### ISSUE TITLE
Target desktop or mobile only

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#102]
https://app.intercom.io/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/all/conversations/5459602577

This is already possible using code (to conditionally initialize the SDK). It might be worth distinguishing between these two segments and guiding users through targeting one or the other (or both).

**Comment by nickpunt** [comment]
Captured elsewhere
