### ISSUE TITLE
Web Push Notifications not working for Chrome on M1 Mac (arm64)

### ISSUE THREAD

**Issue by mrbohnke** [OneSignal/OneSignal-Website-SDK#1034]
Is this known? maybe I'm doing something wrong?
Site with "Typical Site" setup for push notifications on Web Configuration settings.
Tested now on seven computers (all macOS Ventura 13.3.1, Chrome 113.0.5672.63, no extensions, notifications allowed and otherwise totally functional):

Notifications work as expected on all x86 machines, but not on arm ones. Notifications also work on all the other browsers I tested in all the computers. Using the console logging options (as reflected on troubleshooting documentation) you can see that notification information is being received to some extent, but the notifications themselves are not being triggered.

Would appreciate your advice,
Cheers.

**Comment by emawby** [comment]
@mrbohnke Thank you for reporting I do not believe that this is a known issue we will investigate

**Comment by mrbohnke** [comment]
Not sure since I'm not an expert, but I just discovered that this seems to be related to the "persistNotification" config.
When set to false, it does work on every architecture. When set to true, it doesn't work on the arm64 build for M1 Mac machines.

**Comment by jkasten2** [comment]
@mrbohnke This most likely a problem that both Notification permissions are not enabled for Chrome on the macOS level. See the comment https://github.com/OneSignal/OneSignal-Website-SDK/issues/711#issuecomment-782576683 more details.

Chromium issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=1064641#c11

**Comment by jkasten2** [comment]
Closing due to no response, please feel free to open a new issue if you are still running into this problem. Link to this issue if you do so.
