### ISSUE TITLE
[Question]: How can the `from XY` in the messages be removed?

### ISSUE THREAD

**Issue by philipp-schaerer-lambdait** [OneSignal/OneSignal-Website-SDK#1038]
Sorry if this question is in the wrong place, there are alot of repositories though. My client was wondering if it is possible to remove the suffix `from ...` in Push Notifications when the manual Message System is being used.

![image](https://github.com/OneSignal/OneSignal-Website-SDK/assets/19977884/c9fedd8f-46ff-4ef3-862c-6894755b9e50)

Is this possible? If so, where can this be removed? Thank you for your clarification.

**Comment by jkasten2** [comment]
@philipp-schaerer-lambdait you in the right repo to ask this question!

Unfortunately Apple does not allow removing this `from ...` part, it is auto generated by iOS. The default name in your example "Prime News" comes from you web manifest file (normally named `"manifest.json"`), however the end-user may edit this before adding it to their home screen.
