### ISSUE TITLE
[Question]: Does Click behaviour handle hash routing?

### ISSUE THREAD

**Issue by rhurlbatt** [OneSignal/OneSignal-Website-SDK#1048]
### How can we help?

I have a web app that is saved to the homescreen of an Android and ios device. The click url is set to a url with a hash (https://app.example.com/#section1). I have set the click behaviour to be "Origin Navigate".

The problem is that the navigation doesn't seem to work. Is this be cause of hash routing?

How do I get the notification and browser to recognise that the notification url https://app.example.com/#section1 is not equal to https://app.example.com/#listing4 and navigate accordingly (without forcing it to reload the page)?

**Comment by jkasten2** [comment]
@rhurlbatt I don't believe the Web SDK currently supports navigating to a hash / anchor currently. We will mark this as a feature request.

In the meantime you can setup the [OneSignal notification click listener](https://documentation.onesignal.com/docs/web-sdk#notification-clicked) to handle this with your own code however.
