### ISSUE TITLE
[Bug]: Subscription Bell not showing on iOS

### ISSUE THREAD

**Issue by ante-maric** [OneSignal/OneSignal-Website-SDK#1049]
### What happened?

Subscription Bell does not show in Safari on iOS, it works in Edge on PC and Chrome on Android.
On OneSignal web when I open Audience ->Subscriptions I can see a row with Subscribed column checked but Channel and Device columns are empty.

I was testing v9 and it did work on all platforms. Then I migrated to v11 and now I just can't make it work. When I add my PWA to home screen, app is not visible in iPhone Settings like it did when I had v9. So, it's like it isn't recognized as PWA.

Migration guide is a bit confusing:

Service Worker

Download the new [service worker file](https://github.com/OneSignal/OneSignal-Website-SDK/files/11480764/OneSignalSDK-v16-ServiceWorker.zip) and place it next to the original OneSignalSDKWorker.js file.

DO NOT DELETE the original OneSignalSDKWorker.js file.

How should I not delete original OneSignalSDKWorker.js when the new one has the same name? If I place it next to a original it means I have to rename it. And then what?

### What browsers are you seeing the problem on?

Safari

### What operating system are you running?

iOS 16.5.1

### Steps to reproduce?

```Markdown
1. Follow the guide for using web push notifications
2. Open the web app on iOS
```

### What did you expect to happen?

Subscription Bell should show just like on other platforms.

**Comment by jkasten2** [comment]
@ante-maric Thanks for reporting these problems with the new major release of the SDK!

## iOS WebApp Push
iOS WebPush was missing in the v16 branch (AKA v11 OneSignal docs). We merged in the missing feature from main and just released a Beta 6 today:
https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/160000.beta6

## Migration guide
We fixed the wording in the migration guide around the service worker. Let us know if this is clear now:
https://github.com/OneSignal/OneSignal-Website-SDK/blob/160000.beta6/MIGRATION_GUIDE.md#service-worker
