### ISSUE TITLE
[Question]: How to show all notifications and not just the last one?

### ISSUE THREAD

**Issue by ante-maric** [OneSignal/OneSignal-Website-SDK#1054]
### How can we help?

When I send web push notification to iOS, Android and Windows (Edge), only on iOS I can see all notifications until I dismiss them. On Android and Windows just last one is visible. Every new notification just replaces the one that is not yet read. Do I need to change some parameter while sending notification to influence that? I tried using grouping options but that didn't make any difference.

**Comment by jkasten2** [comment]
@ante-maric Sorry for the delay!

You are looking for the [Web Push Topic](https://documentation.onesignal.com/docs/web-push-topic-collapsing#web-push-topic) ([`web_push_topic`](https://documentation.onesignal.com/reference/push-channel-properties#grouping--collapsing) if using the REST API) to change this setting. You will need to set a different value per notification if you want more than one to show. By default OneSignal sets the same value so only the most recent notification per website (domain) will display.

It's odd that iOS WebApps are behaving different, it indicates that it most likely doesn't support the Notification API feature so all notifications are shown. We can leave this ticket open until this part is answered.

**Comment by ante-maric** [comment]
Thanks @jkasten2, that works! Web push notifications on iOS are currently experimental feature, maybe that plays a role in it behaving differently. Also, currently no sound is played for web push notifications on iOS, so other than for testing they are not very useful.

**Comment by jkasten2** [comment]
@ante-maric Push for iOS WebApps isn't labeled as experimental or beta by Apple. It is live and default enabled for all iOS 16.4+ devices, per [Apple's docs](https://developer.apple.com/documentation/usernotifications/sending_web_push_notifications_in_web_apps_safari_and_other_browsers).

Ya seems like the no sound problem is an open issue on Apple's end:
* https://discussions.apple.com/thread/254759442

I would guess Apple may add some of these missing features in the future, since the PushAPI is new in Safari 16.

**Comment by ante-maric** [comment]
I would disagree with you on that. I am on 16.5.1 and Push API must be enabled in Settings -> Safari -> Advanced -> **Experimental Features** to work. It was disabled by default on my device.

**Comment by jkasten2** [comment]
So I believe Settings -> Safari -> Advanced -> Experimental Features controls the APIs in the Safari app itself. Apple requires you to first at the site to your homescreen first, and that "WebApp" doesn't depend on those settings.

I have "Push API" disabled and my WebApps still get push.

**Comment by ante-maric** [comment]
Hmm...you might be right. I was sure it didn't work on my phone until I enabled it, but since I was trying many things and played with beta SDK, I might have draw the wrong conclusion why it started to work.

**Comment by jkasten2** [comment]
@ante-maric I created a new issue to follow up specific on the iOS Web Push showing more than one notification question.
https://github.com/OneSignal/OneSignal-Website-SDK/issues/1099

Closing this issue as this was the only remaining unaddressed item.
