### ISSUE TITLE
Are .getids and .getUserID no longer working?

### ISSUE THREAD

**Issue by DK-Web** [OneSignal/OneSignal-Website-SDK#1083]
### How can we help?

Hi, I'm getting desperate.

The OneSignal Subscription works with:

```js
   window.OneSignalDeferred = window.OneSignalDeferred || [];
   OneSignalDeferred.push(function(OneSignal) {
     OneSignal.init({
       appID: "12345",
     });
   });
```

BUT

No matter how you try, neither .getids nor .getUserID work. Also OneSignal.on does not work.

I always get "... is not a function".

```js
  window.OneSignalDeferred = window.OneSignalDeferred || [];
  OneSignalDeferred.push(function(OneSignal) {
    OneSignal.init({
      appId: "12345",
    });
    OneSignal.getUserId((userId) => {
        if (userId == null){
            alert("Subscribe to Notification First")
            return
        }
        alert(`Player id: is ${userId}`);
    });
  });
```

How do I get the UserID via JS after subscribing so that I can send a targeted push to a user?

Thank you for your support <3

**Comment by jkasten2** [comment]
@DK-Web Thanks for your question. In the major version 16 release most of the SDK's interfaces / functions have changed. I recommend checking out the full [release notes](https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/160000) for v16 if you haven't yet, as it covers the new concepts and API.

For your specific question on getting an id to target later with a push there are two ways to go about it depending if you want to send a push to all devices the User is subscribed to, or just one specific device.

### Option 1 - Target a specific device
To get the subscription id
```js
const id  = OneSignal.User.PushSubscription.id;
```

`id` may be `null` / `undefined`, if so you can use:
```js
OneSignal.User.PushSubscription.addEventListener("change", function(event) {
  if (event.current.id) {
    console.log("Subscription id now available: ", id);
  }
});
```
 to know when it becomes available.
To send a notification use this id with `include_player_ids` to send a notification to that specific device with [OneSignal POST /notifications](https://documentation.onesignal.com/reference/create-notification) REST API.

### Option 2 - Target all devices a User owns 
Call `OneSignal.login("MY_USER_ID_HERE")`. (replace `MY_USER_ID_HERE` with your own internal unique Id you use for your users)
Then to send a notification to all subscribed devices the User owns use `include_aliases` with `external_id` as the same value you set with `OneSignal.login` above. Also set `target_channel` to `push`.
Example:
```JSON
{
  "include_aliases": {
    "external_id": ["external_user_id"]
  },
  "target_channel": "push",
  "isAndroid": true
}
```

See the  [OneSignal POST /notifications](https://documentation.onesignal.com/reference/create-notification) REST API documentation for more details on this targeting.

**Comment by DK-Web** [comment]
> [jkasten2](/jkasten2)

Hi jkasten2, thank you for your quick support!

Thanks to your code I got the whole thing up and running now.

In the meantime I had switched to another (probably older) SDK and it worked:

```
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
<script>
window.OneSignal = window.OneSignal || [];
    OneSignal.push(function() {
        OneSignal.init({
        appId: "12345",
        autoRegister: true,
        autoResubscribe:true,
        notifyButton: {
            enable: true,
        },
        });
        OneSignal.on('subscriptionChange', function (isSubscribed) {
            OneSignal.push(function() { 
                OneSignal.getUserId(function(userId) { 
                    if(userId != null && userId != "" && userId != undefined && userId != 0){
                        console.log(userId);
                    }
                });
            });
        });
    });
</script>
```

But now everything is up to date:

  ```
<script src="https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js" defer></script>
<script>
  window.OneSignalDeferred = window.OneSignalDeferred || [];

  OneSignalDeferred.push(function(OneSignal) {
    OneSignal.init({
      appId: "12345",
    });

    const subscriptionId = OneSignal.User.PushSubscription.id;

    OneSignal.User.PushSubscription.addEventListener("change", function(event) {
    if (event.current.id) {
        console.log(event.current.id);
    }
  });
});
</script> 
```

Thank you and have a nice evening!
