### ISSUE TITLE
[Bug]: Prompt doesn't show in Firefox

### ISSUE THREAD

**Issue by bmulholland** [OneSignal/OneSignal-Website-SDK#1097]
### What happened?

https://github.com/OneSignal/onesignal-vue/issues/40

### What browsers are you seeing the problem on?

Firefox

### What operating system are you running?

https://github.com/OneSignal/onesignal-vue/issues/40

### Steps to reproduce?

```Markdown
https://github.com/OneSignal/onesignal-vue/issues/40
```

### What did you expect to happen?

https://github.com/OneSignal/onesignal-vue/issues/40

**Comment by iAmWillShepherd** [comment]
Closing because this issue is related to Vue.

**Comment by bmulholland** [comment]
@iAmWillShepherd no it’s not, please read my comments on the issue where I post lines of code from this repo

**Comment by bmulholland** [comment]
Please reopen

**Comment by iAmWillShepherd** [comment]
Please write the actual problems in this issue, not just link to other issues. 

It's fine to include relevant links, but we need the actual problem experienced here.

**Comment by jkasten2** [comment]
@bmulholland Appreciate feedback you have been giving us. I created another Github issue for this to start over clean for this Firefox `requestPermission()`.

I provided some details on the approaches we are looking into for this specific issue to give you transparency and the opportunity to comment on them on this ticket:
https://github.com/OneSignal/OneSignal-Website-SDK/issues/1098
