### ISSUE TITLE
[Bug]: Firefox always shows soft-prompt when calling Notifications.requestPermission()

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Website-SDK#1098]
## One Line Summary
Calling `OneSignal.Notifications.requestPermission()` should show the native prompt for all browsers, but it always shows a soft-prompt slidedown prompt for Firefox.

## Details
The [SDK code is checking if the browse requires a user interaction](https://github.com/OneSignal/OneSignal-Website-SDK/blob/160000/src/onesignal/NotificationsNamespace.ts#L128-L129). However the bug is it does not check if that require was met.

### 1. Add code - Interaction detection
If possible, reliable, and maintainable add code to detect if a click / tap requirement was met.
### 2. Remove code - Checking requiresUserInteraction
If option 1 isn't feasible, remove the`requiresUserInteraction` check and calling `OneSignal.Slidedown.promptPush()` in the `requestPermission()` function.

### What browsers are you seeing the problem on?

Firefox

### What operating system are you running?

Windows 11 22H2 and macOS 13.5

### Steps to reproduce?

```Markdown
1. User clicks on an element on the page
2. Call `OneSignal.Notifications.requestPermission()` in response
3. See soft-prompt for push
```

### What did you expect to happen?
```Markdown
1. User clicks on an element on the page
2. Call `OneSignal.Notifications.requestPermission()` in response
3. Should see browser's native prompt for notification permission
```

## Related Issues
https://github.com/OneSignal/OneSignal-Website-SDK/issues/1097

**Comment by bmulholland** [comment]
Another option to consider: provide a param to say "I've already done a soft prompt" that bypasses the check. 

I haven't thought through tradeoffs

**Comment by jkasten2** [comment]
@bmulholland Thanks for the idea, however thinking the API would be easier to understand without the extra parameter and complexity of handling it in this future. If it can't seamlessly be handled here there is probably a better API layer for this.

We are looking at going with option 2 (remove the call to OneSignal.Slidedown.promptPush()). I wasn't able to find any browser APIs to detect if the user interaction requirement was met globally or was done in the call stack. The closest thing is is an [event.isTrusted](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted) API, but again we don't want to introduce a parameter here.
