### ISSUE TITLE
[Question]: Subscription ID -OR- token not available (Chrome)

### ISSUE THREAD

**Issue by eightyfive** [OneSignal/OneSignal-Website-SDK#1104]
### How can we help?

I subscribe to `User.PushSubscription.addEventListener` and I allow the notifications.

* On one Chrome browser: `ev.current.token: undefined` (while `id` is available)
* On another Chrome browser: `ev.current.id: undefined` (while `token` is available)

Why is that?

More generally when to use `id` vs `token`? I can see that to [create a Notification](https://documentation.onesignal.com/reference/create-notification#send-to-specific-devices) via API I need to pass the subscription `id` to `include_subscription_ids`... So what's `token` for?

Thank you in advance 🙏

**Comment by eightyfive** [comment]
By the way, when no `id` is available, this causes a Web SDK error:

```
ExecutorBase.js:93 n: processSubscriptionModel: missing onesignalId: {"subscribers":{},"modelName":"pushSubscriptions","modelId":"<REDACTED>","data":{"type":"ChromePush","token":"https://fcm.googleapis.com/fcm/send/<REDACTED>","enabled":true,"notification_types":1,"sdk":"160001","device_model":"MacIntel","device_os":87,"web_auth":"<REDACTED>","web_p256":"<REDACTED>"},"awaitOneSignalIdAvailable":{}}
    at on (https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.es6.js?v=160001:1:241091)
    at fn.<anonymous> (https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.es6.js?v=160001:1:243504)
    at Generator.next (<anonymous>)
    at https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.es6.js?v=160001:1:326124
    at new Promise (<anonymous>)
    at o (https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.es6.js?v=160001:1:325869)
    at fn.updateSubscription [as _executeUpdate] (https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.es6.js?v=160001:1:243383)
    at fn.<anonymous> (https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.es6.js?v=160001:1:249980)
    at Generator.next (<anonymous>)
    at r (https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.es6.js?v=
```

**Comment by jkasten2** [comment]
@eightyfive `id` might be `undefined` if the browser hasn't registered with OneSignal yet. `token` is the push token the bowser gives the SDK, once this is available the SDK will automatically register with OneSignal's backend where it will get an `id`.

 The `token` isn't something most workflows will need, if you are looking to send notifications you only need to use the `id` with `include_subscription_ids` as you noted. The `token` is only useful for debugging or doing something with it outside of OneSignal.

Can you provide details on reproducing the `processSubscriptionModel: missing onesignalId` error you are seeing?

**Comment by eightyfive** [comment]
Unfortunately I moved away from this lib due to time constraints. As far as I remember the `id` was never picked up (even with listener).

**Comment by DavidQuartz** [comment]
i get an error in Firefox saying "updateSubscription: subscriptionId is not defined"

The methods I besides `OneSignal.Notifications.requestPermission()` are:
- `OneSignal.User.PushSubscription.optIn()`
- `OneSignal.User.PushSubscription.optOut()`
- `OneSignal.User.addAlias('external_id', <userName>)`

**Comment by nmpco1209** [comment]
hello, I have the same issue on old applications.

![image](https://github.com/OneSignal/OneSignal-Website-SDK/assets/100655852/d1af8dc1-3f7f-4ece-ae15-dc8c7fda0426)

But it works if I create new application

**Comment by tanikatech** [comment]
@nmpco1209 

I am having the same exact issue, any solutions if you have found so far ?

**Comment by nmpco1209** [comment]
hello @tanikatech 
I have temp solution:
Open `Keys and IDs` then turn off `Identity Verification for email + external_id (recommended)`.
it seems that we have to wait for Web SDK release.


![image](https://github.com/OneSignal/OneSignal-Website-SDK/assets/100655852/36d5f2af-73d4-4657-bd9b-30c7faf8755e)

![image](https://github.com/OneSignal/OneSignal-Website-SDK/assets/100655852/ca716243-7ecb-4b11-a941-98df979a02e7)
