### ISSUE TITLE
OneSignal SDK is not compatible with this browser on Safari Mobile

### ISSUE THREAD

**Issue by MakhBeth** [OneSignal/OneSignal-Website-SDK#1126]
Hello!

Currently on Safari iOS the SDK doesn't load at all. 

Since web ios notifications for safari mobile have been implemented by Apple.

Will this also help us with the mobile safari? 

Currently I'm getting this in mobile safari: 

![image](https://github.com/OneSignal/OneSignal-Website-SDK/assets/7522178/097843d3-32e3-4e0e-b270-d755da9c9744)

(This is with installing a build `yarn build:prod` and moving these bundled files to the public folder root)

Am I missing something?

@jkasten2 

> ## iOS WebApp Push
> iOS WebPush was missing in the v16 branch (AKA v11 OneSignal docs). We merged in the missing feature from main and just released a Beta 6 today: https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/160000.beta6
> 
> ## Migration guide
> We fixed the wording in the migration guide around the service worker. Let us know if this is clear now: https://github.com/OneSignal/OneSignal-Website-SDK/blob/160000.beta6/MIGRATION_GUIDE.md#service-worker

_Originally posted by @BramDecuypere in https://github.com/OneSignal/OneSignal-Website-SDK/issues/619#issuecomment-1677348095_

**Comment by jkasten2** [comment]
@MakhBeth Thanks for the question, it requires installing your site as a Web App, see [Mobile Web Push for iOS/iPadOS](https://documentation.onesignal.com/docs/safari-web-push-for-ios)

We will look into seeing if we can improve the "SDK is not compatible with this browser" message to point out this requirement.

**Comment by MakhBeth** [comment]
Thanks @jkasten2. Yes a better message will surely improve DX
