### ISSUE TITLE
[Question]: Can't get Notification click event

### ISSUE THREAD

**Issue by fearistoff** [OneSignal/OneSignal-Website-SDK#1127]
I have successfully subscribed and receiving Notifications. But when in click any of them, after focusing tab with same origin (Matching Strategy: Origin, Action Strategy: Navigate) nothing happens.

I've also added Notification handler `oneSignal.Notifications.addEventListener`, but event not triggering, despite the fact that a message in the Service Worker about a click on the Notification appears in the console.

**Comment by fearistoff** [comment]
I'm using npm-package for vue `@onesignal/onesignal-vue3@2.0.1`. And `OneSignalSDK.sw.js` version 16 from documentation.

**Comment by jkasten2** [comment]
@fearistoff Thanks for reporting these issues.

> I have successfully subscribed and receiving Notifications. But when in click any of them, after focusing tab with same origin (Matching Strategy: Origin, Action Strategy: Navigate) nothing happens.

I attempted to reproduce this issue on Chrome 119 on Windows 11 and have not been able to reproduce this issue. I have tested with a custom luachURL and with default. Can you share more details?

> I've also added Notification handler oneSignal.Notifications.addEventListener, but event not triggering, despite the fact that a message in the Service Worker about a click on the Notification appears in the console.

There is an SDK if the notification click results in opening a new tab this was not firing on the new tab. We are addressing this bug in PR #1132 and will be shipped soon.

**Comment by jkasten2** [comment]
@fearistoff The `OneSignal.Notifications.addEventListener('click', function() {})` issue has now been fixed and release.

Please provide more information on the first part of your issue noted above.

**Comment by fearistoff** [comment]
> I attempted to reproduce this issue on Chrome 119 on Windows 11 and have not been able to reproduce this issue. I have tested with a custom luachURL and with default. Can you share more details?

For some reason it works now. Maybe I should resubscribe to apply settings changes in web-client. But after focus tab navigation in it ape happening with some random delay (up to one second), but that is okay.

I think that question we can close.

**Comment by jkasten2** [comment]
@fearistoff good to hear things are working for you now! I'll mark this issue as resolved.
