### ISSUE TITLE
[Question]: OneSignal External ID setting using new OneSignal.login() method not working

### ISSUE THREAD

**Issue by programmerxx89** [OneSignal/OneSignal-Website-SDK#1150]
Hi,
 
I'm struggling to set the External ID of any subscriber of my OneSignal app using the new OneSignal.login() method.
This is the method suggested in the official OneSignal documentation, but after so many tentatives it's really impossible for me to set the External ID of any subscriber of my web push notification service.
This below is the code I'm implementing and not working:
 

 
I've also tried to move the OneSignal.login() method outside of the script but nothing really change.
 
Does anyone have some useful input for me?
 
Thanks
 
Gigi

**Comment by Morenoo1105** [comment]
Did you ever solve this? I'm having the same issue :)

**Comment by HeinKoZin** [comment]
Did someone solve this problem?
