### ISSUE TITLE
ARIA accessibility for prompts

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#117]
Conversation: https://app.intercom.io/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/web-push-team/conversations/5775252244

Link: https://www.marcozehe.de/2013/04/24/easy-aria-tip-6-making-clickables-accessible/

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
