### ISSUE TITLE
hiding the notify button

### ISSUE THREAD

**Issue by pcarion** [OneSignal/OneSignal-Website-SDK#119]
Hi,

We have a SPA application, meaning the the init() method is called once. We are displaying the notiy button by default but we would like to hide it once the user has requested to receive notification.
What is the API to hide the notify button ?

**Comment by gdeglin** [comment]
Hi. Here's our guide on hiding the notify button after a user subscribes: https://documentation.onesignal.com/docs/customizing-features#section-how-do-i-hide-the-notify-button-after-subscribing-or-only-show-it-on-certain-pages-
