### ISSUE TITLE
[Bug]: ReplayCallsOnOneSignal.js:6 Uncaught TypeError: e is not iterable at o.processOneSignalDeferredArray, facing this issue whenever my app loads.

### ISSUE THREAD

**Issue by aman-u-7span** [OneSignal/OneSignal-Website-SDK#1190]
### What happened?

I'm using Vue3 

**index.html**

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=yes"
    />
    <script src="https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js" defer></script>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
```

**oneSignal.js** (File i'm using to initialize one signal in the app)

```
async function getAccessToken() {
    try {
      window.OneSignalDeferred = window.OneSignalDeferred || []
      OneSignalDeferred.push(async function (OneSignal) {
        await OneSignal.init({
          appId: import.meta.env.VITE_ONE_SIGNAL_APP_ID,
          notifyButton: {
            enable: true
          }
        })
        const isPushNotificationSupported = OneSignal.Notifications.isPushSupported()

        await OneSignal.Notifications.requestPermission()

        if (
          isPushNotificationSupported &&
          OneSignal.Notifications.permission &&
          OneSignal.Notifications.permissionNative === 'granted'
        ) {
          console.log(OneSignal.User.PushSubscription.id)
          /* Code to save id in backend */
        } else {
          toast.notify({
            title: 'Check browser settings to recieve push notifications.',
            type: 'warning'
          })
        }
      })
    } catch (error) {
      console.log(error)
      handleGlobalError(error)
    }
  }
```
  
 I'm not sure what i'm doing wrong, Onesignal-vue3 plugin didn't workout for me so had to use web-sdk for this one. Any guidance would be really helpful.
 
<img width="499" alt="Screenshot 2024-09-06 at 12 06 24 PM" src="https://github.com/user-attachments/assets/b59698bf-c935-4fdf-8780-5a8f6a83093f">

### What browsers are you seeing the problem on?

Chrome (Chromium), Safari, Brave

### What operating system are you running?

macOS monterey 12.7.1

### Steps to reproduce?

```Markdown
Just use my code with vue3 and start the app with `npm run dev`
```

### What did you expect to happen?

I expected it to work normally and also found that push notifications are bit inconsistence.

**Comment by aleksi-magner** [comment]
Try immediately after init to bind the context of the current user via the login(<external_id>) method

**Comment by aman-u-7span** [comment]
@aleksi-magner Tried it, still same issue. The thing is that this console error occurs even before init.

**Comment by aleksi-magner** [comment]
@aman-u-7span Isn't there a call somewhere to `OneSignalDeferred.push()` before this `getAccessToken` method is called? It looks like the `window.OneSignalDeferred = window.OneSignalDeferred || []` initialization should be earlier

**Comment by aman-u-7span** [comment]
@aleksi-magner I tried calling `.push()` in index.html as well. Issue still persists.

**Comment by aleksi-magner** [comment]
@aman-u-7span For me, this error is reproduced only if `window.OneSignalDeferred` is not yet defined before the first call to `window.OneSignalDeferred.push()`. Therefore, I clarified - is `window.OneSignalDeferred` initialized before the first call to `window.OneSignalDeferred.push()`?

![изображение](https://github.com/user-attachments/assets/214dde88-8f52-4af1-b331-d0300dfca381)

**Comment by aman-u-7span** [comment]
Ahh okay I got it. I was able to resolve the issue by initialising script manually and then defining the `window.OneSignalDeferred`. Thanks a lot mate @aleksi-magner
