### ISSUE TITLE
[Bug]: Receives push notification only if tab is closed, can anyone please help me with this one ?

### ISSUE THREAD

**Issue by aman-u-7span** [OneSignal/OneSignal-Website-SDK#1193]
### What happened?

OneSignal is initialised successfully and there are no error or warnings in browser but this seems to be very weird behaviour as push notifications are received only if tab is completely closed. 

### What browsers are you seeing the problem on?

Firefox, Chrome (Chromium), Safari

### What operating system are you running?

macOS monterey 12.7.1

### Steps to reproduce?

```Markdown
- This is the cdn i'm using 'https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.js'.
- importScripts("https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.sw.js") this is inside my service-worker file.
```

### What did you expect to happen?

I expect to receive notifications even if tab is active or inactive.

**Comment by dongph9x** [comment]
Maybe sw of onesignal conflict with other sw, please move sw of onesignal without root folder

**Comment by dongph9x** [comment]
Change scope and path of OneSignalSDKWorker.js

**Comment by aman-u-7span** [comment]
@dongph9x I didn't have any other service worker but moving service worker to another folder worked. Thanks mate really appreciate it.
