### ISSUE TITLE
[Feature request] add extra data to subscription

### ISSUE THREAD

**Issue by quochuy** [OneSignal/OneSignal-Website-SDK#121]
That would be nice if there was a way to send extra data to a subscription.
What I imagine is when a user subscribed to a website, a script would capture the event, and ask the user if he want to subscribe to all messages or only for specific categories and then send the data to OneSignal.

Then when I send a message, I could select to send it to only users of specific categories.

**Comment by jasonpang** [comment]
Hello @quochuy,

What you're describing sounds a lot like our tags feature. Could you take a look at this and let us know if you have any more questions? https://documentation.onesignal.com/docs/guides-examples#tagging

You can call `sendTags` at any time, and the tags will automatically be sent after the user is subscribed if the user isn't already subscribed,
