### ISSUE TITLE
Change Firefox prompt notification dismiss behavior

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#124]
If a user dismisses the notification prompt, we store a flag to not bother the user again.

On Chrome, dismissing the notification prompt is intentionally done by clicking "X" (clicking the page will not dismiss the prompt).

On Firefox, the prompt is dismissed too easily by clicking elsewhere on the page. Users accidentally clicking elsewhere will not see the prompt, and will not subscribe. The prompt also does not nest in the address bar to be "re-prompted". So the user will have to "know" to click the OneSignal button (which most users don't know or won't click themselves).

So we should re-think this behavior, or for Firefox only, we should still reprompt.

**Comment by jasonpang** [comment]
The problem is, clicking X to dismiss the Firefox prompt, or clicking anywhere on the page, or alt-tabbing to a new window, are all *treated identically* and reported as "Error: User did not grant push permission". We're not able to distinguish between the user clicking X and the user simply alt-tabbing away or clicking on the page.

I thought about of re-showing the prompt asking users to subscribe if they inadvertently

**Comment by jasonpang** [comment]
Not sure of a workaround at this point, I would rather err on the side of caution and not re-prompt the user on each page until he either blocks or allows.

**Comment by calevano** [comment]
![image](https://user-images.githubusercontent.com/1764561/34017065-22fa7786-e0f2-11e7-82ec-d4eb9554d498.png)

Web Browser Firefox

Help me!

**Comment by jasonpang** [comment]
Firefox no longer dismisses the notification permission prompt by clicking elsewhere on the page.
