### ISSUE TITLE
Support Opera for push notifications

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#130]
Opera on Android and Opera on Desktop.

**Comment by jasonpang** [comment]
#### Opera on Desktop

Opera for Desktop does not seem to support push notifications. Multiple push notification services and Gauntface's simple push demo returns an `AbortError: Registration failed - push service not available`. Gauntface [said he posted to Opera's bug tracker](https://github.com/gauntface/simple-push-demo/issues/69#issuecomment-233769243) about this but Opera's  bug tracker is closed to the public.

> Opera sadly show all the API's as available on desktop and then throw an error when you attempt to subscribe the user for push. I've raised an issue with Opera but it's a closed bug tracker so not a clue what they are doing / what they think about it.

People on the Opera forums have also mentioned the Registration failed error since version 37 (browser now currently version 40), and I couldn't find an official response for this.

#### Opera on Android

Opera on Android is now working, fixed by https://github.com/OneSignal/OneSignal-Website-SDK/pull/138.

**Comment by jasonpang** [comment]
Opera on Desktop v42+ now working.

**Comment by jasonpang** [comment]
Fixed by https://github.com/OneSignal/OneSignal-Website-SDK/commit/8f8206634d44e69938974afc990eb10cfce4e9cd and deployed.

**Comment by Bizarrus** [comment]
The Notification bus is also in `52.0.2871.64`. Here, Notifications won't work with `registration.showNotification`, but push works, i can print out the data to the console.

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36 OPR/52.0.2871.64`
