### ISSUE TITLE
Invalid Google Credentials for Web Push

### ISSUE THREAD

**Issue by yishus** [OneSignal/OneSignal-Website-SDK#135]
Following an update in the dashboard, the field for Google Server API key in the configurations for web push has been removed. The new documentation (great documentation by the way! 👍) is stating that we should be putting "482941778795" as the gcm_sender_id.

Doing so we are getting Invalid Google Credentials error showing in the dashboard.

![screen shot 2016-09-27 at 5 58 54 pm](https://cloud.githubusercontent.com/assets/5773874/18869622/ad544468-84df-11e6-8f70-88a95bc69370.png)

**Comment by jasonpang** [comment]
Hey @yishus,

Could you reach out to us over our chat support after logging in to your account? We'll give you specific instructions on how to fix this error.
