### ISSUE TITLE
help me mismatch senderiderror

### ISSUE THREAD

**Issue by jeffersonmello** [OneSignal/OneSignal-Website-SDK#139]
Mismatched Users
Google returned a MismatchSenderId error. Some users' GCM registration tokens are tied to a Google Server API key that no longer matches your current project's Google Server API key.

**Comment by jasonpang** [comment]
Hey @jeffersonmello,

Sorry you're running into this issue. Would you mind logging in to your OneSignal account and contacting us on our support channel there? We'll be able to look into your account that way and help you out better.
