### ISSUE TITLE
Wrong playerid returned while registering on chrome.

### ISSUE THREAD

**Issue by rohanjulka** [OneSignal/OneSignal-Website-SDK#147]
Hi,

 I have checked the endpoint URL:
https://onesignal.com/api/v1/players/[the-player-id]
It returned JSON received: {"allresponses":"{\"errors\":[\"No user with
this id found\"]}"}

Following are the query parameters:
https://onesignal.com/api/v1/players/b7a0f8f7-5de3-4ad6-a35c-d9411a488e2b?app_id=8896d1c1-d57f-4e82-85a5-fe16af394e43

b7a0f8f7-5de3-4ad6-a35c-d9411a488e2b is the playerid that I got in response when subsreibed on chrome .

The user subscribed from chrome browser.
I have also tried with firefox and it works fine there. but for chrome its
failing and returning wrong playerid in js response.

Please help.

**Comment by gdeglin** [comment]
I have re-opened #146 and followed up there.
