### ISSUE TITLE
Close the subscription window after a hard timeout

### ISSUE THREAD

**Issue by rohanjulka** [OneSignal/OneSignal-Website-SDK#149]
Hi!

After the recent update to chrome version 54 the popup windows that opens when the user goes to register for Push notifications then that window takes long time to close and also the user is not registered for Push and not playerid is returned .

**Comment by rohanjulka** [comment]
I also got the message in console as :

**Error while subscribing for push: A possible Chrome bug** (https://bugs.chromium.org/p/chromium/issues/detail?id=623062) is preventing this subscription from completing.(anonymous function) @ OneSignal.js:1581

**Comment by jasonpang** [comment]
Fixed by: https://github.com/OneSignal/OneSignal-Website-SDK/commit/78adb6d162ac667f5fb2cf286dfa9c7d144c8697
