### ISSUE TITLE
MooTools incompatibility Cannot read property css of undefined

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#150]
jdan made a great explanation on https://github.com/Khan/tota11y/issues/29

**Comment by tixastronauta** [comment]
@jasonpang I came across with the same problem. How did you manage to solve this? Thank you!

**Comment by jasonpang** [comment]
Hey @tixastronauta,

Can you try using the "without compatibility layer" version of MooTools? That might fix the issue. We don't use MooTools but we see some developers using our SDK run into the issue.

**Comment by tixastronauta** [comment]
I would if I could. Sadly this incompatibility is with a third party who's unwilling to change a single thing on is MooTools installation. Thanks @jasonpang!
