### ISSUE TITLE
Notify button not hidden when popover shown; not restored when popover closed if notify button enable is false

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#152]

**Comment by jasonpang** [comment]
This user is affected by this issue: https://app.intercom.io/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/a/web-push-team/conversations/6363522045

What ends up happening is that the user kind of is given the prompt to subscribe twice, which is a horrible and confusing user experience.

**Comment by jasonpang** [comment]
^ Actually this isn't true and the popover does hide the notify button when shown, and the notify button is shown after the popover is closed. However, users still have ample time (while the site loads) to click the red notify button, and then later click the popover Allow.

The original issue was for `setStyle is undefined` when closing the HTTP popup window. There's a console error that's been there for a while.

**Comment by jwilm** [comment]
@jasonpang says this can be closed
