### ISSUE TITLE
isPushNotificationsEnabled not returning in Safari

### ISSUE THREAD

**Issue by crabmusket** [OneSignal/OneSignal-Website-SDK#158]
I've got OneSignal working fine on Chrome and Firefox using a script something like this:

```js
OneSignal.push(() => {
    console.log('THIS');
    this.push.supported = OneSignal.isPushNotificationsSupported();

    OneSignal.isPushNotificationsEnabled().then(val => {
        console.log('THAT');
    });
});
```

While this works perfectly on Chrome in OSX 10.11.6, it doesn't work in Safari. `THAT` is never logged to the console, even though `THIS` is. I'm using Safari 10.0.1. I'm not sure where to start debugging this! There are no console errors or anything (AFAICT), the promise just never seems to resolve.

I should note that this browser has never registered for OneSignal, if that affects the way the method works. However, it seems to return as expected when I test it in a Chrome that has never registered either.

**Comment by jasonpang** [comment]
I believe `isPushNotificationsEnabled()` won't begin to do its work until our SDK is initialized. If the SDK is being initialized in Chrome but not Safari, can you check whether you're missing a Safari web ID in the init options that might be making the init() return early in Safari?

Returning early in Safari if an init option is missing and not initializing at all isn't ideal behavior; we're not going to fix this in the moment, but in a later refactor we'll keep this in mind.

Also turn on the debug logs of our SDK for much more detailed information: https://documentation.onesignal.com/docs/troubleshooting-web-push#section-debugging-using-browser-developer-tools

**Comment by crabmusket** [comment]
Oh, I haven't added the Safari web ID - where should that go? I can't see anywhere [here](https://documentation.onesignal.com/docs/web-push-sdk#section--init-).

**Comment by jasonpang** [comment]
Hey crabmusket,

Thanks for pointing that out. Those docs have been updated :)

**Comment by tenbits** [comment]
It was really frustrating when `getNotificationPermission` promise was neither resolved, nor rejected.  Logs shown the error, but imho also the methods should be reject, so that the app can handle the errors.
