### ISSUE TITLE
`setSubscription` does not fire.

### ISSUE THREAD

**Issue by gigablox** [OneSignal/OneSignal-Website-SDK#159]
`setSubscription` does not fire - I'm not seeing any HTTP traffic for this event in my console.

**Comment by jasonpang** [comment]
Hey there,

`setSubscription` isn't an event. It looks like `subscriptionSet` is an internal event that's fired after calling the method `setSubscription()`. Or maybe you're looking for the `subscriptionChange` event?

**Comment by jasonpang** [comment]
That probably fixed it, so closing the issue.
