### ISSUE TITLE
DOMException: Registration failed

### ISSUE THREAD

**Issue by pcarion** [OneSignal/OneSignal-Website-SDK#162]
Hi,

I have an error when trying to subsctibe a user. We are not using the default notification button, but we are triggering the registration from one of our UI component.

We are using OneSignal from the CDN so we are using the latest SDK and I have cleaned up the browser following the instructions [here](https://documentation.onesignal.com/docs/troubleshooting-web-push#clearing-your-cache-and-resetting-push-permissions).

The steps are as follow:

I am initializing theOneSignal SDK using:

```
var OneSignal = window.OneSignal || [];
OneSignal.push(["init", {
    appId: “our app id”,
    autoRegister: false,
    notifyButton: {
        enable: false, 
        position: 'bottom-right',
        offset: {
            bottom: '50px',
            left: '20px', 
            right: '20px' 
        }
    },
    persistNotification: false
}]);
```

following an interaction of the user with one of our UI component, we programmatically try to subscribe to OneSignal notifications using:

```
const OneSignal = window.OneSignal;
if (OneSignal) {
    OneSignal.push(function() {
        OneSignal.registerForPushNotifications({
            modalPrompt: true
        });
    });
}
```
Your subscription dialog box appear, but when I press "ALLOW" , I get this error:

```
ServiceWorker.js:778Error while subscribing for push: DOMException: Registration failed - missing applicationServerKey, and gcm_sender_id not found in manifest(anonymous function) @ ServiceWorker.js:778
webAppManifest.json:1 Manifest: unknown 'orientation' value ignored.
```

The HTML page containing the application has, in its `HEAD` section:

```
<link rel="manifest" href="/webAppManifest.json">
```

and the `webAppManifest.json` contains, among other application specific data:

```
start_url: "/",
display: "standalone",
gcm_sender_id: "482941778795",
orientation: "portrait-primary landscape-secondary"
```

so, we see that:

* `gcm_sender_id` is pesent and is using the new value recommended in your documentation (it used to be an application specific value before)
* I have no clue what `applicationServerKey` can be and I can't find any reference to that in your documentation.

Any help would be appreciated.

Thanks

Pierre

**Comment by gdeglin** [comment]
We've seen that this error can happen if the manifest file has a formatting error, if there is a second manifest file on the page that is overriding the first (a website may only have one manifest file), or if the manifest file is not in the <head> section of your page.

Please get in touch with us at support@onesignal.com and share your website URL if possible. If your website is locally hosted, please send us a copy of the HTML source code as well as the full exact contents of your webAppManifest.json file and we'll look into this further.
