### ISSUE TITLE
Welcome notification fires before user is subscribed

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#167]
This would be why the welcome notification is sometimes not received. The call to subscribe() is made first, but sometimes the call takes a while, and a welcome notification is sent before the subscribe() call is even finished.

Log: https://uploads.intercomcdn.com/i/o/13305797/1a4b15d2b06e298725bea80e/www.meliuz.com.br-1479326639435.txt

[Conversation](https://app.intercom.io/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/web-push-team/conversations/6220258376)

**Comment by pdf13** [comment]
@jasonpang Thank you very much for your attention!
I am available for help you or bring any other information about the problem.

**Comment by jasonpang** [comment]
Actually the welcome notification fires when subscriptionChange is true, and subscriptionChange only fires if isPushNotificationsEnabled() is true.
