### ISSUE TITLE
Notifications not triggering

### ISSUE THREAD

**Issue by antbirch1990** [OneSignal/OneSignal-Website-SDK#174]
Hey,

I have a website with several logins which are successfully sending tags and assigning users to Segments. The issue I have is that when I call the function to trigger a notifications to all users (in a Segment) no notification ever appears. I have testing on both Chrome and Safari but no luck. I have also gone through the troubleshooting guide but again no luck.

**Results from troubleshooting:**

`OneSignal.log.setLevel('trace');` undefined

`OneSignal.isPushNotificationsEnabled(function(isEnabled) { console.log('Debug Log: Push notifications are enabled:', isEnabled); });` Debug Log: Push notifications are enabled: true

`OneSignal.sendSelfNotification()` undefined ... no notification ever appears.

**Init and sending tags (all working):** 

```
var OneSignal = window.OneSignal || [];

OneSignal.push(function() {
    OneSignal.init({
        appId: "1a95c98a-9349-4876-b9ce-981893b7bf42",
        autoRegister: true,
        notifyButton: {
            enable: false
        },
        welcomeNotification: {
            disable: true
        },
        safari_web_id: 'web.onesignal.auto.613528e9-2930-4b07-a098-5a9518822d98'
   });

    OneSignal.sendTags({
        userType: 'developer'
    });
});
```

**Send notification to segment users (not working):**

```
<?php
    function sendMessage(){
		$content = array(
            "en" => 'Test Message'
        );
		
		$fields = array(
			'app_id' => "1a95c98a-9349-4876-b9ce-981893b7bf42",
			'included_segments' => array('Developers'),
			'data' => array("userType" => "developer"),
			'contents' => $content
		);
        
        //'filters' => array(array("userType" => "developr")),
        // or
        //'included_segments' => array('Developers'),
		
		$fields = json_encode($fields);
    	//print("\nJSON sent:\n");
    	//print($fields);
        
        //echo "<script type='text/javascript'>alert('$fields');</script>";
		
		$ch = curl_init();
		curl_setopt($ch, CURLOPT_URL, "https://onesignal.com/api/v1/notifications");
		curl_setopt($ch, CURLOPT_HTTPHEADER, array('Content-Type: application/json; charset=utf-8',
												   'Authorization: Basic NGEwMGZmMjItY2NkNy0xMWUzLTk5ZDUtMDAwYzI5NDBlNjJj'));
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
		curl_setopt($ch, CURLOPT_HEADER, FALSE);
		curl_setopt($ch, CURLOPT_POST, TRUE);
		curl_setopt($ch, CURLOPT_POSTFIELDS, $fields);
		curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);

		$response = curl_exec($ch);
		curl_close($ch);
		
		return $response;
	}
	
	$response = sendMessage();
	$return["allresponses"] = $response;
	$return = json_encode( $return);
	
	//print("\n\nJSON received:\n");
	//print($return);
	//print("\n");
?>
```

Finally I spoke with Jason and tried the following code in Chrome and got the results as shown below:

```
function isPushNotificationsEnabledVerbose() {
    console.log('isPushNotificationsEnabledVerbose()');
    Promise.all([
            OneSignal.getUserId(),
            OneSignal.getRegistrationId(),
            OneSignal.getNotificationPermission(),
            OneSignal.getSubscription(),
            OneSignal.isServiceWorkerActive()
        ])
        .then(([userId, registrationId, notificationPermission, optIn, serviceWorkerActive]) => {
            let isPushEnabled = false;
      
            console.log('OneSignal Registered User ID (from our server after registering):', userId);
            console.log('GCM Registration ID (token used to send push, sent to our server during registration):', registrationId);
            console.log('Notification permission for this origin:', notificationPermission);
            console.log('NOT Manually Opted Out from calling setSubscription(false) (confusing, but this should say true):', optIn);
            console.log('Is a service worker registered and active:', serviceWorkerActive);
            console.log('What is the current URL of this page?:', location.href);
            console.log("What environment does OneSignal think we're in?", OneSignal.environment.getEnv());
        })
        .catch(e => {
            log.error("Issue determining whether push is enabled:", e);
            reject(e);
        });
}
isPushNotificationsEnabledVerbose();
```

OneSignal Registered User ID (from our server after registering): 896dede3-f808-4c94-80f2-3cc7fac2fa89 
VM125:14 GCM Registration ID (token used to send push, sent to our server during registration): fZdDRRQvzOM:APA91bGc5-u1InOfZ6suOCOlTflBBajlR3cstdHTmH4ZoxeBzlX9EjkKCqOPedsdgrd9Hn-tx-_G2ulFCn_46wYyCSVBSQFtB3SK97W6F-Co4NEc1YQ0WurDWQlJDbv7FZns3aFnnOnp 
VM125:15 Notification permission for this origin: granted 
VM125:16 NOT Manually Opted Out from calling setSubscription(false) (confusing, but this should say true): true 
VM125:17 Is a service worker registered and active: true 
VM125:18 What is the current URL of this page?: https://www.ucouldbe.com/developer.php 

Thanks in advance for any help.

**Comment by jasonpang** [comment]
Hey there,

Sorry you're running into this issue, and thanks for all your work on trying to figure out the issue! Let's try getting a notification to show on Chrome first, since we have more tools available to debug the issue.

First, please make sure you're not running Chrome in full-screen mode. Full-screen mode in Chrome automatically hides notifications.

Second, please make sure you're not running Chrome in Incognito mode, as I believe the Push API is disabled in Chrome's incognito mode.

Please open chrome://gcm-internals and click _Start Recording_. Then call OneSignal.sendSelfNotification() again. Do you see an entry appear on chrome://gcm-internals?

If no, please visit your OneSignal dashboard and visit Sent messages -> View: API Notifications, and check the list to make sure that your notification was actually sent. If it was sent, it would be recorded there.

If you see an entry on chrome://gcm-internals, but you do not see the corresponding notification, please visit chrome://serviceworker-internals, and find the entry with Scope: https://www.ucouldbe.com. Then click Inspect, or Start -> Inspect. Type `OneSignalWorker.log.setLevel('trace');` and then send yourself a notification. You should see output that says something like `onPushReceived` with a lot of log output describing the incoming notification. If you see an error, that would be why you're not seeing a notification.

**Comment by antbirch1990** [comment]
Hey,

No problem, thanks for the help so far.

Running`OneSignal.sendSelfNotification()`shows an entry and now shows the test notification. Not sure why this now works. 

I still cannot seem to trigger the notification via my function sendMessage (shown in the first message).

**Comment by jasonpang** [comment]
Hi antbirch1990,

Maybe you're not a member of the Developers segment? If you send a message using your custom sendMessage() function, do you see the message appear in chrome://gcm-internals? If so, you know for sure the browser has received the message. If you also see log output from our service worker, then you know for sure our background worker tried to process the message at least, and it should be displayed after that if there are no console errors from our worker.

**Comment by antbirch1990** [comment]
Hey,

I've attached an image to show I am a member of the Developer segment (from what I can see anyway).

![screen shot 2016-11-25 at 12 55 58](https://cloud.githubusercontent.com/assets/8056709/20626042/ca846628-b30e-11e6-8369-91f13d0a9891.png)

The sendMessage function does not show up in chrome://gcm-internals.

UPDATE: I've managed to get the following message to print from the sendMessage function (I've removed my app ID):

JSON sent: {"app_id":"APP_ID_HERE","included_segments":["All"],"data":{"foo":"bar"},"contents":{"en":"English Message"}} JSON received: {"allresponses":"{\"errors\":[\"Segment or tag targeting requires a valid App REST API key.\"]}"}

**Comment by jasonpang** [comment]
Awesome, glad you got it! In the future, we'll see if we can improve error messages to more directly lead developers to fixing the cause of the error right away.
