### ISSUE TITLE
ModalPopup blocked main UI when OneSignal was down

### ISSUE THREAD

**Issue by shyamal890** [OneSignal/OneSignal-Website-SDK#175]
I notice that your site was down during 12:30-12:50 pm IST time.

I had set OneSignal.registerForPushNotifications({ 
modalPrompt: true 
}); 

Which means if a user has not yet registered, he would get a modal popup for subscribing.
However, when your site was down, only the modal backdrop popped up blocking the UI without any modal.

I urge the technical team to please have a look at this part of code urgently as even if OneSignal is down it shouldn't be blocking the main site.

**Comment by jasonpang** [comment]
@shyamal890 

Thanks for reporting this. We'll fix this right away.

**Comment by jasonpang** [comment]
Fixed by: https://github.com/OneSignal/OneSignal-Website-SDK/commit/d1ccd373213bc5c4df71e32515ce3d314d84f592
