### ISSUE TITLE
Partial resubscriptions should not trigger welcome notifications

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#180]
In the same way that mismatched users being reset do not trigger welcome notifications on re-subscription, resubscriptions where the user was previously subscribed should not trigger the welcome notification since this is confusing to the user who sees a welcome notification out of nowhere.

Note: This only applies to HTTPS sites.

[Conversation](https://app.intercom.com/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/web-push-team/conversations/7142532382)

**Comment by jwilm** [comment]
This is resolved
