### ISSUE TITLE
Once the user clicks on the received notification, the webpage should be reloaded

### ISSUE THREAD

**Issue by seme1** [OneSignal/OneSignal-Website-SDK#182]
I used to have this on my website working just fine. Today, I noticed that it's repeatedly refreshing the page forever (infinite loop). It's supposed to refresh a certain web page only once, and only when the user clicks on the received notification.

`OneSignal.push(["addListenerForNotificationOpened", function(data) { 
console.log("Received NotificationOpened:", data); 
if(location.href.substr(location.href.lastIndexOf("/")+1).startsWith("read.php")){ 
window.location.href = window.location.href ; 
} 
}]);
`

**Comment by jasonpang** [comment]
Fixed by: https://github.com/OneSignal/OneSignal-Website-SDK/commit/1504e3cdaee2214351dbd8fa15fc80a549c9e9a1
