### ISSUE TITLE
Error on some user's browsers

### ISSUE THREAD

**Issue by bmd-bentar** [OneSignal/OneSignal-Website-SDK#183]
I got some issues for my users. On their console log, it's written like these:
- Uncaught Error: Invocation of form runtime.connect(null, ) doesn't match definition runtime.connect(optional string extensionId, optional object connection)
- OneSignal: Unable to open IndexdD8, UnknownError: The user denied permission to access the database.

Can you explain why?
Thanks.

**Comment by jasonpang** [comment]
Checking the first.

Can you let us know the browser environment for the second error? Browser name and version.
