### ISSUE TITLE
Notification clicks event not respecting notificationClickHandlerOrigin

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#185]
`fireStoredNotificationClicks` in `EventHelper` still checks for the exact document URL even if `notificationClickHandlerOrigin` is set to `origin`.

**Comment by hmrtk** [comment]
@jasonpang any update on this?

**Comment by jasonpang** [comment]
Hey @hmrtk,

Sorry, still haven't worked on this yet. I'll try to find some time over the next week or two.

**Comment by jasonpang** [comment]
Fixed by: https://github.com/OneSignal/OneSignal-Website-SDK/commit/28749a0b3fe02babab60910ad5a4f78d5c1e9f24
