### ISSUE TITLE
Disable Safari Platform

### ISSUE THREAD

**Issue by bmd-bentar** [OneSignal/OneSignal-Website-SDK#187]
Hi OneSignal,

Is that possible to disable (inactive) Safari platform in my apps account? How to do that?

Thanks

**Comment by jasonpang** [comment]
Hey @bmd-bentar,

There isn't a way to inactivate the Safari platform you set up; what you can do instead is remove the `safari_web_id` from your Safari config. This will prevent our SDK from initializing on Safari.

We'd prefer if you could ask non-website-SDK related questions to our support channel at onesignal.com (click the big red button at the bottom right). If you're pretty sure something is a bug with our web SDK though please feel free to post it here.
