### ISSUE TITLE
Is something wrong with OneSignal service?

### ISSUE THREAD

**Issue by bmd-bentar** [OneSignal/OneSignal-Website-SDK#189]
Hi OneSignal,

Yesterday on Dec 26th 2016, I sent push notification for all of my users and it was sent successfully to all platform subscribers (except on Firefox for Android). But today, Dec 27th 2016 it is only sent to my Chrome (windows) subscribers.

Is there something wrong?

**Comment by jasonpang** [comment]
Do you mind asking this question over at our support channel at onesignal.com (click the bright red button at the bottom right). This is just for organizational purposes as it keeps our issues separate from the web SDK. Our site support chat also provides tools to help us easier investigate the situation. Please link to this GitHub thread to provide context.

In the support thread, can you provide us with your login email?
