### ISSUE TITLE
SDK typed errors should not be thrown automatically

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#191]
[Conversation](https://app.intercom.com/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/web-push-team/conversations/7482409260)

It sounds like this error is being outputted to the console on unsupported browsers.

[Conversation](https://app.intercom.com/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/wordpress-team/conversations/7435150300)

The errors shouldn't be thrown if a user is just loading their page and our SDK is calling these methods internally.

**Comment by chankeypathak** [comment]
I'm getting above error after configuring OneSignal for Wordpress. Is this due to the older browser version or have I done anything wrong?

**Comment by jasonpang** [comment]
Hey @chankeypathak,

Just a setup error probably. If you haven't already, shoot us a message on our onesignal.com chat; we'll diagnose the issue and probably let you know what you need to change to fix it!

**Comment by jwilm** [comment]
Duplicate of #298
