### ISSUE TITLE
Closing a tab while the permission request is open dismisses the permission request

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#192]
At least in Chrome, closing a tab while a permission request is active dismisses the permission request. This causes our SDK to think the user actually clicked `X` and will store a cookie to not re-prompt the same permission request until hours later.

One Idea: Catch the window close event, and do not store cookie if prompt is dismissed.

**Comment by isaumya** [comment]
The same problem is there in Firefox too. Haven't tested in Safari as I don't have a Mac. I hope someone with a Mac may test it out.

**Comment by jasonpang** [comment]
This no longer occurs in Chrome or Firefox.
