### ISSUE TITLE
Subscription bell dialog button click listeners should be more specific

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#195]
[Conversation](https://app.intercom.com/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/jason@onesignal.com/conversations/6430482559)

Because the click event for the buttons are listened to at the highest level of the DOM (i.e. `window`):

```js
    window.addEventListener('click', (event) => {
      if (event.target === document.querySelector(this.subscribeButtonId))
        Event.trigger(Bell.EVENTS.SUBSCRIBE_CLICK);
      else if (event.target === document.querySelector(this.unsubscribeButtonId))
        Event.trigger(Bell.EVENTS.UNSUBSCRIBE_CLICK);
    });
```

the event can be prevented from bubbling up at any step along the way.

Instead, the click listener should be added on Dialog construction specifically on `document.querySelector(this.subscribeButtonId)`.

- [ ] **Notify user when fixed**
- [ ] **Notify user 2 when fixed** [Conversation](https://app.intercom.com/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/unassigned/conversations/8031914725)
- [ ] **Notify user 3 when fixed** [Conversation](https://app.intercom.com/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/web-push-team/conversations/8059544180)
- [ ] **Notify user 4 when fixed** [Conversation](https://app.intercom.com/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/web-push-team/conversations/8256911611)

**Comment by jasonpang** [comment]
Temporary workaround:

```js
document.querySelector('#onesignal-bell-container .onesignal-bell-launcher #subscribe-button').addEventListener('click', e => {
  OneSignal.event.trigger('notifyButtonSubscribeClick')
});
document.querySelector('#onesignal-bell-container .onesignal-bell-launcher #unsubscribe-button').addEventListener('click', e => {
  OneSignal.event.trigger('notifyButtonUnsubscribeClick')
});
```

**Comment by yurevichcv** [comment]
Why did you close this issue? Will it be fixed. Have the same problem on many website.

**Comment by jasonpang** [comment]
Hey @yurevichcv,

This will be fixed, just a little busy with some other tasks at the moment, sorry about that. Have you tried using this workaround on your site?

**Comment by yurevichcv** [comment]
Yes, workaround works well. Please, just make sure that after update(fix) it will not conflict with impletented workaround :)

**Comment by jasonpang** [comment]
Fixed by: https://github.com/OneSignal/OneSignal-Website-SDK/commit/f4632c6f95f3207f1608d8385e574de6a1710c45.
