### ISSUE TITLE
Fix Promise polyfill breaking Angular 2 sites using Zone.js

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#199]
http://stackoverflow.com/questions/41220741/onesignal-with-angular-2#comment69640366_41220741

[Conversation 1](https://app.intercom.com/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/jason@onesignal.com/conversations/7670898780)

[Conversation 2](https://app.intercom.com/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/jason@onesignal.com/conversations/7732480265)

**Comment by jasonpang** [comment]
Fixed by: https://github.com/OneSignal/OneSignal-Website-SDK/commit/d790181d7b8f50bf497e894b1a934a7471f85d29

Tested on BrowserStack IE 11 and Edge.

**Comment by nasr18** [comment]
hey @jasonpang how did u fix this? I wanna handle events in anuglar way. When i declare `OneSignal` inside `app.component.ts` its not working. and also no error in console.
