### ISSUE TITLE
Chrome Notification's "Tag" to GroupId then AppId

### ISSUE THREAD

**Issue by JaronrH** [OneSignal/OneSignal-Website-SDK#200]
I would like to see the showNotification's "Tag" config option default to the groupId first then appid.  That way, I can have a single app show multiple notifications and control those by my groupId.

Tag --> "An ID for a given notification that allows you to find, replace, or remove the notification using script if necessary."
http://docs.w3cub.com/dom/serviceworkerregistration/shownotification/

**Comment by jwilm** [comment]
duplicate of #50
