### ISSUE TITLE
Uncaught (in promise) DOMException: Entry was not found.

### ISSUE THREAD

**Issue by s7dhansh** [OneSignal/OneSignal-Website-SDK#204]
I get this error most of the times, when I include the service workers, OneSignalSDKWorker and SDKUpdaterWorker, in my code.

I am unable to figure out why. Any help would be great!

**Comment by jasonpang** [comment]
Hey @s7dhansh,

This probably isn't an SDK error, could you chat us on our live support on onesignal.com? Or you could email us at support@onesignal.com. Do you also have a link to to a live and publicly viewable site where you're experiencing this error?

**Comment by jasonpang** [comment]
Please feel free to email us at support@onesignal.com if you are still having issues.

If you're trying to add the SDK by source and running into import errors, we'd recommend using our CDN-hosted SDK instead and following the HTTPS web push setup guide on documentation.onesignal.com.
