### ISSUE TITLE
Improve being stuck in an unsubscribed state

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#206]
## HTTPS

**Problem**: A push subscription is marked as _Not Subscribed_ on our server, and is "stuck" in this state.

**Expected Solution:**
This problem should fix itself after the user opens their HTTPS site in a new tab or window, since we will automatically resubscribe for push and update our server's record after.

**Possible Explanations:**

1. Some users' `identifier` value is `nil`, along with a `nil` `p256dh` and `auth`. This isn't good, and we should:

    1.1. Add error reporting around this case so we know it's happening.

    1.2. Prevent any `null` or `undefined` values in `identifier`, `p256dh`, and `auth` from ever making it to the players `on_session` call or `create` call.

[Case 1](https://app.intercom.com/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/unassigned/conversations/8056167468)

**Other Actionable Items:**

1. Call `pushManager.getSubscription()` on new session. If it is `null`, which it will be if the user revoked or blocked their notification permission, we should:

    1.1 Make sure `isPushNotificationsEnabled()` returns false, since the user is now unsubscribed. This means modifying `isPushNotificationsEnabled()` to check for `pushManager.getSubscription()`.

    1.2 Resubscribe ASAP so we are restored a valid subscription.

2. On new session, check if notification permission is blocked; if so, update OneSignal registration with `notification_types` 0. This allows the dashboard to descriptively read `No (Permission Not Granted`.

**Comment by madshargreave** [comment]
Any ETA on this?

**Comment by jasonpang** [comment]
1.1 and 1.2 have been implemented for a long time, 2 is tracked internally.
