### ISSUE TITLE
"Unsubscribe" button does not work

### ISSUE THREAD

**Issue by and800** [OneSignal/OneSignal-Website-SDK#207]
On my https website, when the button "Unsubscribe" is pushed, nothing happens. Also the console remains clear, with `OneSignal`'s log level set to `trace` (but just before it clicking on the bell successfully calls `getSubscription()`, according to that log). Network graph is also clear. Everything else (subscribing, receiving notifications) is working properly.

**Comment by jasonpang** [comment]
Hi there,

We're not currently aware of such an issue. Can you provide a website URL, or reach out privately to support@onesignal.com if you don't want to provide this website URL publicly?

**Comment by jasonpang** [comment]
Duplicate of https://github.com/OneSignal/OneSignal-Website-SDK/issues/195
