### ISSUE TITLE
Checking existing http://site.com subscription in IFrame while in top frame http://x.site.com uses incorrect http://site.com environment instead of http://site.os.tc

### ISSUE THREAD

**Issue by joeljv91** [OneSignal/OneSignal-Website-SDK#208]
I'm triying to avoid double notifications for my clients. I have 2 apps in my OneSignal account with this names: "example.com" and "m.example.com". So what I'm trying to do is subscribe users in my subdomains without subscribing in my 2 apps. I'm doing this checking if my client it's subscribed on my first domain (example.com) before launch subscribe event on my mobile domain (m.example.com).

**m.example.com code:**

```
<script type="text/javascript" src="https://cdn.onesignal.com/sdks/OneSignalSDK.js"></script>
<script type="text/javascript">
    /* One signal */
    var OneSignal = window.OneSignal || [];
    OneSignal.push(["init", {
        appId:                 "[DEVMOBILEAPPID]",
        autoRegister:          false,
        subdomainName:         "https://devmobileexample.onesignal.com",
        httpPermissionRequest: {
            enable:          true
        },
        welcomeNotification:   {
            disable: true
        },
        notifyButton:          {
            enable: false
        }
    }]);

    // If mobile notifications isn't enabled
    OneSignal.isPushNotificationsEnabled(function(isEnabled) {
        if (!isEnabled) {
            var remoteDomain = 'http://www.example.com';
            var iframeHtml = '<iframe id="os_desktop_push" src="http://www.example.com/os.html" ></iframe>';
            $('body').append(iframeHtml);

            // Check if we are subscribed in desktop domain
            var iframe = document.getElementById('os_desktop_push');

            // Event to receive new messages
            window.addEventListener('message', function(e) {
                console.log('Origin: ' + e.origin + ' Data: ' + e.data);
                if (e.origin.indexOf('example.com') !== -1) {
                    if (e.data === false) {
                        OneSignal.push(function() {
                            OneSignal.showHttpPermissionRequest();
                        });
                    }
                }
            }, false);


            // When iframe is loaded send isSubscribed
            $(iframe).on('load', function() {
                iframe.contentWindow.postMessage('isSubscribed', remoteDomain);
            });
        }
    });
</script>
```

**example.com/os.html code:** 

```
<script type="text/javascript" src="https://cdn.onesignal.com/sdks/OneSignalSDK.js"></script>
<script type="text/javascript">
    /* One signal */
    var originDomain = "m.example.com";
    var OneSignal = window.OneSignal || [];
    OneSignal.push(["init", {
        appId:               "[DEVAPPID]",
        autoRegister:        false,
        subdomainName:       "https://devexample.onesignal.com",
        httpPermissionRequest: {
            enable:          true
        },
        notifyButton:        {
            enable: false
        },
    }]);

    window.addEventListener('message', function(e) {
        console.log('Origin: ' + e.origin + ' Data: ' + e.data);
        // Check origin domain
        if (e.origin.indexOf(originDomain) !== -1) {
            if (e.data == 'isSubscribed') {
                OneSignal.push(function() {
                    OneSignal.isPushNotificationsEnabled(function(isEnabled) {
                        e.source.postMessage(isEnabled, e.origin);
                    });
                })
            }
        }
    }, false);

</script>
```

When in my "m.example.com" remove OneSignal init and "isPushNotificationsEnalbed" no problem, postMessage works perfectly, but in other case Chrome launch this error "Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)."

**NOTE:** In firefox this works perfect

I'm going to continue investigating this.

**Comment by jasonpang** [comment]
@joeljv91 Thanks for providing all these details. I've been working on a small demo to recreate this issue at http://notify.tech/notify-tech-demos/shared-sites/main-domain.html and it looks like the SDK needs some changes to be able to check for subscription from iFrames.

For now, you can just check the notification permission on the iFrame. Most likely, if your users have allowed it, they are subscribed and you shouldn't re-prompt them.

**Comment by joeljv91** [comment]
@jasonpang For now I'll try with that.

**Comment by jasonpang** [comment]
[Another user affected by this issue](https://app.intercom.com/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/web-push-team/conversations/8237537730)

**Comment by joeljv91** [comment]
@jasonpang Any news?

**Comment by jasonpang** [comment]
Hey @joeljv91,

We put this issue on hold to develop some other features in the past few months, but we'll take a look at this soon. Sorry for the delay. Please feel free to check back in one week.

**Comment by joeljv91** [comment]
Hi @jasonpang,

Thanks for this info, no problem.

**Comment by jasonpang** [comment]
[This demo](http://notify.tech/notify-tech-demos/shared-sites/main-domain.html) shows three example subdomains that should be checking subscription state from HTTP (`?.os.tc`) but incorrectly checks from HTTPS (`?.notify.tech`) instead.

`SubscriptionHelper.ts` function `isUsingSubscriptionWorkaround()` determines whether the page loads in HTTP or HTTPS mode.

Normally, it returns `true` if a subdomain was set in dashboard config _or_ if the protocol is `http://`. But an extra condition is that `isUsingSubscriptionWorkaround()` only returns `true` if the current context is a top-level frame.

`true` means database / permissions is loaded from sub-frame `?.os.tc/webPushIFrame`. `false` means database / permissions uses the current frame's origin.

OneSignal's HTTP IFrame `?.os.tc/webPushIFrame` needs `isUsingSubscriptionWorkaround()` to return `false` to prevent endless child iframes to `?.os.tc/webPushIFrame` from being created recursively.

So we need "OneSignal" IFrames to return `false`, but we need "non-OneSignal" IFrames to return `true`.

Changing https://github.com/OneSignal/OneSignal-Website-SDK/blob/7e383e2d0b13211ae8266dbdf0daef47c978fc05/src/helpers/SubscriptionHelper.ts#L179 to:

```
return (
   (
     SdkEnvironment.getWindowEnv() === WindowEnvironmentKind.Host || 
     SdkEnvironment.getWindowEnv() === WindowEnvironmentKind.CustomIframe 
   ) && ...
);
```

correctly returns `true` for "non-OneSignal" IFrames that are HTTP or use a subdomain.

**Comment by zaidsallam** [comment]
i want to do any event when the user clicked on the notification pleeeeease help
