### ISSUE TITLE
notificationPermissionChange event fires twice on main page for HTTP subscriptions

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#218]
Caused By: https://github.com/OneSignal/OneSignal-Website-SDK/blob/ea851a49da41d82973a4970cbd8ccaf8bbaef15b/src/helpers/HttpHelper.ts#L402

The remote is already remotely re-triggered when fired originally from the iFrame (where the notification permission is actually changing).

**Comment by jasonpang** [comment]
Fixed by: https://github.com/OneSignal/OneSignal-Website-SDK/commit/9f3a2b126186f69765466748c5c3892695379a7d

**Comment by chinmaylbb** [comment]
Hi, in firefox, this event is getting fired twice when clicked on allowed only
