### ISSUE TITLE
Support using custom service worker filenames 

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#219]
`isPushNotificationsEnabled()` returns `false`, because the [check for whether the service worker is active](https://github.com/OneSignal/OneSignal-Website-SDK/blob/d790181d7b8f50bf497e894b1a934a7471f85d29/src/helpers/ServiceWorkerHelper.ts#L161) assumes a file name containing `"OneSignalSDKWorker"` or `"OneSignalSDKUpdaterWorker"`.

There are other places in the source code containing the hardcoded string `"OneSignalSDKWorker"` and `"OneSignalSDKUpdaterWorker"`. These should be moved off to use `OneSignal.SERVICE_WORKER_PATH` or `OneSignal.SERVICE_WORKER_UPDATER_PATH`. If these variables are not accessible in the service worker, they should be saved to IndexedDb and loaded from there.

Original Intercom Conversation: [Link](https://app.intercom.com/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/search/conversations/8474401681?q=https%3A%2F%2Fgithub.com%2FOneSignal%2FOneSignal-Website-SDK%2Fissues%2F212)

**Comment by tixastronauta** [comment]
Hi @jasonpang! Is this issue still open or have you guys managed to have `OneSignal.SERVICE_WORKER_PATH` everywhere?

**Comment by jasonpang** [comment]
This issue is still open; a refactored `ServiceWorkerManager` is in the works that doesn't use any hardcoded `"OneSignalSDK"` strings.

**Comment by jasonpang** [comment]
Refactored `ServiceWorkerManager` now accepts custom service worker file names.
