### ISSUE TITLE
Chrome push notifications not working with Linux

### ISSUE THREAD

**Issue by Jaryn-R** [OneSignal/OneSignal-Website-SDK#222]
Hello,
So I've been messing around with OneSignal for a couple of days, and I found a little problem.
I use an a Linux operating system known as Manjaro Budgie Community Edition 16.10. Everything works fine on Firefox, but not chrome. I've tested with a windows laptop that I had laying around and both Firefox, and Chrome work without any problems.

So at this point in time i'm not sure what else I could do, is this a problem with the SDK, or would this be a problem with the Linux version of Chrome?

I've tested with both Chrome and Chromium and both seem to have the same problem.

EDIT: This actually had something to do with cloudflare. It seems as if it was caching my user session, and denying the application to run.

**Comment by jasonpang** [comment]
Hey @Jaryn-R,

Did everything work out in the end? If so, would you mind closing this issue?

**Comment by jasonpang** [comment]
Please contact support@onesignal.com if you're still experiencing issues.
