### ISSUE TITLE
window.Notification.requestPermission is not a function

### ISSUE THREAD

**Issue by JosephP91** [OneSignal/OneSignal-Website-SDK#227]
Hi,
I am using onesignal in an https environment, but when I click on the red notification button the javascript console reports this error: 

"SubscriptionHelper.ts:379 Error while subscribing for push: TypeError: window.Notification.requestPermission is not a function"

How can I solve?

**Comment by jasonpang** [comment]
Hi @JosephP91,

Most likely, a third party script on your site is overriding window.Notification and not implementing requestPermission. What is your site URL?

**Comment by JosephP91** [comment]
hi @jasonpang 
That was the problem. Changing the class name inside of my script solves the issue. Thank you anyway!

**Comment by jasonpang** [comment]
Awesome, so glad you got it @JosephP91 !
