### ISSUE TITLE
Service Worker is not registered when Push Notifications aren't enabled

### ISSUE THREAD

**Issue by leonderijke** [OneSignal/OneSignal-Website-SDK#231]
I'm using the OneSignal Web Push SDK in conjunction with another Service Worker (for caching). In `OneSignalSDKWorker.js` and in `OneSignalSDKUpdaterWorker.js` I added the other Service Worker via `importScripts('/service-worker.js');`.

However, the Service Worker is only registered when the user has given permission for Push Notifications. When the user doesn't allow Push Notifications or the site didn't ask for permission yet, the Service Worker is not registered.

Is there a way to work around this?

**Comment by jasonpang** [comment]
Hey @leonderijke ,

In the future, we want to develop a better API for site developers to control the installation / updating of the service worker, but for now, you'll have to add some code to manually register the worker. 

Something like:

```
// If service workers are supported, and one isn't already registered
if ('serviceWorker' in navigator && !navigator.serviceWorker.controller) {
  navigator.serviceWorker.register('/OneSignalSDKWorker.js');
}
```

**Comment by leonderijke** [comment]
Thanks, @jasonpang! I registered the Service Worker manually to work around this.

**Comment by jasonpang** [comment]
Super @leonderijke !

**Comment by anshulix** [comment]
@jasonpang @leonderijke I've been working on a similar thing, my concern is for 'OneSignalUpdatedSDKWorker.js', I'm not registering it, so would there be any issue? As I can register only one here

`if ('serviceWorker' in navigator && !navigator.serviceWorker.controller) {
  navigator.serviceWorker.register('/OneSignalSDKWorker.js');
}`

In the success of registration I perform certain tasks which in case of other service worker registers, I'd lose. 

Thanks in Advance.

**Comment by jasonpang** [comment]
@anshulix,

It's okay if you're not registering the alternate updater worker. That'll be registered and then the original (non-updater) will be registered when an update is needed. Actually, can you please use the script:

```
var OneSignal = window.OneSignal || [];
if (OneSignal.installServiceWorker) {
  OneSignal.installServiceWorker();
} else {
  if (navigator.serviceWorker) {
    navigator.serviceWorker.register('/OneSignalSDKWorker.js?appId=YOUR-APP-ID');
  }
}
```

replace `YOUR-APP-ID` with your app ID.

**Comment by anshulix** [comment]
Thanks @jasonpang it works.

**Comment by anshulix** [comment]
@jasonpang Just one more query, an important one. How can I use the success callback which is after registration of service worker we have,

`.then(function (reg) {`

**Comment by jasonpang** [comment]
@anshulix,

Depends on what you're trying to do. If you just want to know whether the service worker was successfully attempted to be installed, I believe you can continue the Promise chain using the `.then(..)` syntax described above:

```
navigator.serviceWorker.register('/OneSignalSDKWorker.js?appId=YOUR-APP-ID')
      .then(function (registration) {
         /* The service worker has been attempted to be installed, there wasn't an error loading the service worker or parsing its script */
      });
```

If you're trying to communicate with your service worker through post message, I believe your service worker not only has to be installed, but it also has to be activated. You can read more about [the service worker lifecycle here](https://developers.google.com/web/fundamentals/instant-and-offline/service-worker/lifecycle). To check for activation, add:

```
          navigator.serviceWorker.addEventListener('controllerchange', e => {
            // Check that the navigator.serviceWorker.controller.scriptURL is your intended worker
          });
```

Check out the service worker docs / Google guide. There a couple of things to be aware of like:

a) Does your service worker immediately take over active workers, or wait until all tabs are closed to take over? If you're bundling your worker with our worker, then our merged code will cause all pages to be immediately controlled by your+our (merged) worker.

     This means you can immediately check for the events above after installation, without waiting for the page to refresh or for other tabs to close.

b) What you're trying to do: post message communication (your SW must be activated), install a cache (I think your SW only needs to be installed), intercept network events (your SW must be activated).

**Comment by anshulix** [comment]
@jasonpang Thank you, it was really helpful. My service worker requires PostMessage and also force install, which looks good with OneSignal. Let me work it out.

I'm trying to implement this in WordPress OneSignal plugin integration, there I can see the service worker is not at the root which will cause my cache and other features of SW to be not working. I'm trying to edit and place those files in the root, would that affect the plugin?

I'm not sure if I'm raising this query at the right place, but your help is highly appreciated.

Thanks

**Comment by jasonpang** [comment]
@anshulix,

If you're using our WordPress plugin integration, use the following registration code instead:

```
navigator.serviceWorker.register('/wp-content/plugins/onesignal-free-web-push-notifications/sdk_files/OneSignalSDKWorker.js.php?appId=YOUR-APP-ID')
      .then(function (registration) {
         /* ... */
      });
```

Even if a service worker file isn't located at the root, it can be used as if it were located at the root as long as the file is served with a special HTTP header `Service-Worker-Allowed: /`, which allows the scope of the service worker to be set to the root directory again. The `OneSignalSDKWorker.js.php` file in our plugin sets this header using PHP code so that it can be used inside of a subdirectory. No need to move those files!

**Comment by anshulix** [comment]
@jasonpang Thanks for this awesome info.

> Even if a service worker file isn't located at the root, it can be used as if it were located at the root as long as the file is served with a special HTTP header Service-Worker-Allowed: /, which allows the scope of the service worker to be set to the root directory again.

All fixed now! I actually did it by registering my own work and then it gets replaced by OneSignal one, but I guess with this path it works, now workaround required

**Comment by jasonpang** [comment]
Great to hear!

**Comment by mcrisostomo** [comment]
> @anshulix,
> 
> It's okay if you're not registering the alternate updater worker. That'll be registered and then the original (non-updater) will be registered when an update is needed. Actually, can you please use the script:
> 
> ```
> var OneSignal = window.OneSignal || [];
> if (OneSignal.installServiceWorker) {
>   OneSignal.installServiceWorker();
> } else {
>   if (navigator.serviceWorker) {
>     navigator.serviceWorker.register('/OneSignalSDKWorker.js?appId=YOUR-APP-ID');
>   }
> }
> ```
> 
> replace `YOUR-APP-ID` with your app ID.

This answer helped me a lot.

Thank you.
