### ISSUE TITLE
Web Push Safari browser image problem

### ISSUE THREAD

**Issue by yakraba** [OneSignal/OneSignal-Website-SDK#234]
Hi,
I'm trying to send browser notifications via Rest api .net (c#). 
When i sending notification everything is ok(chrome,opera ,...), but on safari browser notification image coming default onesignal icon. I don't want to see this, and i want to send for each notification different image.  
My c# code is :
     request.Headers.Add("authorization", "Basic " + ApiKey);
            byte[] byteArray = Encoding.UTF8.GetBytes("{"
                                                    + "\"app_id\": \"" + App_guid + "\","
                                                     + "\"url\": \"" + url + "\","
                                                   + "\"headings\": {\"en\": \"" + title + "\"},"
                                                    + "\"contents\": {\"en\": \"" + spot + "\"},"
                                                    + "\"chrome_web_icon\": \"" + imageUrl + "\","
                                                    + "\"included_segments\": [\"All\"]}");

And my js code is :

 <script type="text/javascript">
        var OneSignal = window.OneSignal || [];
        OneSignal.push(["init", {
            appId: "app id ",
            autoRegister: true,
            notifyButton: {
                enable: false
            },
            safari_web_id: 'safari web id ',
            persistNotification: false
        }]);
    </script>
Is there a custom command that needs to be set for the Safari browser?

**Comment by jasonpang** [comment]
@yakraba Please make sure you're setting a Safari icon in your onesignal.com dashboard App Settings.

**Comment by yakraba** [comment]
Yes i did before @jasonpang

**Comment by jasonpang** [comment]
@yakraba In that case, please remove your permission and resubscribe. Unfortunately, Safari won't show new images if you upload a new image to your app settings; you have to resubscribe to see it. See https://documentation.onesignal.com/docs/troubleshooting-web-push#section-my-safari-notification-icons-aren-t-showing-up for more details.

**Comment by jwilm** [comment]
Closed due to inactivity
