### ISSUE TITLE
After blocking and re-allowing permissions on the same page load, user can't resubscribe

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#239]
1. Clear all data and reset state.
2. Open site (this specific site had `autoRegister: false)`, click notify button but click _Block_.
3. Manually set permissions to always allow.
4. Click the notify button. Observe that nothing happens, when the user should actually be prompted.

**Comment by madshargreave** [comment]
Any solution to this problem?

**Comment by Findiglay** [comment]
Have found the same issue. Hopefully most users will not block and then attempt to re-allow permissions.

**Comment by jasonpang** [comment]
This issue no longer occurs.

I'm not sure what fixed this issue, but this would be a nice test case to add when refactoring prompt logic.
