### ISSUE TITLE
"TypeError: o is undefined" in Firefox 54.0.1 (64-Bit, MacOS)

### ISSUE THREAD

**Issue by jopnas** [OneSignal/OneSignal-Website-SDK#242]
Firefox 54.0.1 (64-Bit, MacOS) sends 'TypeError: o is undefined   OneSignalSDK.js:1:124816' message followed by a warning "OneSignal: Loading the required iFrame https://xxxxxx.onesignal.com/webPushIframe timed out. Check that the Site URL onesignal.com dashboard web config is http://xxxxxx.xxxxx.de. Only the Site URL specified there is allowed to use load the iFrame.  OneSignalSDK.js:1:205952" in console but works fine in Chrome browser. I'am using "https://cdn.onesignal.com/sdks/OneSignalSDK.js".

**Comment by jasonpang** [comment]
Hi @jopnas,

Can you contact us on support@onesignal.com with your site URL so that we can reproduce this issue?

**Comment by jasonpang** [comment]
Closing stale issue; please contact us at support@onesignal.com if you're still having issues.
