### ISSUE TITLE
No user with this id found when using "Edit device" server rest API

### ISSUE THREAD

**Issue by fx-leb** [OneSignal/OneSignal-Website-SDK#243]
Hello,

I'm trying to use this edit-device endpoint to update a device tags.

I always get the same answer :

> No user with this id found

Below, the request I use :
`curl --include \ --request PUT \ --header 'Content-Type: application/json' \ --data-binary '{"app_id" : "my app id", "tags":{"a":"1","foo":"2"}}' \ https://onesignal.com/api/v1/players/:45754208-6ff9-4613-80c2-193a19aa1536`

The user exists. I checked it with
`https://onesignal.com/api/v1/players/45754208-6ff9-4613-80c2-193a19aa1536?app_id=my app id`

I'm certainly missing something...

Thanks,

**Comment by jasonpang** [comment]
Hey @fx-leb,

Try removing the semicolon before the user ID.

**Comment by fx-leb** [comment]
my bad  :flushed:
