### ISSUE TITLE
Not able to register the service worker

### ISSUE THREAD

**Issue by SethuSenthil** [OneSignal/OneSignal-Website-SDK#244]
I published a simple blank website (on GitHub) to test this out. But when ever I check for subscribers, there are none so while checking the console it shows me: 

"ServiceWorkerHelper.ts:127 ServiceWorker registration TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
e.registerError @ ServiceWorkerHelper.ts:127"

**Comment by SethuSenthil** [comment]
FIX: Onesiginal only works on the root most part of the domain, in GitHub pages, it means publishing it on your username domain (username.github.io) not (username.github.io/some-project-repo.html)

**Comment by jasonpang** [comment]
Hey @SethuSenthil,

Sorry I wasn't able to get back to you in time, and glad you figured it out. Publishing it on your username domain is one way. We also have some configuration options for allowing OneSignal to work on pages in a sub-directory. Please see [this documentation link](https://documentation.onesignal.com/docs/web-push-sdk-setup-https#section-can-manifest-json-onesignalsdkworker-js-and-onesignalsdkupdaterworker-js-be-served-from-a-subfolder-of-my-site-) or reach out to us at support@onesignal.com if you'd like to learn more.

You can set:

```
OneSignal.SERVICE_WORKER_PARAM = { scope: '/your-subfolder' };
```

_before_ OneSignal is initialized and also set the `path` initialization option.

**Comment by SethuSenthil** [comment]
@jasonpang Wow! Thanks! Never saw this configuration of the SDK before, this will make my life a whole lot easier!
