### ISSUE TITLE
ServiceWorker registration DOMException

### ISSUE THREAD

**Issue by Pulkit-Sharma** [OneSignal/OneSignal-Website-SDK#246]
I installed on a website as mentioned in documentation. However I am getting the following error in inspect.

ServiceWorker registration DOMException: Failed to register a ServiceWorker: The script resource is behind a redirect, which is disallowed.
e.registerError @ ServiceWorkerHelper.ts:127

**Comment by jasonpang** [comment]
Hi @Pulkit-Sharma,

Wherever your service worker file is served from, the response your server gives can't be a redirect to another resource.

For example, if your file is available at https://your-site.com/OneSignalSDKWorker.js, then:

`curl -I https://your-site.com/OneSignalSDKWorker.js`

should return:

```
HTTP/1.1 200 OK
Content-Type: application/javascript
...
```

The error is saying that the response is something like:

```
HTTP/1.1 301 Moved Permanently
Location: <some-other-location>
```

This can also happen if you haven't uploaded the service worker to the root directory of your site, and requesting a non-existent file redirects to a 404 page.

**Comment by jasonpang** [comment]
Please reach out to support@onesignal.com if you're still receiving messages about an invalid redirect for your service worker.
