### ISSUE TITLE
CSP Issue with your SDK

### ISSUE THREAD

**Issue by ayumihamsaki** [OneSignal/OneSignal-Website-SDK#248]
Hello,

I am trying to setup Slidedown Permission Message with your OneSignal. But I notice your coding is not good with CSP Content Security Policy. The following code gives the error:

`<div class="popover-body-icon " style="background-image: url('https://www.example.com/images/192x192.png');"></div>`

I don't understand the need to in-line CSS Styles?

A solution and cleaner code would be this:

```
<div class="popover-body-icon "><img src="https://www.example.com/images/192x192.png" alt="OneSignal" ></div>


Editing your SDK JS File: (Found at: https://cdn.onesignal.com/sdks/OneSignalSDK.js)

This line of Code to be changed:

<div class="popover-body-icon '+("default-icon"===n?"default-icon":"")+'" style="background-image: url(\''+("default-icon"===n?u:n)+'\');"></div>

Also Changing your CSS File (Found at: https://cdn.onesignal.com/sdks/OneSignalSDKStyles.css)

OLD:

#onesignal-popover-container #onesignal-popover-dialog .popover-body-icon {
    box-sizing: border-box;
    float: left;
    width: 80px;
    height: 80px;
    background-size: contain;
    background-position: 0 0;
    background-repeat: no-repeat;
}

NEW (ADDED img):

#onesignal-popover-container #onesignal-popover-dialog .popover-body-icon img {
    box-sizing: border-box;
    float: left;
    width: 80px;
    height: 80px;
    background-size: contain;
    background-position: 0 0;
    background-repeat: no-repeat;
}
```

I look forward to your replies and hope the OneSignal team is willing to make their SDK work with CSP Content Security Policy.

**Comment by ayumihamsaki** [comment]
Gonna cc @jasonpang into this as its been 3 days and still no reply.

**Comment by jasonpang** [comment]
Hey @ayumihamsaki,

Sorry for the delay, we'll definitely be looking into this soon.

**Comment by jasonpang** [comment]
Hi @ayumihamsaki,

We fixed this in https://github.com/OneSignal/OneSignal-Website-SDK/commit/7ff81472e250d1cc96cc612e28541bbb5492da55, and this should go out early next week.

**Comment by ayumihamsaki** [comment]
Thank you
