### ISSUE TITLE
OneSignal Push: There was a 0 error sending your notification:

### ISSUE THREAD

**Issue by vishaldodiya** [OneSignal/OneSignal-Website-SDK#249]
![screenshot from 2017-08-11 18-06-14](https://user-images.githubusercontent.com/10206090/29350190-10e6d056-827b-11e7-84c2-1fd93979ab2b.png)

I am getting this error on my WordPress dash board whenever I want to send push notification after updating or publishing one post.

**Comment by jasonpang** [comment]
Hi @vishaldodiya,

In our experience, a 0 error means that the outgoing network connection was blocked. Can you check with your server host to see if outgoing connections are blocked?

Please reach out to support@onesignal.com if you're still stuck on figuring this error out.
