### ISSUE TITLE
No popup for notification Wordpress

### ISSUE THREAD

**Issue by rebootcode** [OneSignal/OneSignal-Website-SDK#250]
I just installed onesignal push notification and found, it does not popup automatically.

The bell remains idle on bottom left. Isn't it suppose to popup asking to allow or block ?

I am using onesignal wordpress plugin.

**Comment by jasonpang** [comment]
Hi @rebootcode,

Not by default for the WordPress plugin. In general, auto-prompting as a default isn't the best experience for users. If you'd like to turn on auto-prompting, please enable "Automatically prompt new site visitors to subscribe to push notifications" on our WordPress plugin's configuration page (in your WordPress admin backend).
