### ISSUE TITLE
getUserId returns an object

### ISSUE THREAD

**Issue by HZ-labs** [OneSignal/OneSignal-Website-SDK#253]
Sometimes getUserId returns an object like this - 
```
{
    uuid: ...
}
```
not a string

**Comment by jasonpang** [comment]
@HZ-labs,

Are you able to reproduce the issue when `getUserId()` returns an object instead of a string? When does it occur?

**Comment by jasonpang** [comment]
@HZ-labs reported the callback version of `getUserId()` was incorrectly returning an object instead of a string. Fixed by https://github.com/OneSignal/OneSignal-Website-SDK/commit/ec75854c499135fbab6f642d5814a756a3fb544d.

Thanks for the report!
