### ISSUE TITLE
OneSignal.isServiceWorkerActive() does not exists anymore

### ISSUE THREAD

**Issue by fabio-rigato** [OneSignal/OneSignal-Website-SDK#254]
Hello @jasonpang,
I noticed that from OneSignal SDK build version 140005, the `isServiceWorkerActive()` function does not exists anymore, causing error on OneSignal initialisation as you can see in my attached screenshot.
![screen shot 2017-08-22 at 17 02 06](https://user-images.githubusercontent.com/9264663/29572273-2366f20c-875c-11e7-9003-970c968b16e9.png)

This brakes the init logic as described in your documentation/examples as you can see [here](https://documentation.onesignal.com/v3.0/docs/troubleshooting-web-push#section-3-check-if-you-are-subscribed)

is that a known issue, how can I test if the service worker is active? 

Thank you!

---
Fabio Rigato

**Comment by jasonpang** [comment]
Hey Fabio,

Can you use `navigator.serviceWorker && navigator.serviceWorker.controller && navigator.serviceWorker.controller.scriptURL.indexOf('OneSignalSDKWorker.js') !== -1`? The `isServiceWorkerActive()` wasn't a publicly documented API method; sorry for the confusion.

**Comment by simonemazzoni** [comment]
@jasonpang I had the same problem. 
Maybe is better to change the documentation at the link provided by fabio-rigato?

Looking at the source code I also noticed that `OneSignal.isPushNotificationsSupported()` already checks if the service worker is active. Am I right?

**Comment by fabio-rigato** [comment]
Hello @jasonpang,
thank you so for your fast answer.
I noticed that `OneSignal.closeNotifications()` does not works anymore too.
How can i close a particular notification?
Witch function can I use to close a notification instead of `OneSignal.closeNotifications()`?

Thank You

**Comment by jasonpang** [comment]
Hey there,

Sorry for the inconvenience, these functions weren't publicly documented (on our SDK API page) so they're liable to be removed at any time.

To reproduce `closeNotifications()`, you can use Notification.close() and ServiceWorkerRegistration.getNotifications(). Here's an example:

```
if (navigator.serviceWorker) {
  const registration = await navigator.serviceWorker.getRegistration();
  const notifications = registration.getNotifications();
  for (const notification of notifications) {
    notification.close();
  } 
}
```
