### ISSUE TITLE
persistNotification of undefined

### ISSUE THREAD

**Issue by rmdevelopers** [OneSignal/OneSignal-Website-SDK#255]
Uncaught (in promise) TypeError: Cannot read property 'persistNotification' of undefined.

Uncaught (in promise) TypeError: Cannot read property 'persistNotification' of undefined
    at Function.e.saveInitOptions (InitHelper.ts:159)
    at t.<anonymous> (ProxyFrame.ts:98)
    at i (tslib.es6.js:91)
    at Object.next (tslib.es6.js:72)
    at s (tslib.es6.js:62)
    at <anonymous>

**Comment by jasonpang** [comment]
Hey @rmdevelopers,

Is there a webpage I can visit to reproduce the same error?

**Comment by rmdevelopers** [comment]
I was trying to run on Angular 4 and I did not find any NPM install for this. So I decided to do it in a bad way, but it worked that is putting the <script> </ script> in the index.html of the project.
