### ISSUE TITLE
Is there any functionality to send big image in firefox like i can send in chrome with chrome_web_image?

### ISSUE THREAD

**Issue by ravisojitra** [OneSignal/OneSignal-Website-SDK#259]
I need to send big picture in notification. It's working fine in google chrome with chrome_web_image but not anything for firefox.
I tried using firefox_icon but it appears too small compared to chrome web image.
Is there any functionality available for firefox?

**Comment by jasonpang** [comment]
Hi @ravisojitra,

Firefox doesn't support large images, only the small notification icon.
