### ISSUE TITLE
There seems to be a Major Bug in your SDK setup

### ISSUE THREAD

**Issue by ayumihamsaki** [OneSignal/OneSignal-Website-SDK#260]
Hello,

There seems to be a huge bug in your SDK that needs fixing asap!

When you select the option: **Slidedown Permission Message** which I got.

I have updated these two files:

```
OneSignalSDKUpdaterWorker.js
OneSignalSDKWorker.js
```

With the following code:

```
importScripts('sw.js');
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDK.js');
```

Now the user has three options:

1. Does not click on the Slidedown banner.
2. Clicks on No option on the Slidedown banner.
3. Clicks on Yes option on the slidedown banner.

The Major bug is that when the user clicks on options 1 and 2 both service workers are not loaded at all.

You need to make sure that the service worker file sw.js loads on all three options.

You need to make your SDK API service worker only load on option 3.

This is a mahor problem because your SDK is stopping my service worker from working normally and loading in 2 out of 3 cases!!!

@jasonpang

**Comment by jasonpang** [comment]
Hi @ayumihamsaki,

If your website is a Progressive Web App that needs to register a service worker as early as possible, please register your service worker the following way:

(be sure to replace YOUR-APP-ID with your app ID)

```
var OneSignal = window.OneSignal || [];
if (OneSignal.installServiceWorker) {
  OneSignal.installServiceWorker();
} else {
  if (navigator.serviceWorker) {
    navigator.serviceWorker.register('/OneSignalSDKWorker.js?appId=YOUR-APP-ID');
  }
}
```

**Comment by ayumihamsaki** [comment]
@jasonpang  Perfect! That's working great now, thank you very much. 🥇
