### ISSUE TITLE
Catching exceptions in registerForPushNotifications

### ISSUE THREAD

**Issue by tamirvs** [OneSignal/OneSignal-Website-SDK#262]
I can't seem to be able to catch `registerForPushNotifications` exceptions. Since they are thrown in promises, `try-catch` won't catch them, and `registerForPushNotifications` doesn't return a promise to be able to `catch()` on.  
How can I tell if `registerForPushNotifications` has failed?

**Comment by tamirvs** [comment]
Thanks @jasonpang. So there is no way informing the user an error has occurred during a subscription?

**Comment by jasonpang** [comment]
@tamirvs,

Sorry, there is no way to inform the user an error occurred. If you're trying to find out if the user blocked notification permissions before subscribing them, you can check `OneSignal.getNotificationPermission()` to see if the promise returned resolves to `blocked`. Other than this, a lot of the issues aren't something the user can do (e.g. the user is using iOS and is trying to subscribe to web push, which doesn't support iOS, or the site setup has an issue preventing web push from working).

**Comment by tamirvs** [comment]
Yeah, I just wanted to give the user a heads up that this operation has failed, because I've recently ran into a weird bug that gave me _UnsupportedEnvironment_ errors (for an already subscribed browser) until I reopened the browser. I'll open a new issue if I'll be able to reproduce it.  
Thanks for your help!
