### ISSUE TITLE
Push notifications not supported on nw.js

### ISSUE THREAD

**Issue by Romischart** [OneSignal/OneSignal-Website-SDK#263]
Hey i wanted to ask if nw.js based on Chromium is supported?

Cause i have following problem:

- in my nw.js app i directly request a webapp (used https)
- the webapp request the client for web push notifications, wich i manuelly allow 
   - in the def console i can see that the WebWorker of OneSignalSDK is installed and after i allow it is running.
   - **The Problem is, after i accept web push i get the response that Registration failed** `DOMException: Registration failed - push service not available`

i use nw.js in version 0.25.0 and i get following if i print out the user-agent:
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.79 Safari/537.36`

thank in advance!

**Comment by Romischart** [comment]
Its already a week  passed.
So I can assume that it is not supported?

**Comment by jasonpang** [comment]
Hey @Romischart,

Sorry I missed this. I haven't used nw.js and I'm not sure what the answer is. I found an interesting comment on the thread about push notification support for Electron (https://github.com/electron/electron/issues/6697#issuecomment-313526691). There, someone says they got the Push API working with NW.js. 

Have you made sure to start NW.js with the `--enable-gcm` flag? (http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/#-enable-gcm)

**Comment by Romischart** [comment]
@jasonpang,

thank you so much! Yes, i already enabled it, but had a syntax error in the arguments section, where the flags are placed in. 
Now it is working correctly.

**Comment by jasonpang** [comment]
@Romischart,

Great! Are you able to receive a standard push notification, like you do in a regular browser?

**Comment by Romischart** [comment]
Yes, in nw.js it depends on version u need to set the argument flag for native web push notification `--enable-features=NativeNotifications` this flag only supported nw.js versions 0.21 and newer. Older versions has the `--enable-native-notifications` flag. This flag enables native web push notification for the browser by default, without manually activate them over the popup wich comes in browser like chrome, safari or firefox. But to get onesignal working the second flag is needed wich you said `--enable-gcm`.

**Comment by jasonpang** [comment]
Awesome, thanks for the information!

**Comment by zkrige** [comment]
I had to use both of these to make nwjs work with FCM notifications ` --enable-features=NativeNotifications --enable-gcm`
