### ISSUE TITLE
How to get IP Address of registered device via getDevices REST Api ?

### ISSUE THREAD

**Issue by ravisojitra** [OneSignal/OneSignal-Website-SDK#264]
I need to get the IP address of registered device via getDevices REST Api.
I can see IP address of registered devices in all users tab in onesignal dashboard.
But i couldn't receive IP address of registered device via REST Api.
Can you tell me how to get IP address?

**Comment by jwilm** [comment]
Hi there, this is currently unsupported, and we don't currently have plans to support it via the API. I've filed a feature request for this internally.
