### ISSUE TITLE
Notifications don't work on Firefox ESR 52.3.0 (64-bit)

### ISSUE THREAD

**Issue by farmnest** [OneSignal/OneSignal-Website-SDK#267]
Notifications and bell display stopped. No message pop up shows up that the site wants to show notifications. 

The same configuration work fine on google chrome/chromium. 

Firefox ESR 52.3.0 (64-bit)
OS: Opensuse Leap 42.3 (tested on several others with same results)
Will send site link on demand

**Comment by jasonpang** [comment]
Hey @farmnest,

[Firefox ESR doesn't support push notifications](https://developer.mozilla.org/en-US/docs/Web/API/Push_API#Browser_compatibility) unfortunately.

**Comment by nikunjbhatt** [comment]
If the `navigator.serviceWorker` is `undefined` on Firefox ESR (or in any browser) then the "Subscribe to Push Notifications" button should not be rendered in the `<div class='onesignal-customlink-container'></div>`.
