### ISSUE TITLE
Broken Image in notification permission popover.

### ISSUE THREAD

**Issue by 5achinJani** [OneSignal/OneSignal-Website-SDK#268]
Problem: OneSignal isn't able to fetch the image to display in the permission popover.
![onesignalbug1](https://user-images.githubusercontent.com/23077544/30683901-c53127ba-9ecc-11e7-9122-14473630a94b.png)

Problem details:
![onesignalbug2](https://user-images.githubusercontent.com/23077544/30684132-abd596b0-9ecd-11e7-83a1-31ce60a3be61.png)

![onesignalbug3](https://user-images.githubusercontent.com/23077544/30684156-bdc76920-9ecd-11e7-8b64-b01c3b99eb6c.png)

![onesignalbug4](https://user-images.githubusercontent.com/23077544/30684168-c8a3befc-9ecd-11e7-8552-5bd5088ef9e6.png)

Things verified :
-> OneSignal configuration :heavy_check_mark: 
-> OneSignal configuration(Default Notification Icon URL)  url is publicly accessible  :heavy_check_mark:
-> OneSignal manifest.json (all images paths are okay and working)  :heavy_check_mark: 
-> OneSignal Web push notification shows the icon image   :heavy_check_mark:

**Comment by 5achinJani** [comment]
I debugged and found the root cause. The issue is with the [bowser](https://github.com/OneSignal/bowser) package. It doesn't detect `chromium` browser as `chrome` and your function 
```javascript 
getPlatformNotificationIcon
```
returns `undefined` .

**Comment by jasonpang** [comment]
@5achinJani Thanks for debugging the issue, patched by https://github.com/OneSignal/OneSignal-Website-SDK/commit/c5c8ee3541add2d39ad857f5d66cea08286e0e01.
