### ISSUE TITLE
OneSignal.com website is broken

### ISSUE THREAD

**Issue by kevinfoley** [OneSignal/OneSignal-Website-SDK#269]
I apologize for using this means to report these issues, but there doesn't seem to be any other way to do so.

1. The Contact link at the bottom of [your website ](https://onesignal.com/about)does not work
2. The [documentation site ](https://documentation.onesignal.com)does not explain how to contact support
3. The dashboard does not render correctly in Edge
![onesignal broken edge](https://user-images.githubusercontent.com/7231744/30711657-4a1adf7a-9ebe-11e7-8f61-d42073b8de0a.png)

**Comment by gdeglin** [comment]
Thanks for letting us know! The contact link should now be working. We think Intercom.com (our support system vendor) was having issues which caused the first two problems you reported.

The dashboard is not currently compatible with Edge, but this will be soon resolved when Edge is updated to fully support for CSS grid later this year. https://developer.microsoft.com/en-us/microsoft-edge/platform/status/gridupdate/?q=grid%20update.
