### ISSUE TITLE
UnsupportedEnvironment on all web browsers

### ISSUE THREAD

**Issue by anujgeek** [OneSignal/OneSignal-Website-SDK#270]
Hello, we've been experiencing issues for web push since a couple of days. I tested this on chrome and firefox on a few different machines and whenever we try to subscrive or send a push, we were seeing a "UnsupportedEnvironment" error. I tried on https://onesignal.com/webpush too and it gave the same error, so I'm thinking this is broken from onesignal side.

![image](https://user-images.githubusercontent.com/16366917/30718248-302fd424-9ed4-11e7-85e2-0d873f78b475.png)

**Comment by jasonpang** [comment]
Are you refreshing the page bypassing the cache by using the `Ctrl + Shift + R` keyboard shortcut? If so, this disables service workers and our SDK detects this and returns the UnsupportedEnvironment error.

If you're able to reproduce this error again, could you please expand both arrows you see on the error to get the stack trace?

**Comment by anujgeek** [comment]
Thanks @jasonpang, hard refresh was the reason behind that error. But there is another error that we're experiencing on our websites only:
![image](https://user-images.githubusercontent.com/16366917/30881524-ffd7fdb6-a2ba-11e7-80b0-1b333b16e107.png)
Any idea why this could be happening?

**Comment by jasonpang** [comment]
Hi @anujgeek,

Both this JavaScript file, and the similarly named OneSignalSDKUpdaterWorker.js, must be served from CloudFront with a `Content-Type` of `application/javascript`, and not `text/plain`. The browser requires this content type when registering the JavaScript file as a background service worker.

I came across this line in [CloudFront's documentation](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AddingObjects.html) that says:

> CloudFront servers don't determine the MIME type for the objects they serve. When you upload an object to your origin, you should set the Content-Type header field for the object.

Can you check that the Content-Type for those two files is set to `application/javascript`? Also make sure the content type of `manifest.json` is set to `application/json`.

**Comment by anujgeek** [comment]
Hi @jasonpang ,
Thanks, I changed the ContentType for those three files and and it fixed the issue for us. Now even though push notifications are working, I still see the console errors:

![image](https://user-images.githubusercontent.com/16366917/30882386-97b0a226-a2bd-11e7-903b-5bcdd213eddb.png)

Will these console errors cause any issues?

**Comment by anujgeek** [comment]
Sorry I was
