### ISSUE TITLE
Push notification problem on iOS 11 w/ Ionic 3?

### ISSUE THREAD

**Issue by petrot** [OneSignal/OneSignal-Website-SDK#271]
I can't get push notifications in my Ionic 3 app built with XCode 9 & iOS11. Same code on android works well. Has anyone the same problem?

UPDATE: 
Neither the old working version can't get the notifications under iOS11 :/

**Comment by petrot** [comment]
Solved by new build.. (I don't know what was the problem, same code had been rebuilt..)

**Comment by mathewk2017** [comment]
which version of the plugin are you using?
