### ISSUE TITLE
How do I locally install onesignal-website-sdk (Angular CLI/webpack/npm)

### ISSUE THREAD

**Issue by mautematico** [OneSignal/OneSignal-Website-SDK#276]
I understand it is discouraged because of possibility to lose updates propagated through the CDN.
Nevertheless, I still prefer to install it locally and package it through webpack/npm.

What are the general steps to follow?
Would it be enough to building locally the git repo and importing resulting .js?

**Comment by jasonpang** [comment]
Building locally, rough instructions until we have a better README one day:

1. Clone the repo.
2. Copy config.json.example and rename as config.json.
3. In config.json, modify the "railsProjectRoot" property to a directory that exists. Can be just an empty directory.
4. Run "./sdk build". You can also explore some of the options with "./sdk".
5. You should see in your directory some generated files.
6. Run "./sdk build --env=production" for the real production SDK we push out. This is the OneSignalSDK.js we serve. You'll also get a styles file we load dynamically when needed.
7. tsconfig.json, set compilerOptions -> lib -> es5 to "es7" and compilerOptions -> target -> es5 to "esnext" for the best debugging on Chrome.

Keep in mind the SDK will import itself for the background service worker, and will import the styles hosted on our CDN if you use our notify button or slidedown prompt, so it isn't possible to completely get rid of the CDN usages.

**Comment by jwilm** [comment]
Please let us know if you've got any further questions about this!

**Comment by tixastronauta** [comment]
@jasonpang could you please provide updated information on how to build this project locally? thank you!

**Comment by jasonpang** [comment]
@tixastronauta `yarn` install dependencies and then `yarn build:prod`. The last command in the sequence of commands will fail, but it should still build to `build/bundles`. You can view the script in `package.json` for more info.
