### ISSUE TITLE
Display variance web push

### ISSUE THREAD

**Issue by scotshurdler** [OneSignal/OneSignal-Website-SDK#277]
Hi folks, 

One of my colleagues is having issues with push notifications as per the attached screenshot whereby they don't display correctly.  I'd looked through the documentation/faqs, his chrome version is up to date.  Everyone else in the office is displaying correctly.  I'm curious if I've done something wrong at set up or whether it's a compatibility issue.

Any tips much appreciated

Cheers
N
![1](https://user-images.githubusercontent.com/33225397/32173901-4535a87c-bd78-11e7-95d9-edbc964bf083.jpg)

**Comment by jwilm** [comment]
This looks like it's working as intended. You've provided both an image and the icon for this push notification. If you have any further questions, please reach out via our support widget on onesignal.com.
