### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by junivillegas** [OneSignal/OneSignal-Website-SDK#278]
![image](https://user-images.githubusercontent.com/3825784/32386776-f30a644e-c087-11e7-874f-e0716e7a6d32.png)

**Comment by natterstefan** [comment]
@junivillegas I have two questions

- which command did you run in the console to get this error?
- Can you please change the title and make it more specific?

Thank you.

**Comment by jwilm** [comment]
Duplicate of #298
