### ISSUE TITLE
Failed to register serviceworker

### ISSUE THREAD

**Issue by VeeK727** [OneSignal/OneSignal-Website-SDK#280]
A similar issue has been discussed before but I'm having a slightly different problem. I'm trying to use Onesignal on a subdomain. The manifest and other files are located at https://mydomain.com (Fully HTTPS) and my notification request takes place on http://crm.mydomain.com.

I use the following code:

```
var OneSignal = window.OneSignal || [];
OneSignal.push(["init", {
	appId: "5ad01a3c-5bbe-4ec9-ad41-7a08b4e79af2",
	autoRegister: false,
	notifyButton: {
		enable: false /* Set to false to hide */
	},
	promptOptions: {
      /* actionMessage limited to 90 characters */
      actionMessage: "Get Notified for upcoming Follow Ups.",
      /* acceptButtonText limited to 15 characters */
      acceptButtonText: "Yes Please",
      /* cancelButtonText limited to 15 characters */
      cancelButtonText: "No Thanks"
    }
}]);
OneSignal.log.setLevel('trace');

OneSignal.push(function() {
	console.log('test');
	OneSignal.on('subscriptionChange', function(isSubscribed) {
	      if (isSubscribed) {
	      OneSignal.getUserId( function(userId) {
	        $.ajax({
	        	type: 'POST',
	        	data: {
	        		action: 'savePlayerId',
	        		id: userId
	        	},
	        	success: function(data){
	        		console.log(data);
	        	}
	        });
             });
	    }
     });
});
OneSignal.showHttpPrompt();
```
The slidedown prompt appears, I click accept and then browser permission appears, then I click Allow and then in the console I get the error
**TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.**

I can't find out which link is it trying to access that goes to 404.

**Comment by VeeK727** [comment]
It was indeed due to the subdomain. I had to copy the files over to my subdomain and everything is working now.

**Comment by natterstefan** [comment]
@VeeK727 you meant the root folder of your subdomain? eg. `sub.example.com/manifest.json`

**Comment by VeeK727** [comment]
Correct.

**Comment by jasonpang** [comment]
@VeeK727 Sorry for the late reply. Glad you got everything working.
