### ISSUE TITLE
notificationPermissionChange does not report "denied" Event on localhost [tested w/ Chrome & Firefox]

### ISSUE THREAD

**Issue by natterstefan** [OneSignal/OneSignal-Website-SDK#281]
Hello,

When I implement the following methods

```js
OneSignal.push(function() {
    OneSignal.on('notificationPermissionChange', function(permissionChange) {
      var currentPermission = permissionChange.to;
      console.log('New permission state:', currentPermission);
    });
  });

export default class Setup extends Component {

    // ...

    onAllowNotifications = async () => {
      OneSignal.push(["registerForPushNotifications"], {modalPrompt: true})
     // ...
    }

    // ...

    render () {
        // ...
        <Button
          title='Continue to allow Push Notifications'
          onClick={this.onAllowNotifications}
         />
        // ...
    }

}
```

it does not listen when I click on the _Block_ Button.

![image](https://user-images.githubusercontent.com/1043668/32829476-7fa83a98-c9f2-11e7-8442-3d157d47479d.png)

But it works when I _Allow_ it or click the _X_ button. Any clues?

Tested on: http://localhost (`allowLocalhostAsSecureOrigin: true`) <<< is the fact that it is http not https important?
Environment: React
Chrome: Version 61.0.3163.100, but also not working in FF (latest)
OneSignal SDKs: latest build (downloaded them today from the [Website](https://documentation.onesignal.com/docs/web-push-sdk-setup-https))

**Update**
After entering `OneSignal.log.setLevel('trace');` in the console I saw this at least when clicking on _Block_:

![image](https://user-images.githubusercontent.com/1043668/32831839-e20475ec-c9f9-11e7-9b18-b4bd6ca24ad4.png)

But still no event in the `notificationPermissionChange` event listener.

**Comment by natterstefan** [comment]
@jasonpang okay, thanks for the answer. I assume then it is because of Chrome and the local setup with http://localhost:port/something. Maybe a package, like https://www.npmjs.com/package/hotel, can solve this for me. Let's see.

**Comment by jwilm** [comment]
@natterstefan please let us know if this is still an issue.
