### ISSUE TITLE
Websites using OneSignal SDK fail to show an image in the notification on Samsung Internet browser

### ISSUE THREAD

**Issue by billyjay** [OneSignal/OneSignal-Website-SDK#282]
In case of Samsung internet, when websites show a notification using OneSignal SDK, the image fails to load. You can test this on www.deccanchronicle.com or www.gozefo.com ( under explore furniture>Beds) After changing the User Agent of the Browser to that of Chrome, the image loads fine.

**Comment by jasonpang** [comment]
Hi there,

It looks like Samsung Internet Browser (v6.2.01.12 at this time) does not support large images. This can be verified independently of OneSignal by [using this notification generator](https://tests.peter.sh/notification-generator/#image=1) on the Samsung Internet Browser.

**Comment by jasonpang** [comment]
Regarding regular notification icons (not large images), I was able to see the icon just fine:

![image](https://user-images.githubusercontent.com/1015970/33043895-c0e12aa8-cdfb-11e7-83f3-7201463816b7.png)

**Comment by billyjay** [comment]
Hello,
I was talking about the following.
https://imgur.com/a/NUx8e

I don't think this notification is shown by the browser. This is shown by content itself. Correct me if I am wrong.

**Comment by maddy3396** [comment]
Hi Looks like Billy Jay is right. 
This should be One Signal SDK issue.
No broken image seen when using Chrome User agent on samsung browser.

**Comment by TrymBeast** [comment]
@jasonpang Is there any follow up on this issue?
This is happening to me too.
The icon for some reason in Samsung Browser is being requested to "/undefined".

Just like in @billyjay image:
![image](https://user-images.githubusercontent.com/1187322/47731328-c761a500-dc5b-11e8-83d8-e33df6c33ba8.png)

**Comment by AdaRoseCannon** [comment]
Testing Samsung Internet Beta on the testing site and it seems to work. 

![test website](https://imgur.com/c2WolPI.jpg)

**Comment by hatakekakashi2999** [comment]
It seems they changed the UI for Samsung Internet. On visiting deccanchronicle.com on Chrome, we can see that there is a complete banner, while visiting the same site on Samsung Internet 9.2, we get just a small bell icon. If that is intentional, I think it is fine.

**Comment by hatakekakashi2999** [comment]
The issue still seems to be there on https://www.buddy4study.com/faq/every-thing-you-need-know-about-education-loans-india

**Comment by jkasten2** [comment]
@TrymBeast The image not loading on the permission prompt has been fixed in the latest SDK>
https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/150703
