### ISSUE TITLE
Display notify button in a specific page

### ISSUE THREAD

**Issue by mellyna** [OneSignal/OneSignal-Website-SDK#290]
Hi !
I'm using Onesignal for my wordpress website. Works great but I'd like to display the notify button on a specific page and only on this page. How can I achieve that?
Thanks

**Comment by jasonpang** [comment]
Hi @mellyna,

This is possible but it'll require some engineering. You can take a look at this JavaScript code sample for hiding the notify button when the user is subscribed, and modify it to only show the notify button on specific pages. How you determine which page the user is on may depend on your permalink structure. Link: https://documentation.onesignal.com/docs/customize-permission-messages#section-hiding-the-subscription-bell.
