### ISSUE TITLE
Django templates URL pattern redirection

### ISSUE THREAD

**Issue by dungeonpp** [OneSignal/OneSignal-Website-SDK#294]
I am facing this issue in https web push setup. in https web push setup we need to have a OneSignalSDKWorker.js, manifest.json and OneSignalSDKWorkerUpdater.js files served from the root url. So I have served those files from root of the project directory. I have referred those files as a template from a view using url pattern and these files are readily accessible. What onesignal's script does is it treats the   <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async></script>
as a call to the scriptworker and searches for serviceworker as https://mysite.com/OneSignalSDKWorker.js?appId='YOUR_APP_ID' . But the problem in django urls is that if I mention the url pattern as empty to make this file accessible it will take this empty pattern and display the serviceworker at https://mysite.com/ itself. How do I make sure that these files are not redirect considering the django url patterns?

ERROR in the console:

The script resource is behind a redirect, which is disallowed.
/OneSignalSDKWorker.jsOneSignalSDKWorker.js?appId=05716e11-685b-464a-b2d1-abb59bd2af38 Failed to load resource: net::ERR_UNSAFE_REDIRECT

**Comment by jwilm** [comment]
Hey there, sorry for the delay on response. Did you get this resolved?

**Comment by jasonpang** [comment]
Closed due to inactivity. Feel free to post another issue if you're still experiencing this!
