### ISSUE TITLE
Workbox service worker installation failure

### ISSUE THREAD

**Issue by shashik-edgz** [OneSignal/OneSignal-Website-SDK#297]
im trying to integrate oneSignal with my PWA Angular app. im using workbox js as my service worker generator .i tried as onesiganl said about how should two service worker integrate . but it didnt work

`importScripts('sw.js');
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDK.js');
`
and i registerd sw like this

> function registerServiceWorker() {
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker
      .register('OneSignalSDKWorker.js')
      .then(reg => {
        registration = reg;
        swLog('Registration successful', registration);
        registration.onupdatefound = () => checkServiceWorkerStateChange();
      })
      .catch(e =>
        console.error('Error during service worker registration:', e)
      );
  } else {
    console.warn('Service Worker is not supported');
  }
}

but both of my service workers become redundant.

**Comment by jasonpang** [comment]
@shashik-edgz Are you still running into this issue?

If so, can you provide the source of sw.js or a cloneable repo project for your setup?

**Comment by jasonpang** [comment]
Closed due to inactivity. Feel free to post another issue if you're experiencing this!
