### ISSUE TITLE
Prevent internal SDK errors from being shown in console

### ISSUE THREAD

**Issue by codeslane** [OneSignal/OneSignal-Website-SDK#298]
Uncaught (in promise) : tslib.es6.js:62 Uncaught (in promise) 
AlreadySubscribedError {message: "This operation can only be performed when the user is not subscribed.", name: "AlreadySubscribedError", stack: "AlreadySubscribedError: This operation can only be…m/sdks/OneSignalSDK.js:1:1460)↵    at <anonymous>"}message: "This operation can only be performed when the user is not subscribed."name: "AlreadySubscribedError"stack: "AlreadySubscribedError: This operation can only be performed when the user is not subscribed.↵    at Function.<anonymous> (https://cdn.onesignal.com/sdks/OneSignalSDK.js:1:137163)↵    at i (https://cdn.onesignal.com/sdks/OneSignalSDK.js:1:2358)↵    at Object.next (https://cdn.onesignal.com/sdks/OneSignalSDK.js:1:1693)↵    at s (https://cdn.onesignal.com/sdks/OneSignalSDK.js:1:1460)↵    at <anonymous>"__proto__: t
s @ tslib.es6.js:62
Promise resolved (async)
u @ tslib.es6.js:64
s @ tslib.es6.js:62
Promise resolved (async)
u @ tslib.es6.js:64
s @ tslib.es6.js:62
Promise resolved (async)
u @ tslib.es6.js:64
s @ tslib.es6.js:62
Promise resolved (async)
u @ tslib.es6.js:64
s @ tslib.es6.js:62
Promise resolved (async)
u @ tslib.es6.js:64
(anonymous) @ tslib.es6.js:65
u @ tslib.es6.js:61
e.showHttpPrompt @ OneSignal.ts:245
(anonymous) @ InitHelper.ts:341
Promise resolved (async)
e.sessionInit @ InitHelper.ts:325
(anonymous) @ InitHelper.ts:283
i @ tslib.es6.js:91
(anonymous) @ tslib.es6.js:72
(anonymous) @ tslib.es6.js:65
u @ tslib.es6.js:61
e.internalInit @ InitHelper.ts:220
(anonymous) @ OneSignal.ts:209
Promise resolved (async)
(anonymous) @ OneSignal.ts:205
i @ tslib.es6.js:91
(anonymous) @ tslib.es6.js:72
(anonymous) @ tslib.es6.js:65
u @ tslib.es6.js:61
n @ OneSignal.ts:162
complete.document.readyState.interactive.document.readyState.document.onreadystatechange @ OneSignal.ts:225

**Comment by jasonpang** [comment]
Hi,

This is an internal error that shouldn't be thrown from our SDK, and we're working to prevent these internal errors from showing up in future releases.

**Comment by jasonpang** [comment]
- Remove `!OneSignal.config` check and error throwing at https://github.com/OneSignal/OneSignal-Website-SDK/blob/master/src/helpers/SubscriptionHelper.ts#L164.

- Modify to check if `OneSignal` is defined at https://github.com/OneSignal/OneSignal-Website-SDK/blob/master/src/helpers/SubscriptionHelper.ts#L180.

**Comment by jkasten2** [comment]
This issue was fixed in release [150700](https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/150700). It only warns now in the javascript console if the OneSignal log level is set high enough.
> checkIfAutoPromptShouldBeShown returned an error st: This operation can only be performed when the user is not subscribed.
