### ISSUE TITLE
Workbox service worker syntax error

### ISSUE THREAD

**Issue by naveedahmed1** [OneSignal/OneSignal-Website-SDK#299]
Hi,

Can you please guide how to use OneSignal with Workbox

https://developers.google.com/web/tools/workbox/

I tired it but it was throwing below error:

```
workbox-sw.prod.v2.1.2.js:19 Uncaught SyntaxError: Unexpected identifier
    at sw.js:1
    at OneSignalSDKWorker.js:1
(anonymous) @ sw.js:1
(anonymous) @ OneSignalSDKWorker.js:1
myscript.min.js:5 ServiceWorker registration TypeError: Failed to register a ServiceWorker: ServiceWorker script evaluation failed
```

**Comment by shashik-edgz** [comment]
i would like to know too

**Comment by naveedahmed1** [comment]
@jasonpang can you please guide?

**Comment by jasonpang** [comment]
@naveedahmed1 @shashik-edgz,

Do you have a repo I could clone to reproduce the error you're getting?

Based on the provided stack trace, it looks like `workbox-sw.prod.v2.1.2.js:19` has a syntax error. This would be unrelated to our service worker.

**Comment by jasonpang** [comment]
Closed due to inactivity. Feel free to post another issue if you're still experiencing this issue!
