### ISSUE TITLE
web push icon in Yandex browser

### ISSUE THREAD

**Issue by Lomski** [OneSignal/OneSignal-Website-SDK#300]
![2018-01-10 13-10-05](https://user-images.githubusercontent.com/8664572/34754292-9365ff9c-f608-11e7-9a71-b79f9eea6735.png)
![2018-01-10 13-09-29](https://user-images.githubusercontent.com/8664572/34754298-a086cd78-f608-11e7-9381-68720f77ddce.png)
Icon is displayed correctly In Chome, Firefox.

**Comment by jasonpang** [comment]
Hi,

We were able to reproduce the issue and we've fixed it in https://github.com/OneSignal/OneSignal-Website-SDK/commit/7e383e2d0b13211ae8266dbdf0daef47c978fc05.
