### ISSUE TITLE
Customize centralized AMP permission dialog

### ISSUE THREAD

**Issue by Ysery** [OneSignal/OneSignal-Website-SDK#301]
I want to translate them into my language.

Earlier it could be done, but how now?

Sorry for My English

**Comment by jasonpang** [comment]
Hi @Ysery,

We changed the AMP helper file contents from hardcoded HTML markup to a centralized version we host for easier and more consistent upgrades.

Unfortunately, it isn't possible to modify `amp-permission-dialog.html` with this change.

We'll revisit this issue and consider exposing JavaScript hooks to customize popup text with.

**Comment by Ysery** [comment]
Hi @jasonpang 

Thank you. I'm waiting for implementation

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
