### ISSUE TITLE
Getting SdkInitError message "This web push config can only be used on"

### ISSUE THREAD

**Issue by MONOmah-V** [OneSignal/OneSignal-Website-SDK#303]
Hi!

Trying OneSignal's webpush. My test-site uses https, but I'm debugging it on http://localhost. I've checked "Local Testing" in project configuration on OS-Dashboard. But... During the initialization step I'm getting `SdkInitError`, because [`appConfig.restrictedOriginEnabled`](https://github.com/OneSignal/OneSignal-Website-SDK/blob/master/src/managers/ConfigManager.ts#L45) is `true`. And therefore initialization never reaches actual check for localhost-allowance in `SubscirptionHelper`.

**Comment by jasonpang** [comment]
Closed due to inactivity. Please contact support@onesignal.com if you're still getting this error!

**Comment by gajus** [comment]
> If you're getting an error message about "This web config can only be used on https://a-different-site.com", please double-check the Site URL set in your dashboard web config editor. Check for differences between http:// and https://, and also differences between www. and no www.

He was asking about localhost though. Same issue here.

**Comment by gajus** [comment]
https://github.com/OneSignal/OneSignal-Website-SDK/issues/327#issuecomment-367410300

> Web push apps created in or after December 2017 have an extra check to make sure the Site URL specified in your OneSignal dashboard is the only site using your web push config. [..]
> For testing locally, please create a separate development app.
