### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by wickeym** [OneSignal/OneSignal-Website-SDK#308]
Hi,

I am getting this error:
```
TypeError: Cannot read property 'toString' of undefined
```
![screenshot of console error](https://user-images.githubusercontent.com/11077339/35447444-c011d26c-0285-11e8-9bd7-dbdc50238af3.png)
Relevant piece from WorkerMessenger.ts
```
  public findListenersForMessage(command: WorkerMessengerCommand): any {
    return this.replies[command.toString()] || [];
  }
```

My setup is using Angular v5, and using their angular/service-worker.
In my app.module.ts, I set OneSignalSDKWorker.js as the service worker, then import angular's service worker using an importScripts as documented here: https://documentation.onesignal.com/v3.0/docs/web-push-sdk-setup-https#section-can-onesignal-integrate-with-another-service-worker-on-my-site-or-a-progressive-web-app-
```
ServiceWorkerModule.register('/OneSignalSDKWorker.js', {enabled: environment.production}),
```

I don't yet see what side-affects this error is causing, I am able to receive notifications, and the angular service worker seems to be working correctly.

To see this error, visit my site: https://developer.wickeyappstore.com/
and it shows after allowing push. It also shows every time I push a new version of the site and the angular service worker picks it up, then immediately after that refresh to activate the new version.

Sincerely,
Michael Wickey

**Comment by wickeym** [comment]
Hi @jasonpang,

Thanks for your response, and thanks for making a nice product.

Sincerely,
Michael Wickey

**Comment by nickpunt** [comment]
Hi @wickeym, this is fixed now!

**Comment by jupereira0920** [comment]
Hi @nickpunt i'm still getting this error, . im using angular 5 and service worker ngsw.js generated by angular-cli.
Thanks

**Comment by jasonpang** [comment]
Hey @jupereira0920,

Do you have a cloneable repo or a publicly accessible URL we could visit to reproduce the error? Feel free to reach out to us at support@onesignal.com if you'd like to share the link privately.

**Comment by jupereira0920** [comment]
Hi @jasonpang i try to reproduce the error again, but don't no what happen, it just stopped (xD). 
With **https** i dont get the error, only on **localhost**. 
I'm sorry for the inconvenient.
Best regards, and great project 👍

**Comment by jasonpang** [comment]
It's possible that page view was using a cached version of our older web SDK. You can try clearing all browser data (especially the Cached files clearing setting) to make sure you're using the newest version of our SDK.

If you're able to get intermittent errors, can you please:

- Paste the error message here from the console?
- Type `OneSignal.VERSION` to see what version of the SDK is being used

Closing the issue until then, but if you do see something, just post those details here and we can re-open the issue.
