### ISSUE TITLE
Firefox keep asking for permissions to display notifications

### ISSUE THREAD

**Issue by 007me** [OneSignal/OneSignal-Website-SDK#309]
Hi,
I've added OneSignal to my WP sites long ago.
On Chrome (on win 10) everything works fine.
FF latest version (on Win10) keeps asking for permission to display notifications every time I start the browser.
What could be the reason?
Thanks.

**Comment by jasonpang** [comment]
Hi,

Can you provide a URL to a page on your website where you see this issue?

**Comment by 007me** [comment]
Hi,

Yes. You can see it here:
Https://blog.udiburg.com
Or
Https://hamitlabetet.com
Or
Https://ramon253.udiburg.com

Regards,

________________________________
Udi Burg

e udi@udiburg.com  t +972-77-7673020 f +972-77-2134265 m+972-54-4249440

Ramat Gan, Israel w http://blog.udiburg.com

Think before you print

**Comment by jasonpang** [comment]
Hi @007me,

Sorry for the late reply.

Have you configured Firefox to clear your data when exiting the browser?

**Comment by 007me** [comment]
Hi Jason,

 

Yes, but not the cookies.

See this screenshot for my settings. So why does it happen?

 



 

Regards,

 

 

__________________________________________________________________

 

Udi Burg 

e udi@udiburg.com <mailto:udi@udiburg.com>   t +972-77-7673020 f +972-77-2134265 m +972-54-4249440 

Ramat Gan, Israel w http://blog.udiburg.com <http://blog.udiburg.com/> 

 <https://www.linkedin.com/in/udiburg/> 

 

P Think before you print

**Comment by 007me** [comment]
Understood, so visitors that do not clear their data won't see the request again. Right? 

 

 

__________________________________________________________________

 

Udi Burg 

e udi@udiburg.com <mailto:udi@udiburg.com>   t +972-77-7673020 f +972-77-2134265 m +972-54-4249440 

Ramat Gan, Israel w http://blog.udiburg.com <http://blog.udiburg.com/> 

 <https://www.linkedin.com/in/udiburg/> 

 

P Think before you print

**Comment by jasonpang** [comment]
That's correct @007me! By default, data won't be cleared when exiting the browser, and users will not be seeing the prompt again after accepting, or won't see it for 3, 7, and 30 days after dismissing it (https://documentation.onesignal.com/docs/permission-requests#section-after-dismissing-a-web-push-prompt-when-is-the-prompt-shown-again-).

**Comment by 007me** [comment]
Thanks a lot!

 

 

__________________________________________________________________

 

Udi Burg 

e udi@udiburg.com <mailto:udi@udiburg.com>   t +972-77-7673020 f +972-77-2134265 m +972-54-4249440 

Ramat Gan, Israel w http://blog.udiburg.com <http://blog.udiburg.com/> 

 <https://www.linkedin.com/in/udiburg/> 

 

P Think before you print
