### ISSUE TITLE
Slide Prompt will reprompt after 3 days

### ISSUE THREAD

**Issue by nuryagdym** [OneSignal/OneSignal-Website-SDK#324]
Hi, I pressed cancel in Slide Prompt and expected it to reprompt after 1 day. I checked it the next day but it did not show up. I checked it 2 days later again it did not show up. In Onesignal Documentation I could find  any mention when it is gonna reprompt. And then after enabling Onesignal tracing I saw "Slide Prompt will reprompt after 3 days" message after pressing Cancel button in Slide Prompt. 

Can you add to the Documentation the interval of reprompting Slide Prompt

**Comment by jasonpang** [comment]
Hi @nuryagdym,

Thanks, [we've added it to this section of our documentation](https://documentation.onesignal.com/v5.0/docs/permission-requests#section-after-dismissing-a-web-push-prompt-when-is-the-prompt-shown-again-).
