### ISSUE TITLE
notificationClickHandlerMatch and notificationClickHandlerAction parameters are overridden by default values

### ISSUE THREAD

**Issue by gabrielprc** [OneSignal/OneSignal-Website-SDK#337]
**Description:**

I've been trying to make use of the **notificationClickHandlerAction** and **notificationClickHandlerMatch** parameters with their **focus** and **origin** respectively, but to no avail.

When a notification is clicked, the default behavior is fired: If a tab is open, even though it is open in the same domain as the incoming notification's URL (which should be accepted by setting the **notificationClickHandlerMatch** as **origin**, according to the docs), a new tab is open unless the current URL and the notification's URL match _exactly_.

After trying everything and rereading the docs more than a couple times, I set some breakpoints in the init function and wherever there are checks for the values of notificationClickHandlerMatch and notificationClickHandlerAction. Having debugged these, I noticed that the values I'm passing in are being ignored and overridden by the default values (**exact** and **navigate**, which causes the default behavior above mentioned).

I wasn't able to find a solution to this in older issues related to these parameters or to the behavior fired after clicking on a notification, so I find no other option but to ask for advise and report what seems to me to be a bug.

**Steps to Reproduce Issue:**

Initialize OneSignal with the following parameters (removed appId for privacy purposes):

`OneSignal.push(["init", {
	persistNotification: false,
	autoRegister: false,
	notificationClickHandlerMatch: 'origin',
	notificationClickHandlerAction: 'focus',
        notifyButton: {
            enable: true,
            displayPredicate: function() {
                return OneSignal.isPushNotificationsEnabled()
                    .then(function(isPushEnabled) {
                        return !isPushEnabled;
                    });
            }
        }
}]);`

**Thanks in advance.**

**Comment by jasonpang** [comment]
Hi @gabrielprc,

I'm not able to reproduce this issue of `notificationClickHandlerAction` and `notificationClickHandlerMatch` being overwritten unless your dashboard configuration was set to Typical Site. Is it possible you selected "Typical Site" for your setup, which overrides custom initialization options?

**Comment by gabrielprc** [comment]
Yes, seems that was it! Must have missed that in the Documentation, it wasn't really clear for me that it was required to select the Custom configuration to enable initialization parameters.

Thanks for the quick support!
