### ISSUE TITLE
Getting TypeError: OneSignal.getListeners is not a function when pressing On Notification

### ISSUE THREAD

**Issue by dmastag** [OneSignal/OneSignal-Website-SDK#344]
**Description:**
My Web App used to work but since a couple of Days its not working anymore.
Problem is that when on Chrome Browser (Web and Android) I click on the Push Notification.

**Steps to Reproduce Issue:**
1. Press on the Push Notification
2. Nothing Happens
3. The following shows on the console.log
```ERROR Error: Uncaught (in promise): TypeError: OneSignal.getListeners is not a function```

**Anything else:**
I can't find the same issue here or on google so I think the problem is on my Code?
Am using Angular and the following is from my code:

```
    ngOnInit() {
      console.log('Init OneSignal');
      OneSignal.push(['init', {
        appId: '',
        // autoRegister: false,
        allowLocalhostAsSecureOrigin: true,
        notifyButton: {
          enable: false
        }
      }]);
      console.log('OneSignal Initialized');
      OneSignal.push(() => {
        console.log('Register For Push');
        OneSignal.push(['registerForPushNotifications'])
      });
      OneSignal.push(() => {
        // Occurs when the user's subscription changes to a new value.
        OneSignal.on('subscriptionChange', function (isSubscribed) {
          console.log(`The user's subscription state is now:`, isSubscribed);
          OneSignal.getUserId().then(function (userId) {
            console.log('User ID is', userId);
          });
        });
      });
      this.addListenerForNotificationOpened();
    }

    addListenerForNotificationOpened() {
      OneSignal.push(['addListenerForNotificationOpened', notificationData => {
        console.log('Received NotificationOpened:', notificationData);
        this.addListenerForNotificationOpened();

        // Actions
        const payload = notificationData.data;
        if (payload.action === 'OpenDetail') {
          this.router.navigate(['/app', 'forms', payload.item]);
        }
      }]);
    }
```

**Comment by rlarmore** [comment]
I am having the same problem. Same code use to work, It just started happening no code changes on my client side.

ServiceWorkerManager.js:346 Uncaught (in promise) TypeError: OneSignal.getListeners is not a function
    at e.<anonymous> (ServiceWorkerManager.js:346)
    at IntegrationKind.js:16
    at Object.next (IntegrationKind.js:16)
    at IntegrationKind.js:16
    at new Promise (<anonymous>)
    at i (IntegrationKind.js:16)
    at ServiceWorkerManager.js:332
    at e.onPageMessageReceivedFromServiceWorker (WorkerMessenger.js:217)

**Comment by dmastag** [comment]
I asked the Support through the Chat Function on the OneSignal website and they replied that there is no getListeners function.

Not sure what I should do about it.

**Comment by jasperltz93** [comment]
I have this issue as well, please help

**Comment by jkasten2** [comment]
@dmastag Thanks for reporting. We were able to reproduce the issue working on resolving it

**Comment by jkasten2** [comment]
@dmastag @jasperltz93 @rlarmore The bug as been fixed in the commit above. We are shooting for a release sometime next week with this fix included.

**Comment by dmastag** [comment]
Great, waiting to be able to test it

**Comment by jasperltz93** [comment]
@jkasten2 thank you very much

**Comment by jkasten2** [comment]
Fix is now released in version 150200.
https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/150200

The cdn.onesignal.com has been updated with the release. To make sure you have the latest version clear your browser cache
