### ISSUE TITLE
subscriptionChange doesn't work properly

### ISSUE THREAD

**Issue by kingluddite** [OneSignal/OneSignal-Website-SDK#345]
**Description:**

subscriptionChange event only fires on the first click. When I click to unsubscribe it does not fire. When I then click to subscribe it does not fire

**Steps to Reproduce Issue:**

Using this code:

```HTML
<script>
window.OneSignal = window.OneSignal || [];
OneSignal.push(function () {
	OneSignal.on("subscriptionChange", function (isSubscribed) {

        console.log('Subscription changed');

		if (isSubscribed) {
			_satellite.track("one-signal-subscribe")
		} else {
			_satellite.track("one-signal-unsubscribe")
		}
	});
});
</script>
```

1. Code added to the footer of a WordPress site
2. Click oneSignal icon and form opens
3. Click on subscribe button and console.log() records subscribe
4. Click icon again and click unsubscribe and the event does not fire
5. Click icon again to subscribe and the event does not fire

**Anything else:**

I found a workaround to get the event to fire but I would rather OneSIgnal update their API so that when you make future changes to your code/structure, it won't break my code

Here is my current workaround:

```javascript
window.OneSignal = window.OneSignal || [];

window.OneSignal.push(function() {
    window.OneSignal.once('notifyButtonLauncherClick', function() {
        hookTreeModified();
    });

    function hookTreeModified() {
        if (getDialogBody()) {
            getDialogBody().addEventListener('DOMSubtreeModified', onDialogBodyModified);
        }
    }

    function onDialogBodyModified() {
        console.log('OneSignal: Dialog body DOMSubtreeModified event.');
        if (getSubscribeButton()) {
            getSubscribeButton().removeEventListener('click', onSubscribeButtonClicked);
            getSubscribeButton().addEventListener('click', onSubscribeButtonClicked);
        }
        if (getUnsubscribeButton()) {
            getUnsubscribeButton().removeEventListener('click', onUnsubscribeButtonClicked);
            getUnsubscribeButton().addEventListener('click', onUnsubscribeButtonClicked);
        }
    }

    function onSubscribeButtonClicked() {
        console.log('Subscribe button clicked.')
        _satellite.track('one-signal-subscribe');
        OneSignal.event.trigger('notifyButtonSubscribeClick');
    }

    function onUnsubscribeButtonClicked() {
        console.log('Unsubscribe button clicked.');
        _satellite.track('one-signal-subscribe');
        OneSignal.event.trigger('notifyButtonUnsubscribeClick');
    }

    function getDialogBody() {
        return document.querySelector('.onesignal-bell-launcher-dialog-body');
    }

    function getSubscribeButton() {
        return document.querySelector('#onesignal-bell-container .onesignal-bell-launcher #subscribe-button');
    }

    function getUnsubscribeButton() {
        return document.querySelector('#onesignal-bell-container .onesignal-bell-launcher #unsubscribe-button');
    }
});
```

**Comment by jkasten2** [comment]
@kingluddite Thanks for reporting, we will look into improving the `subscriptionChange` to fire for subscription changes done through the bell icon by the user

**Comment by tristanleboss** [comment]
Workaround is not working for me.  The `onSubscribeButtonClicked` and `onUnsubscribeButtonClicked` functions are triggered but the `subscriptionChange` OneSignal event callback is not. No errors in the dev console.

**Comment by oytuntez** [comment]
We are implementing our custom workflow with OneSignal and this is a stopper for us (and we didn't notice for a while, so our production is broken).

Here is TRACE log:

![image](https://user-images.githubusercontent.com/656635/42952859-4256f4a6-8b47-11e8-91ef-943985766e89.png)


Is there ETA for this, or should we PR?

**Comment by oytuntez** [comment]
@Droppix we are planning to unsubscribe via the backend instead of frontend.

**Comment by Droppix** [comment]
I understand, but I suppose it will be possible to be notified on the front-end of unsubscription?

**Comment by oytuntez** [comment]
yes, they would mention this issue in their merge or this issue would be closed by the team

**Comment by Droppix** [comment]
Great!
Thanks

**Comment by itrush** [comment]
@kingluddite @Droppix @oytuntez Testing on the latest SDK version (150402), the issue doesn't seem to be reproducible. Could you please verify whether you're still seeing it? If so, what environment do you use? We would be happy to help resolving it.

**Comment by oytuntez** [comment]
@itrush 

we are using your CDN: https://cdn.onesignal.com/sdks/OneSignalSDK.js

We observed this in all major browser. Here is our controller for OneSignal actions: http://motaword.com/app/app/Controller/Notifier/OneSignal.js

On line 55, subscriptionChange event is only triggered when isSubscribed is true (when subscription enabled).
On line 87, to work around this issue, we are unsubscribing in the backend via REST API instead.

**Comment by Droppix** [comment]
@itrush 

I use your CDN: https://cdn.onesignal.com/sdks/OneSignalSDK.js

The subscription or not, event works well, but I cannot hide and positioning  the "bell".
Bellow my code:
`


       <script type="text/javascript">
            
            var OneSignal = window.OneSignal || [];
            OneSignal.push(function() {
            
                OneSignal.push(["init", {
                    appId: {@Configuration path="OneSignal.appId"/},        
                    notifyButton: {
                        enable: false,
                        position: 'bottom-right',
                        offset: {
                            bottom: '50px',
                        },
                    }
                }]);
        
                function onSubscribeButtonClicked() {
                    OneSignal.getUserId(function(userId) { 
        
                        const options = {
                            method  : 'POST',
                            headers : new Headers({ 'Content-Type' : 'application/json' }),
                            body    : JSON.stringify({ subscribe: true, userId: userId }),
                            credentials: "same-origin"
                        };
        
                        fetch('/api/webpush/register', options).then((res) => {
                        }).catch((error) => {
                        });  
                    });
                }
        
                function onUnsubscribeButtonClicked() {
                    OneSignal.getUserId(function(userId) { 
        
                        const options = {
                            method  : 'POST',
                            headers : new Headers({ 'Content-Type' : 'application/json' }),
                            body    : JSON.stringify({ subscribe: false, userId: userId }),
                            credentials: "same-origin"
                        };
            
                        fetch('/api/webpush/register', options).then((res) => {
                        }).catch((error) => {
                        });
                    });
                }

                OneSignal.on('subscriptionChange', function (isSubscribed) {                    
                    if(isSubscribed) {
                        onSubscribeButtonClicked();                        
                    }
                    else {
                        onUnsubscribeButtonClicked();
                    }
                });
            
            });            
        
    </script>
`

**Comment by itrush** [comment]
@oytuntez Tested once again with the setup you described, works like a clockwork. Could it be something more specific? Have you tried disabling cache? What browser and the specific version do you use? It seems your changes are not live yet, otherwise I could try to take a look at your site if it helps.

**Comment by itrush** [comment]
@Droppix If I understood your question correctly, you're trying to hide bell prompt after user subscribed and change it's positioning. All these settings can be easily set up and previewed in our dashboard when you choose typical site setup flow for web push. It's actually a recommended way of configuring your OneSignal app and works for majority of use-cases. You can still subscribe to OneSignal events and add your custom logic. Please see a screenshot below:

![bell_config_dashboard](https://user-images.githubusercontent.com/39500603/43913100-faa83e80-9bb8-11e8-993a-3763da56b1d6.png)

Hope I answered your question :)

**Comment by Droppix** [comment]
@itrush

Sorry it's not good solution for me.
I need to control the display of the "bell" by javascript and not by "dashboard". To be more precise, I need to display the "bell" only on my configuration page.

**Comment by itrush** [comment]
@Droppix 
There are a few options again. 

First of all, you may think of using a different kind of prompt, namely Custom Link that we recently added which will be rendered only where you place a specific markup. [More info in the docs](https://documentation.onesignal.com/v5.0/docs/custom-link-prompt).

If you still prefer to have a bell as your prompt of choice, the easiest would be to enable notifyButton by default and to play with css in order to hide/show it on specific pages. For instance the following css hides the bell from UI
```
#onesignal-bell-container {
    display: none;
}
```

**Comment by itrush** [comment]
Closing this issue. Please open a new one if you figure out the specific steps to reproduce. Thanks.
