### ISSUE TITLE
OneSignal push is not function error in ionic 3 

### ISSUE THREAD

**Issue by shrutikateiosys** [OneSignal/OneSignal-Website-SDK#352]
**Description:**
Here i have used web push in ionic 3 for browser support.In index.html it works fine but in typescript it shows error OneSignal.push is not a function.
 **ERROR TypeError: OneSignal.push is not a function.**

**Comment by jkasten2** [comment]
@shrutikateiosys If you're using the OneSignal web push SDK your initialization should look like this.

```html
<head>
  <link rel="manifest" href="/manifest.json">
  <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async></script>
  <script>
    var OneSignal = window.OneSignal || [];
    OneSignal.push(["init", {appId: "YOUR_APP_ID"}]);
  </script>
</head>
```

For Ionic / Cordova this should only be use for browsers, such as a PWA (Progressive Web App).
See the full Web push setup SDK guide below.
https://documentation.onesignal.com/docs/web-push-quickstart

For Ionic apps for iOS and Android devices it should look something like this.
```javascript
constructor(platform: Platform, statusBar: StatusBar, splashScreen: SplashScreen) {
  platform.ready().then(() => {
    // ...
    window["plugins"].OneSignal
      .startInit("YOUR_APPID")
      .endInit();
  });
}
```
See the full Ionic Mobile SDK setup below.
https://documentation.onesignal.com/docs/ionic-sdk-setup
