### ISSUE TITLE
Can't customize web push prompt behaviour by calling showHttpPrompt

### ISSUE THREAD

**Issue by ghashi** [OneSignal/OneSignal-Website-SDK#355]
**Description:**

In the [Docs](https://documentation.onesignal.com/docs/permission-requests#section-after-dismissing-a-web-push-prompt-when-is-the-prompt-shown-again-) it is said:
> By default, after dismissing a prompt, a web push prompt won't be shown for the next 3 days initially. After 3 days when the prompt is shown again, if the prompt is dismissed again then it won't be shown for the next 7 days. After 7 days elapse, if the prompt is dismissed again it won't be shown for the next 30 days. Subsequent dismissals will also hide the prompt for 30 days.
The above are our defaults to maintain a good user experience. You may customize and show the prompt at any time using our showHttpPrompt() web SDK API.

At the same time it is [said](https://documentation.onesignal.com/docs/web-push-setup-faq#section-slide-prompt): 
> Even if you trigger showHttpPrompt(), it may not always show the message. The message will not be shown if any of the following are true:
> - The user previously dismissed the message by clicking the "No Thanks" button
> ...

Therefore, **is it possible to "customize and show the prompt at any time"?** For instance, due to some business rules on my web app, I want to show the prompt every time the user visits some pages. 

**Steps to Reproduce Issue:**

1. Call `showHttpPrompt()` on one page
2. Click "No thanks"
3. Call `showHttpPrompt()` again on another page
4. The prompt won't show up (I would like to show it)

**Comment by jkasten2** [comment]
@ghashi We have updated our docs providing an option to override this behavior if needed.
https://documentation.onesignal.com/docs/web-push-sdk#section--showhttpprompt-

Note, for a good user experience we recommend that the user would have to take some action on the page rather than just visiting a specific page.
