### ISSUE TITLE
OneSignal does not send notifications in chrome but everything is correct!

### ISSUE THREAD

**Issue by mouhalves** [OneSignal/OneSignal-Website-SDK#357]
Hey there @jasonpang !

I saw . that you gave a nice help to our friend in there and I'm looking to solve a problem to so I'm wondering if that's any change that you can help me too.

So One signal is up at (www.4gnews.pt) and all seems ok... But! that's a big But!

Safari notifications work has it supposed.
Chrome and Android on the other hand, not really.
The bell and notification show up, reader sign it but never got the confirmation notification or any other notification.

That happens to Android as well... I've literally tried everything of my knowledge. Until I got to this amazing threat that not solved my problem either.

If you can give me a hand on this, please do. We have 40k subscribers that not receive a thing! =(

Best,

**Comment by jkasten2** [comment]
@mouhalves I tested your site on Chrome on both macOS and Android the device subscribed successfully and displayed your welcome notification without any issues. I recommend contacting OneSignal support with more details on the issue and they can take a look at your site from their end.
