### ISSUE TITLE
Make Slide Prompt pass GDPR

### ISSUE THREAD

**Issue by ayumihamsaki** [OneSignal/OneSignal-Website-SDK#362]
Hello,

I'm sure there is a feature in Onesignal to be able to do what I am about to ask.

I have set up the Slide Prompt as shown in the screenshot below:

![1](https://user-images.githubusercontent.com/17784082/40587262-a39fc500-61c4-11e8-94d2-d06c74b4c62f.png)

I was looking today at the AMP Version of OneSignal and saw that it would pass GDPR, yet the Desktop version would not pass GDPR.

See below a screenshot of the AMP Version:

![2](https://user-images.githubusercontent.com/17784082/40587284-f4df1e70-61c4-11e8-8662-0d166f33afdc.png)

> GDPR states that a person can subscribe to the OneSignal service at any time, once they have subscribed they can unsubscribe at any time also and this is my issue.

On Desktop a user can subscribe easily but once they have subscribed they can't unsubscribe.

**Is there some code that will allow me to create a button for users to be able to unsubscribe and I can put that in my Cookie Settings Page.**

~Then OneSignal would pass GDPR.

**Comment by AcidRaZor** [comment]
I'm able to unsubscribe on the desktop version of their AMP implementation. Are you sure you implemented this correctly and that your CSS doesn't block the click with a different element, preventing the person from unsubscribing?

**Comment by ayumihamsaki** [comment]
@AcidRaZor I'm not using the AMP implementation on the Desktop version of my PWA's, I'm using the following:

Desktop PWA - OneSignal Slide Prompt Desktop Setup.
Mobile AMP - OneSignal AMP Setup.

(Two different websites joined together).

My issue is that the Desktop version doesn't have an unsubscribe button and I was hoping someone could point me to the direction where they have the code to create a custom button and be able to unsubscribe users.

**Comment by ayumihamsaki** [comment]
cc @jasonpang Probably best person to ask on this.

**Comment by AcidRaZor** [comment]
Did you even read the documentation?

https://documentation.onesignal.com/docs/web-push-sdk#section-subscription-change

**Comment by ayumihamsaki** [comment]
@AcidRaZor I didn't read that webpage you suggested, everytime I did a search on their website I kept getting this webpage: https://documentation.onesignal.com/docs/unsubscribe-from-notifications

Thanks for the link and your help! Can make an unsubscribe toggle button now.
