### ISSUE TITLE
TypeError: Cannot read property 'force' of undefined

### ISSUE THREAD

**Issue by rezakeramati** [OneSignal/OneSignal-Website-SDK#363]
The new version of script is using `privateShowHttpPrompt` instead of `showHttpPrompt`, but in  `privateShowHttpPrompt` this following code is missing, causing error     
```
if (!options)
      options = {};
```
causing the following error 

```
Uncaught (in promise) TypeError: Cannot read property 'force' of undefined
    at Function.<anonymous> (OneSignal.js:281)
    at EmailDeviceRecord.js:7
    at Object.next (EmailDeviceRecord.js:7)
    at s (EmailDeviceRecord.js:7)
```

**Comment by awongwork** [comment]
I am experiencing the same error.

![image](https://user-images.githubusercontent.com/4719921/40723324-b1d85306-63ec-11e8-91a1-1ed482d84f62.png)

**Comment by jkasten2** [comment]
Thanks for reporting, we are looking to fixing this for the next release

**Comment by franj0** [comment]
@jkasten2 Do we need w8 for new release or you will push some fix_release? thank you

**Comment by jkasten2** [comment]
@franj0 It will be pushed to the OneSignal cdn when released so you won't need to change anything. We are shooting for a release next week.

**Comment by racram** [comment]
@jkasten2 Thanks for the update, we are facing the same issue, is there a work around or we just wait for the fix?

**Comment by boczeratul** [comment]
Any updates? seems like it's still broken
<img width="700" alt="2018-06-13 1 43 19" src="https://user-images.githubusercontent.com/1079990/41332274-c6a81b26-6f0f-11e8-8638-14b4f6cba7cb.png">

**Comment by franj0** [comment]
I still have the same problem

**Comment by shyamal890** [comment]
Same problem here too.

**Comment by newbie7777** [comment]
The problem is also available to me. 
Is there a solution? :)

**Comment by franj0** [comment]
@jkasten2 is your commit merged and released?

Because throwing me same error
![image](https://user-images.githubusercontent.com/11553585/41409577-fc2fc2fe-6fd6-11e8-8b3a-acadfd31c1cf.png)

but in your commit it seems that you removed these lines
![image](https://user-images.githubusercontent.com/11553585/41409646-2c8f4a14-6fd7-11e8-8eb6-07a7967c8810.png)

**Comment by jkasten2** [comment]
Sorry for the delay on this. We just released this update about 12 hours ago in [release 150300](https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/150300). If you are still seeing this error you will need clear or disable your browser's cache. If you enter `OneSignal.VERSION` in the console in your browser you should see `150300` to confirm you are testing this version.

@rezakeramati The lines below were broken up, they we just moved just to make this code clearer and easier to setup a unit test for this issue. The [main fix](https://github.com/OneSignal/OneSignal-Website-SDK/pull/369/files#diff-fb80f661e12c1fed41f03bc99cf50ad8R344) was moving the `undefined` check to the private function from the public one.

**Comment by rezakeramati** [comment]
@jkasten2 Thanks for your attention. The problem is solved now after clearing browser cache.
