### ISSUE TITLE
Best way to update custom service worker

### ISSUE THREAD

**Issue by luisherranz** [OneSignal/OneSignal-Website-SDK#366]
**Description:**

We need to be able to update our SW when a new version is published, like you do with your library.

I saw an issue where another person suggests to add a hash to the `OneSignalSDKWorker.js` file, like this:
```js
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDK.js');
importScripts('/service-worker.B2Y-9zM2x.js');
```

Unfortunately, we can't update the `OneSignalSDKWorker.js` file to add a hash because that file can be aggresively cached (we don't control the cache). So we need an alternative.

From what I read from this comment:
https://github.com/OneSignal/OneSignal-Website-SDK/blob/a89198a7d316e88c5ce2f915b52f81f5753ee0b5/src/managers/ServiceWorkerManager.ts#L333-L336

Looks like now, because of AMP web push, only `OneSignalSDKWorker.js` is installed, with an `appId` query. To update, you install `OneSignalSDKUpdaterWorker.js` and then install `OneSignalSDKWorker.js` again, is that right?.

If so, I want to know if this solution works well when we detect a new version of our SW:

```js
if (currentVersion !== installedVersion) {
  // There's a new version of our Service Worker
  const appId = await OneSignal.getUserId();
  try {
    await navigator.serviceWorker.register(`/OneSignalSDKUpdaterWorker.js.php?appId=${appId}`);
    // Registration of OneSignalSDKUpdaterWorker succeed, go back to OneSignalSDKWorker
    await navigator.serviceWorker.register(`/OneSignalSDKWorker.js.php?appId=${appId}`);
    // Update succeed
  } catch (error) {
    // update failed
    console.log('Registration failed with ' + error);
  }
}
```

Thanks in advance!

**Comment by luisherranz** [comment]
Actually, that code doesn't update the Service Worker, it fails, don't know why.

But this one does:

```js
await navigator.serviceWorker.register(`/OneSignalSDKUpdaterWorker.js.php?appId=${appId}`);
await new Promise(resolve => setTimeout(resolve, 1));
await navigator.serviceWorker.register(`/OneSignalSDKWorker.js.php?appId=${appId}`);
```

**Comment by luisherranz** [comment]
I finally used `oncontrollerchange` to wait between SW installations:

```js
const onControllerChange = new Promise(resolve => { 
  window.navigator.serviceWorker.oncontrollerchange = resolve; 
});

await navigator.serviceWorker.register(`/OneSignalSDKUpdaterWorker.js.php?appId=${appId}`);
await onControllerChange();
await navigator.serviceWorker.register(`/OneSignalSDKWorker.js.php?appId=${appId}`);
```

**Comment by jkasten2** [comment]
@luisherranz If it is ok for your service worker 24 hours old or less than just changing the service worker contains will be enough. Service workers ignore any local cache settings. See this post for more details on this.
https://stackoverflow.com/a/38854905/1244574

If you must load the service work right away then the service worker just needs to be a different name. You shouldn't load one service worker right after another. It will work but then the browser is doing an extra request to load one service worker than another to replace it.

**Comment by luisherranz** [comment]
Thanks for your answer @jkasten2.

> If it is ok for your service worker 24 hours old or less than just changing the service worker contains will be enough.

As I said in the opening post, we don't control the service worker file and it may be aggresively cached:
*Unfortunately, we can't update the OneSignalSDKWorker.js file to add a hash because that file can be aggresively cached (we don't control the cache). So we need an alternative.*


> If you must load the service work right away then the service worker just needs to be a different name. You shouldn't load one service worker right after another. It will work but then the browser is doing an extra request to load one service worker than another to replace it right away

Isn't that exactly what you guys are doing? Explained here:
https://github.com/OneSignal/OneSignal-Website-SDK/blob/a89198a7d316e88c5ce2f915b52f81f5753ee0b5/src/managers/ServiceWorkerManager.ts#L333-L336

**Comment by jkasten2** [comment]
@luisherranz Just to confirm, you are not in control of the service side caching? You don't have a way to clear this on your host / cdn? Just to confirm, the client side cache setting does not apply to service workers.

The issue with changing the service worker file name each time you make an update is if someone does not come back to your site the service worker will never be updated. This means when OneSignal makes feature updated or bug fixes to the service worker they will not be updated in this case.
**Unless** you keep **EVERY** hash variant you have ever created available going forward.

If these limitation are ok then you can tell the OneSignal SDK to use a custom name. 
Example:
```javascript
OneSignal.SERVICE_WORKER_PATH = "OneSignalSDKWorker_HASH.js";
OneSignal.SERVICE_WORKER_UPDATER_PATH = "OneSignalSDKUpdaterWorker_HASH.js"
```

**Comment by luisherranz** [comment]
> Just to confirm, you are not in control of the service side caching? You don't have a way to clear this on your host / cdn?

Yes, that's it. We are working on a WordPress plugin and we don't control how our users cache their sites. Some of them use cache plugins, others use varnish, others use cdns... The service-worker file can be aggresively cached on their side so we can't rely on it.

We are using the same approach than you, include an `importScript` in the .php file which generates the `service-worker.js` file. If OneSignal is installed, we are also including `OneSignalSDK.js` because we want our plugin to be compatible with yours. We are also populating `window.OneSignal` with the correct names and paths to our files, so OneSignal can also update itself.

> Also just want to repeat, the client side cache setting does not apply to service workers, they are always set to 24 hours.

The problem is, browsers only look at changes in the top file (`service-worker.js`) and not in the imported scripts (OneSignalSDK and our plugin SDK). As I explained above, we can't depend on a change of the top file because it may be cached.

> The issue with changing the service worker file name each time you make an update is if someone does not come back to your site the service worker will never be updated. This means when OneSignal makes feature updated or bug fixes to the service worker they will not be updated in this case.

Could you please explain this part with more detail? I'm not sure I got it.

----

Our strategy right now is: 
- Expose the current SDK build hash in an endpoint
- Install `OneSignalSDKWorker.js?appId=...` if user doesn't have a service worker installed and save the current hash in `localStorage`.
- If user have a sw installed but the endpoint hash is different from the localStorage hash, install `OneSignalSDKUpdaterWorker.js?appId=...` first, then install `OneSignalSDKWorker.js?appId=...` again.

We chose this strategy because we read this comment in your SDK code:
https://github.com/OneSignal/OneSignal-Website-SDK/blob/a89198a7d316e88c5ce2f915b52f81f5753ee0b5/src/managers/ServiceWorkerManager.ts#L294-L337

**Comment by jkasten2** [comment]
@luisherranz 

>>The issue with changing the service worker file name each time you make an update is if someone does not come back to your site the service worker will never be updated. This means when OneSignal makes feature updated or bug fixes to the service worker they will not be updated in this case.

> Could you please explain this part with more detail? I'm not sure I got it.

This applies if you will be using a unique hash in the file name each time you update the service work. Example if you do `navigator.serviceWorker.register("OneSignalSDKWorker_HASH.js?appId=...")` then you should always keep the exact file around. If you can use a query param to do catch breaking on your end this will be better. Example `navigator.serviceWorker.register("OneSignalSDKWorker.js?hash=...&appId=...")`

**Comment by luisherranz** [comment]
I thought the filename or query parameters of the service worker path must not be changed because if you do, AMP web push stops working:
https://github.com/OneSignal/OneSignal-Website-SDK/blob/a89198a7d316e88c5ce2f915b52f81f5753ee0b5/src/managers/ServiceWorkerManager.ts#L305-L328

Precisely here:

> Actually, users can customize the file names of Worker A / Worker B, but it's up to them to be consistent with their naming. For AMP web push, users can specify the full string to expect for the service worker. They can add additional query parameters, but this must then stay consistent.

I understand that the filename and query parameters of the installed service worker should be always the same. If that's true, we shouldn't be using a hash query parameter to update it, should we?

**Comment by jkasten2** [comment]
@luisherranz Sorry for the confusion, you are correct that using a hashed name in the query param or file name won't work for AMP. I don't believe it will be possible to support this.

The only way I can see solve your issue is to look into trying to clear your server side caching of these files.

**Comment by luisherranz** [comment]
Ok, Thanks for your help @jkasten2!

I guess we'll stick to the "install B then install A again" approach you do here:
https://github.com/OneSignal/OneSignal-Website-SDK/blob/a89198a7d316e88c5ce2f915b52f81f5753ee0b5/src/managers/ServiceWorkerManager.ts#L333-L336

I hope this will be solved once WP has a proper service worker API in its core :)
