### ISSUE TITLE
Failed to subscribe in China

### ISSUE THREAD

**Issue by torghay** [OneSignal/OneSignal-Website-SDK#367]
For chrome (cannot request fcm in China for special reasons, but can receive fcm notification):
I use onesignal sdk in China and the target users are all in China. I think the subscription notification doesn't need to request an fcm, but if I use a proxy to access google, I can use onesignal sdk to subscribe to notifications. If I don't use a proxy, I can't subscribe with onesignal sdk. Why do I use onesignal sdk also need to request google, Trouble answer below, thank you

---Translation with Google, please ignore grammatical errors

**Comment by torghay** [comment]
After agreeing to "show notification", subscription notification (registration of device to onesignal) failed

**Comment by jkasten2** [comment]
@torghay To subscribe or receive notifications in Chrome you must be able to access Google's server. However all requests to Google are block in mainland China so push notification in Chrome will not work there. Unless the Chrome version from https://www.google.cn/chrome/ has a different push server subscription I am not aware of I don't believe Chrome push will work there. It seems that some in China can download Chrome from this URL from some ISPs according to [this post](https://www.quora.com/How-can-I-install-the-latest-Chrome-browser-in-China)

You can visit `chrome://gcm-internals/` in Chrome and check "GCM Client State"?

**Comment by torghay** [comment]
Thank you, and finally understand that there is currently no way to use onesignal

**Comment by torghay** [comment]
@jkasten2 Yes, Firefox and Safari can normally use onesignal. Unfortunately, their usage rate is not high. Domestic browsers do not support service worker.

**Comment by ivanzhang** [comment]
any way to config onesignal to register on proxy?   we can provide self hosted proxy to make sdk access FCM in client javascript ?
