### ISSUE TITLE
ReactJS Web app + OneSignal web push

### ISSUE THREAD

**Issue by franj0** [OneSignal/OneSignal-Website-SDK#372]
**Description:**

Hi guys,

I have mobile application with One Signal notifications and everything works fine.
So now I'm created admin panel for that mobile apps. 
In my web admin panel I need web push notifications so I used OneSignal web push to configure into admin panel. And it seems I'm configure correct regarding documentation. Also I tried send new push from OS site and that web push notification appear on my browser - works fine.

I'm already sending push notifications to mobile apps from my API and works fine, 
but when I want send web push notification to my browser I'm getting error.

My question is, how can I send web push notification programmatically from my API.

This function working for playerIDs(mobile) from OS site, but for web browsers not working.
![image](https://user-images.githubusercontent.com/11553585/41534732-ce9d4a38-72ff-11e8-946f-0248996a896d.png)

```
 OneSignal returned those error messages:
 Incorrect player_id format in include_player_ids (not a valid UUID): 8a34c878-9afd-4ffc-bd18-ccd491e20264
```

sry for bad eng :)

Web app is ReactJS
API is golang + gin gonic

**Comment by jkasten2** [comment]
@franj0 Thanks for the details and sharing your code. Can you print out `deviceIDs` from your code to make sure it isn't blank, `nil`, or contains any invalid UUID?

Note that `include_player_ids` is an array, even if you pass one value to must be wrapped in an array.

**Comment by franj0** [comment]
@jkasten2 thanks for interesting in this case.

Yeah, I'm already printed array of deviceIDs and get this. 

![image](https://user-images.githubusercontent.com/11553585/41554144-38c5b006-7334-11e8-9c1a-63d9029f9d4d.png)

**Comment by jkasten2** [comment]
@franj0 Can you print out the full JSON being sent to OneSignal as well as the HTTP headers you are sending?

**Comment by franj0** [comment]
I can print only these things:

```
{
    "DeviceIDS": [
        "453d779e-631d-41da-ab8e-2c3e552aa289",
        "8a34c878-9afd-4ffc-bd18-ccd491e20264\t"
    ],
    "ErrorResponse": {
        "errors": [
            "Incorrect player_id format in include_player_ids (not a valid UUID): 8a34c878-9afd-4ffc-bd18-ccd491e20264\t"
        ]
    },
    "OneSignalRequest": {
        "app_id": "there is my app id and I check it, it's correct",
        "contents": {
            "en": "WEB PUSH NOTIFICATION TEST"
        },
        "include_player_ids": [
            "453d779e-631d-41da-ab8e-2c3e552aa289",
            "8a34c878-9afd-4ffc-bd18-ccd491e20264\t"
        ]
    },
    "OneSignalResponse": null,
    "status": 200
}
```

**Comment by jkasten2** [comment]
@franj0 Thanks, I see a `\t` on the 2nd id which would cause that error. It should work after you strip it out

**Comment by franj0** [comment]
@jkasten2  Yeah, thanks, it's working

F*** me, copy paste is mother of errors.
I copied deviceID form OS site to my DB manuallly and paste was with 1-tab(4 spaces)

![image](https://user-images.githubusercontent.com/11553585/41556281-92ebf094-733a-11e8-8465-318110c86964.png)

**Comment by jkasten2** [comment]
@franj0 Glad I could help hunt down the error! Marking this ticket as resolved

**Comment by samanthakem** [comment]
@franj0 I am building a dashboard for an existing mobile app as well and I want to use OneSignal however I have no clue from where to start. The stack I am using is reactjs for the dash, android for the mobile app and nodejs for the api. Could you help me? If so, my e-mail is samanthakem@gmail.com, feel free to send me an e-mail or reach me through hangouts.

**Comment by franj0** [comment]
@samanthakem hi, I'll check is there any changes to implement web push. If not, I'll contact you on email, but nothing before tomorrow.

**Comment by franj0** [comment]
@samanthakem also, while you waiting me, try it with their documentation
https://documentation.onesignal.com/docs/web-push-quickstart
