### ISSUE TITLE
Disable Error "SdkInitErrorKind.WrongSiteUrl" on Custom installations

### ISSUE THREAD

**Issue by tixastronauta** [OneSignal/OneSignal-Website-SDK#374]
**Description:**

On **custom installations** we should be able to use the JS SDK without the `SdkInitErrorKind.WrongSiteUrl` error being raised.

From what I can tell, this behaviour was firs introduced here: https://github.com/OneSignal/OneSignal-Website-SDK/commit/4ce2b582593664f3a76a39fb09ca654e98f3eb10

In the past, we were able to use an app's JS in a different domain without any warnings/errors while keeping all the functionalities intact.

**Steps to Reproduce Issue:**

1. Create a Custom App with domain `subdomain.domain.com`
2. Now follow the installation procedures on a different domain, such as `domain2.com`
3. The error `SdkInitErrorKind.WrongSiteUrl` occurs and further script execution is prevented

**Anything else:**

Another way of solving this problem is to allow us to edit the App's "Site URL" on OneSignal's backend.

**Comment by fatsjohonimahnn** [comment]
Thank you for the input, our product team is still looking into adding this feature back or perhaps setting up our configuration in a way that will allow it for certain circumstances.
