### ISSUE TITLE
subscriptionChange event not firing when unsuscribe

### ISSUE THREAD

**Issue by rince1990** [OneSignal/OneSignal-Website-SDK#376]
**Description:**

The event subscriptionChange only fires the first time per page that the user changes the subscription and only if the subscriptions is changed to true.

**Steps to Reproduce Issue:**

1. Enter into my webpage
2. Wait for prompt to appear ( lets assume i'm already registered and suscribed)
3. click on the red bell to unsuscribe
4. The unsuscribe is completed succesfully (I confirm that in the one signal webpage) but the event doesn't fire ( it doesn't show anything on the console log).
5.I subscribed again, nothing with the event fires, but it suscribed to one signal
6.Refresh the page, the bell shows to unsuscribe and when i do the event doesnt fire, but it still works with oneSingal
7.Refresh the page again, hit the suscribe button, THE EVENT FIRES, and the console log shows "The user's subscription state is now: True"

**Anything else:**

To clarify:
as it is a bit mess ill try to say it in this way
```
if (first time making subscription in the page){
      if(isSubscribed = true){
           Launch the event
      }else //isSubscribed=false
           NO launch event
}else {//!first time making subscription in the page
      NO launch event
}
```

The code that Im using to see the event is the one in the SDK page
https://documentation.onesignal.com/docs/web-push-sdk#section-subscription-change
```
OneSignal.push(function() {
  // Occurs when the user's subscription changes to a new value.
  OneSignal.on('subscriptionChange', function (isSubscribed) {
    console.log("The user's subscription state is now:", isSubscribed);
  });
});
```

**Comment by tristanleboss** [comment]
This is maybe linked to https://github.com/OneSignal/OneSignal-Website-SDK/issues/345

This is really anoying.

**Comment by rince1990** [comment]
Yes  @tristanleboss ... seems to be the same... I searched for this bug here and I couldn't find it, I'll have to improve my search skills. Anyways, I think I should now delete this, but I will let the admins to decide it, so feel free to delete this  as its a duplicate of the #345

**Comment by fatsjohonimahnn** [comment]
Thanks, we are aware of this and will look into pushing it up on our features list.
