### ISSUE TITLE
Unhandled Promise Rejection on Safari

### ISSUE THREAD

**Issue by Krystus** [OneSignal/OneSignal-Website-SDK#380]
I can't get to work OneSignal on Safari. Chrome and Firefox works well.

Tested on production url too but the same result. Always something with Unhandled Promise Rejection.

![screen shot 2018-07-13 at 02 13 50](https://user-images.githubusercontent.com/15039636/42666034-c186672a-8642-11e8-89b1-6ce97e9e05a0.png)

![screen shot 2018-07-13 at 02 14 59](https://user-images.githubusercontent.com/15039636/42666035-c40624a4-8642-11e8-8d61-afe9e4db6ab3.png)

**Comment by jkasten2** [comment]
@Krystus Thanks for reporting, we will look into it and get back to you.

**Comment by fatsjohonimahnn** [comment]
@krystus Please contact OneSignal support with your app ID and the link to this Github issue so we can further assist.

**Comment by jkasten2** [comment]
@Krystus This is now fixed in the latest SDK released today
