### ISSUE TITLE
CDN request OneSignalSDK.j add CORS Access-Control-Allow-Origin header For PWA service workers ?

### ISSUE THREAD

**Issue by centminmod** [OneSignal/OneSignal-Website-SDK#384]
**Description:**

I am using OneSignal on an existing web site and new to using PWA but I am converting to a Progressive Web App (PWA) via [Workbox](https://developers.google.com/web/tools/workbox/) and referencing OneSignal CDN request `https://cdn.onesignal.com/sdks/OneSignalSDK.js` in the site ends up with Workbox service worker determining the CDN request is an opaque response and ends up with Chrome padding the response size to 7MB as outlined at https://cloudfour.com/thinks/when-7-kb-equals-7-mb/ causing browser cache bloat.

>  Opaque responses are responses that the browser receives from untrusted origins. Because the origin is not trusted, exposing any information about the response to JavaScript—the size, the response code, etc.— could create a security hole. Browsers obfuscate details about the response which makes them opaque.

The fix is to have a proper CORS header added

> One reason a fetch request to a cross-origin resource can return an opaque response is not having the proper Cross-Origin Resource Sharing (CORS) HTTP response header. 

```
Access-Control-Allow-Origin: *
```

The current CDN request doesn't have that header

```
curl -I https://cdn.onesignal.com/sdks/OneSignalSDK.js
HTTP/1.1 200 OK
Date: Mon, 23 Jul 2018 00:19:27 GMT
Content-Type: application/javascript
Content-Length: 331338
Connection: keep-alive
Set-Cookie: __cfduid=d667474e69e56d1731af07849f973c5d11532305167; expires=Tue, 23-Jul-19 00:19:27 GMT; path=/; domain=.onesignal.com; HttpOnly
Last-Modified: Thu, 19 Jul 2018 20:18:19 GMT
ETag: "5b50f20b-50e4a"
CF-Cache-Status: HIT
Expires: Thu, 26 Jul 2018 00:19:27 GMT
Cache-Control: public, max-age=259200
Accept-Ranges: bytes
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 43e9f9c14b379607-SJC
```

**Steps to Reproduce Issue:**

  1. Setup a index.html html page referring the CDN request `https://cdn.onesignal.com/sdks/OneSignalSDK.js` and necessarily onesign web push setup code

```
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async></script>
```

add to html page to register `sw.js` service worker file

```
<script>
// Check that service workers are registered
if ('serviceWorker' in navigator) {
  // Use the window load event to keep the page load performant
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js');
  });
}
</script>
```

  2. Setup Workbox service worker https://developers.google.com/web/tools/workbox/guides/get-started

create `sw.js` in same directory as index.html html page with contents

```
importScripts('https://storage.googleapis.com/workbox-cdn/releases/3.4.1/workbox-sw.js');

if (workbox) {
  console.log(`Yay! Workbox is loaded`);
} else {
  console.log(`Boo! Workbox didn't load`);
}

workbox.setConfig({
  debug: true
});

workbox.routing.registerRoute(
  // Cache JS files
  new RegExp('.*\.js'),
  workbox.strategies.staleWhileRevalidate({
    // Use a custom cache name
    cacheName: 'js-cache',
    plugins: [
      new workbox.expiration.Plugin({
        // Cache only 200 images
        maxEntries: 200,
        // Cache for a maximum of a week
        maxAgeSeconds: 14 * 24 * 60 * 60,
        // Automatically cleanup if quota is exceeded.
        purgeOnQuotaError: true,
      })
    ],
  })
);
```

  3. Visit index.html page in Chrome browser and reload page once and then check dev tools -> application under Clear Storage and Cache storage check  `js-cache` cache and the size of the cache. Size is padded for the opaque response and larger than needed.

**Comment by fatsjohonimahnn** [comment]
Our service workers OneSignalSDKWorker.js and OneSignalSDKUpdaterWorker.js overwrite other service workers that are registered with the topmost (site root) service worker scope. Please import your other service workers into our service worker.

We recommend this approach because our web SDK kicks out other workers that are registered on the root scope and replaces it with our files.
