### ISSUE TITLE
Woocommerce Zapier feed for targeted user

### ISSUE THREAD

**Issue by Aminericher** [OneSignal/OneSignal-Website-SDK#386]
Hall, I want to create a notification push using zapier feed integration for a woocmmerce event (change order status). The problem is that the notification is sent for all subscribed users. I don t need that since not all users are interested in the change of the status of the orders of of other users. How is it possible to filter the recipient with only the user that I have changed his order ?

By the way I am using an Android SDK notification.

Thank you in advance.

**Comment by fatsjohonimahnn** [comment]
Please contact OneSignal support and provide the app ID and this Github issue url for more detailed support.
