### ISSUE TITLE
Chrome: only secure origins are allowed

### ISSUE THREAD

**Issue by WichardRiezebos** [OneSignal/OneSignal-Website-SDK#391]
**Description:**

Apparently since this morning (after the release of 150401) my integration with OneSignal failed:
`Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).`

**Steps to Reproduce Issue:**

  1. Visit http://groothuisbouw.info on chrome
  2. Open console 
  3. View the error

**Anything else:**

**Comment by jkasten2** [comment]
@WichardRiezebos Thanks for reporting this issue. This is now fixed and has been release in version [150402](https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/150402)
