### ISSUE TITLE
Service worker not installing on Firebase

### ISSUE THREAD

**Issue by rajatkhare619** [OneSignal/OneSignal-Website-SDK#397]
**Description:**

One Signal is working fine on my localhost but after deploying the app on Firebase, I'm getting these errors:

The script has an unsupported MIME type ('text/html').

Failed to load resource: net::ERR_INSECURE_RESPONSE

ServiceWorkerManager.js:441 [Service Worker Installation] Installing service worker failed SecurityError: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').

**Steps to Reproduce Issue:**

 1. Visit https://reminder619.firebaseapp.com/addreminder.
  2. Click on the "How do you want to be reminded?" dropdown and select "Browser notification".
  2. Wait for prompt to appear.
  3. Click Allow.
  4. Observe the errors in the console.

**Anything else:**

Attaching a screenshot here

![onesignal](https://user-images.githubusercontent.com/4737358/44706259-a85d6000-aabe-11e8-86dc-1d5cad23777e.PNG)

I need help in fixing this issue.
I already tried downloading OneSignalSDK.js locally and referencing it in the index.html file. That didn't help.

**Comment by jkasten2** [comment]
@rajatkhare619 You have selected the OneSignal HTTPS setup but the following URLs are not accessible from your site;
* https://reminder619.firebaseapp.com/OneSignalSDKWorker.js
* https://reminder619.firebaseapp.com/OneSignalSDKUpdaterWorker.js

Please upload the correct files to your site noted here;
https://documentation.onesignal.com/docs/web-push-typical-setup#section--span-class-step-step-6-span-upload-onesignal-sdk

**Comment by rajatkhare619** [comment]
@jkasten2 Thank you! That worked.
