### ISSUE TITLE
Subscription error on showHttpPrompt

### ISSUE THREAD

**Issue by michaelgavan** [OneSignal/OneSignal-Website-SDK#398]
Hi I am trying to implement the showHttpPrompt but I keep on getting subscription error.
Please help. 

Case 1: I have unsubsribed to one signal and test showHttpPromt.

Uncaught (in promise) Error: The user has manually opted out of receiving of notifications. This operation can only be performed after the user is fully resubscribed.

Case 2: I have subscribed to one signal and test showHttpPromt.

Uncaught (in promise) Error: This operation can only be performed when the user is not subscribed.

Here is my code:

OneSignal.push(function() {
    OneSignal.init({
        appId: "app_id",
        autoRegister: false,
        notifyButton: {
            enable: true,
        },
        welcomeNotification: {
            "title": "My Custom Title",
            "message": "Thanks for subscribing!",
            // "url": "" /* Leave commented for the notification to not open a window on Chrome and Firefox (on Safari, it opens to your webpage) */
          },
          promptOptions: {
            /* actionMessage limited to 90 characters */
            actionMessage: "We'd like to show you notifications for the latest news and updates.",
            /* acceptButtonText limited to 15 characters */
            acceptButtonText: "ALLOW",
            /* cancelButtonText limited to 15 characters */
            cancelButtonText: "NO THANKS"
          }
    });

    OneSignal.showHttpPrompt();

    OneSignal.on('subscriptionChange', function(isSubscribed) {
        OneSignal.getUserId(function(userId) {
            if (isSubscribed) {
                _this.addDevice(userId);
            } else {
                _this.removeDevice(userId);
            }
        });
        
    });
    
});

**Comment by jkasten2** [comment]
@michaelgavan 
**Case 1**
The error you listed means the user has clicked on the OneSignal bell icon and clicked unsubscribed.
```
The user has manually opted out of receiving of notifications. This operation can only be performed after the user is fully resubscribed.
```
Or if you have called `OneSignal.setSubscription(false);` you will also see this error.

**Case 2**
The following means `OneSignal.showHttpPrompt();` was called but the user is already subscribed so the error is letting you know it had no effect.
```
This operation can only be performed when the user is not subscribed.
```

**Detecting If Subscribed**
If you want know if the user is subscribed you can call [`isPushNotificationsEnabled`](https://documentation.onesignal.com/docs/web-push-sdk#section--ispushnotificationsenabled-) and take an action based on this.

**Comment by rgomezp** [comment]
Closing due to no response
