### ISSUE TITLE
Change the Service Worker domain to make requests to your own CDN

### ISSUE THREAD

**Issue by airkoko** [OneSignal/OneSignal-Website-SDK#399]
There are peaks of requests on my server due to access to the OneSignalSDKWorker.js and OneSignalSDKUpdaterWorker.js files.

According to OneSignal documentation, you can only specify a subfolder to change the path to these files, but I need to change the domain to attack the CDN of the page. 
For example: www.example.com -> assets.example.com.

Is this possible?

Thank you

**Comment by itrush** [comment]
Hi @airkoko, for a service worker to control your site it should be served from the same domain for security reasons. That's why our documentation instructs you to upload the service worker files to the root folder.
