### ISSUE TITLE
Add the __initAlreadyCalled global var in the doc :D

### ISSUE THREAD

**Issue by fouzko** [OneSignal/OneSignal-Website-SDK#402]
Maybe you should add __initAlreadyCalled gobal var in the doc ?!

**Comment by itrush** [comment]
It intentionally has those underscores to indicate that it's an internal one. For stuff in the documentation we make sure that we keep it for backwards compatibility. I wouldn't promise for this one to exist forever. Please don't rely on its presence in your code.
