### ISSUE TITLE
Chrome 69 disabled notification

### ISSUE THREAD

**Issue by tthdvd** [OneSignal/OneSignal-Website-SDK#404]
**Description:**

After we updated the chrome to 69 version, on websites with only http the notification is disabled and it's does not work. Nothing shows up (include the onesignal notification accept modal).  It's a little problem, our master site is https, only in local development server we use http. 
The main problem is that when we use the isPushNotificationsEnabled() function nothing response goes back. 

**Steps to Reproduce Issue:**

1. open an http site
2. set up OneSignal
3. use isPushNotificationsEnabled function, nothing response.

**Comment by itrush** [comment]
@tthdvd Investigating. Will keep you posted.

**Comment by itrush** [comment]
Seems to working again as normal. Just remember to clear browser cache. OneSignal.VERSION should help verify if you're on the latest one.

**Comment by tthdvd** [comment]
Thank you guys! :)
