### ISSUE TITLE
OneSignal completely failing in Chrome, but working in FF & Safari

### ISSUE THREAD

**Issue by slothstronaut** [OneSignal/OneSignal-Website-SDK#406]
**Description:**

I'm not sure when this started, but its been going on for awhile. I haven't changed anything with my OneSignal integration in a long time, but Chrome no longer works on desktop or mobile, and gets the following error:

[Violation] Only request notification permission in response to a user gesture.
SubscriptionManager.js:183 [Violation] Only request notification permission in response to a user gesture.
(anonymous)	@	SubscriptionManager.js:183
e.requestNotificationPermission	@	SubscriptionManager.js:183
(anonymous)	@	SubscriptionManager.js:154
(anonymous)	@	CookieSyncer.js:2
(anonymous)	@	CookieSyncer.js:2
(anonymous)	@	CookieSyncer.js:2
i	@	CookieSyncer.js:2
e.requestPresubscribeNotificationPermission	@	SubscriptionManager.js:153
(anonymous)	@	SubscriptionManager.js:265
(anonymous)	@	CookieSyncer.js:2
(anonymous)	@	CookieSyncer.js:2
s	@	CookieSyncer.js:2

I track user agents in my DB and FF and Safari users are able to enable push permission, but no Chrome users are able to. I'm guessing I need to setup a custom integration, and the default autoRegister way of the past is no longer working in Chrome, but wanted to confirm this first, and see if perhaps I'm doing something wrong first.

I've actually tried setting autoRegister: false with the <div class='onesignal-customlink-container'></div> instead, and it gives the same exact error message.

**Steps to Reproduce Issue:**

Steps to reproduce (in Chrome):

1) Navigate to: https://findmate.app/info/test/onesignal.html
2) Open debug console
3) Wait for permission prompt, notice violation error in console
4) Notice that notification permissions are thereafter blocked in the permissions for the site as a whole

**Comment by itrush** [comment]
Hi. I tested in Chrome 69 and Chrome 64 desktop and didn't see any errors like you've described. What error message says, that there was no user interaction. Clicking on a prompt is considered interaction. Did you have any custom code in place requesting a user permission? What is the userAgent string in your browser?

**Comment by slothstronaut** [comment]
It seems to be working now using the custom link. The autoregister method seems to be completely blocked now in Chrome. Thanks for checking.
