### ISSUE TITLE
Allow 3d party SW to keep `skipWaiting` and `claimClients` disabled while using OneSignal

### ISSUE THREAD

**Issue by Sturgelose** [OneSignal/OneSignal-Website-SDK#407]
**Description:**

OneSignal SDK Service Worker is forcing custom SW to skipWaiting and claim clients.
As a user, I'd like to notify a user before reloading the service worker as rebooting their page without warning can be harmful for the user experience.

In our custom service worker, written using workbox (we have a PWA in Angular), we have claim clients and skipWaiting disable.
We would like to keep it disabled without allowing onesignal to forcing it, as we ask the user to reload the page beforehand, in a notification, where we also update users about the new features.

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(any other information here)

**Comment by Sturgelose** [comment]
Hi,

I did some research in this repository today and it kinda looked as if `skipWaiting` and `clients.claimClients` are only being used over here (in the service worker code): https://github.com/OneSignal/OneSignal-Website-SDK/blob/e530384b72bc69b1741112f05d55d55ec07fd704/src/service-worker/ServiceWorker.ts#L779

I used git-blame and did some code reading to find that the legacy events that still exist (if they do) are: https://github.com/OneSignal/OneSignal-Website-SDK/blob/e530384b72bc69b1741112f05d55d55ec07fd704/src/Event.ts#L49

```
const LEGACY_EVENT_MAP = {
	  'notificationPermissionChange': 'onesignal.prompt.native.permissionchanged',	  
          'subscriptionChange': 'onesignal.subscription.changed',
          'customPromptClick': 'onesignal.prompt.custom.clicked',
}
```

According to the SW logic, if we are updating the service worker, and we do not trigger the skipWaiting and clients.claimClients, the website will keep on working using the latest installed SW, which, should not break how OneSignal works.

Also, the objective of this improvement is to at least be able to warn the user if we are updating the service worker, as otherwise, the webpage may flash a couple of times if we are also loading our own SW, breaking the User Experience.

So, I guess that, not calling this two events shouldn't break anything the app. Anyways, I cannot try it in local, mostly because I do not see any dev guide on how to test or build it locally. I took a peek in the package.json scripts, but anyways, I do not have the time to dedicate to research all this.

Any chance to give advice on how to try it, or at least put those two calls behind a flag (and I call them few seconds later when the user presses a button, or will be done by itself when the user refreshes the page?)

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration

**Comment by novaknole** [comment]
@Sturgelose Hi , How have you ended up? I have the same issue. Removing `skipwaiting` and `clientsclaim` from those lines? do they end up dangerous? or I can remove them?  I completely agree that removing them shouldn't affect anything, but still curious if it happened to be dangerous along the way? Any ideas?
