### ISSUE TITLE
"This site has been updated in the background" - Windows 10 Chrome

### ISSUE THREAD

**Issue by jviral** [OneSignal/OneSignal-Website-SDK#412]
**Description:**
Sometimes notifications show "This site has been updated in the background." instead of their content. Also, some times notifications are not clickable when multiple notifications are shown.

![](https://i.imgur.com/a4zHRfh.png)

**Steps to Reproduce Issue:**

1. Subscribe to a website that frequently sends notifications on Windows 10 Chrome (I used producthunt)
2. Power off the machine a few days (I used Virtual Box)
3. When you turn on the machine again, sometimes the error occurs

**Anything else:**

Almost all of the time most notifications on Windows 10 are not clickable, it appears only the last notification is clickable.

**Comment by jkasten2** [comment]
@jviral Thanks for reporting, the "This site has been updated in the background" is a default notification that Chrome shows if the servicer work does not generate a notification of it's own. However for OneSignal there isn't any know cases where a notification would never show.

The only case I could see if there was some javascript error preventing the notification. If you open a new tab to chrome://serviceworker-internals/ you can precess the Inspect button to get a javascript console in this context.
![image](https://user-images.githubusercontent.com/645861/46054360-dbb1ff80-c0fb-11e8-8fc5-83080cedf064.png)
Can you try to reproduce the issue again with this javascript console open and report back any errors? Also please run `OneSignal.VERSION` from the console so we can confirm the version you are running of the SDK.

Lastly this notification shouldn't just be a Windows 10 issue. Chrome Windows, macOS, Android, and Linux should all show this message if in the case I noted above.

For the 2nd issue of only the last notification clickable, it is expected for only the most recent notification to show per site with OneSignal. Is this display issue what you are referring to by "...it appears only the last notification is clickable."? If not what behavior do you get when you click on the notification? Does it stay around or just go away without a page showing?

**Comment by Ndekere** [comment]
Wow!! Thanks for the info... Av learnt a lot.

**Comment by FlavorPantry** [comment]
![screenshot 14171](https://user-images.githubusercontent.com/20829617/52499454-52720580-2b90-11e9-9998-eb320537c308.jpg)

I see this message frequently... just happened again this morning..

**Comment by rgomezp** [comment]
Closing due to no response from OP
