### ISSUE TITLE
Not working in Edge

### ISSUE THREAD

**Issue by alphanull** [OneSignal/OneSignal-Website-SDK#415]
**Description:**

Seems like OneSignal won't work for Edge, not even on the OneSignal Page itself.

**Steps to Reproduce Issue:**

1. Visit https://OneSignal.com
2. Click on Bell
3. Click "Allow" to enable notifications
4. Reload page and look for the bell again

**Anything else:**
The Browser Dialog to allow Notifications is shown, but it seems the user is actually never subscribed. At least the Bell won't change, as it does on another browser as I subscribe.

And of course it also does not work on the site I am currently developing. Seems to make no difference if I use the bell to subscribe or some custom implementation. On all other systems it works just fine.

This is also the latest version of Windows 10 (Microsoft Edge 42.17134.1.0). Also note that I ran this test in a VM (Parallels on macOS)

**Comment by fatsjohonimahnn** [comment]
Sorry you are running into this issue but I don't believe you can test Microsoft Edge push notifications on Parallels. You need an actual Windows 10 PC to test Microsoft Edge.

Web Push Notifications work on Windows Computers running Edge version v42.17134 / 17.17134

Otherwise, you need to test in the developer preview.

You can get developer preview as a virtual machine here https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ (last one in the drop down list)

For Mac users: http://osxdaily.com/2015/12/01/run-microsoft-edge-in-mac-os-x-virtual-machine/

**Comment by fatsjohonimahnn** [comment]
Unfortunately I am unable to reproduce this on Windows 10 Edge version v42.17134 / 17.17134

Please contact OneSignal support with your OneSignal app ID and a reference to this GitHub issue so we can take a look at your site.

**Comment by jkasten2** [comment]
@alphanull If you try to our notification preview page do you see the example notification? https://onesignal.com/webpush

I also recommend turning on SDK's logging which might uncover the issue>
https://documentation.onesignal.com/docs/troubleshooting-web-push#section-2-enable-web-sdk-logging
Feel free to post your log here

I have tested on Edge 42.17134.1.0 on Windows 10 as well without any issues. On Parallels I recommend disabling [Coherence View](https://kb.parallels.com/en/4670) for Edge as the Windows Action Center needs displayed to see the notification.

**Comment by alphanull** [comment]
> @alphanull If you try to our notification preview page do you see the example notification? https://onesignal.com/webpush

Result: "It's that easy. Get started in minutes or view another example."
But no push notification!

Coherence View is disabled. And, I have tested another PC with exact the same result. Seems that no machine in my Network works with Edge. Does Edge maybe need a special port opened in the firewall for web push? It is really strange, as it seems to work on your side. But there must be something, but what? 

Thanks for the hint with the logging, I will do that now and report back to you guys. Thanks for your help!

**Comment by alphanull** [comment]
So I enabled debugging and this is how it looks like when I open the page where the user can subscribe:

```
 isPushNotificationsEnabledVerbose()
notifications.2.0.158.js (17,401)

 Called isPushNotificationsSupported() .
utils.js (201,5)

 Called isPushNotificationsEnabled() .
utils.js (201,5)

 Called getUserId() .
utils.js (201,5)

 Called getRegistrationId() .
utils.js (201,5)

 Called isOptedOut() .
utils.js (201,5)

 Called getUserId() .
utils.js (201,5)

 Called isPushNotificationsEnabled() .
utils.js (201,5)

 Called isOptedOut() .
utils.js (201,5)

 Is Completely Subscribed: false
notifications.2.0.158.js (18,271)

 {"notifyType":"consoleItemLog","message":{"message":"","styles":"","hasFormatString":true,"fileUrl":"https://************","lineNumber":18,"columnNumber":314}}
notifications.2.0.158.js (18,314)

What is our OneSignal user ID? null

What is our push subscription token? null

 What is the notification permission status? granted
notifications.2.0.158.js (18,432)

 Are you manually opted out? false
notifications.2.0.158.js (18,493)

 Is a service worker registered and active? (should be false on Safari, otherwise should be 'Worker A (Main)')? Worker A (Main)
notifications.2.0.158.js (19,4)

 What is the current URL of this page? https://************
notifications.2.0.158.js (19,132)

 What environment does OneSignal think it's in? Host
```

And this what happens when I try to enable notifications:

```
 Called isPushNotificationsEnabled() .
utils.js (201,5)

 Called isOptedOut() .
utils.js (201,5)

 Called sessionInit({"fromRegisterFor":true})
InitHelper.js (330,9)

 Called isOptedOut() .
utils.js (201,5)

 Called isPushNotificationsEnabled() .
utils.js (201,5)

 Waiting for the service worker to activate...
SubscriptionManager.js (304,36)

 Service worker is ready to continue subscribing.
SubscriptionManager.js (306,16)

[Subscription Manager] Subscribing to web push with these options: [object Object]

[object DOMException]: {code: 20, message: "AbortError", name: "AbortError"}
code: 20
message: "AbortError"
name: "AbortError"

__proto__: Object

 (Host) » initializeInternal
Event.js (56,43)
```

Not sure what to make of that. But at least we have an Error, but I have no idea what it means. Again this happens with the "bell" as well, not only with my custom code. And it also happens on the OneSignal Site itself (though I cannot confirm because I cannot enable tracing there of course), and on three different Systems (one being a VM). And only in Edge - Chrome & FF work well. Hmmm.

Any ideas?

**Comment by jkasten2** [comment]
@alphanull I don't believe that `AbortError` error is related to OneSignal. Can you try following the source from the javascript console? The file should be clickable from the console.

Can you run the following to see if Edge ended up creating a user on OneSignal?
`OneSignal.getUserId(function(id) { console.log(id); });`
If you get a UUID then it subscribed, you can send this to OneSignal support and they can take a look at the player id from their end.

If this is working and it show subscribed on OneSignal make sure the "Windows Push Notification" services are running in Windows. You can find this by running `services.msc`.
![image](https://user-images.githubusercontent.com/645861/46382432-c9861300-c65f-11e8-818a-e93379623c0f.png)

I wasn't able to find documentation on the port Edge web push from Microsoft will use but it looks like a local port of 49425-49431 and a remote port of 443 over TCP when I used TCPView to inspect.

**Comment by alphanull** [comment]
@jkasten2 as it seems no user id is ever assigned. I also do not see this browser in the users list on the OneSignal dashboard. However a collegue of mine was sucessfully able to subscribe. So it really seems there is something wrong with my environment. What baffles me is that I have the same symptoms on totally different systems. Firewall already ruled out - i.e. same thing when I turn it off. Service is running as well.

**Comment by alphanull** [comment]
Any ideas? Also updating to 1809 just yesterday made no apparent difference

**Comment by alphanull** [comment]
FYI: I also took my network / router out of the equation and connected my machine via tethering to my mobile network. Problem remains, same goes for #417

**Comment by rgomezp** [comment]
Hello @alphanull ,
Did you make any progress on this issue?

**Comment by rgomezp** [comment]
Closing due to no response
