### ISSUE TITLE
A bad HTTP response code (404) was received when fetching the script. Failed to load resource: net::ERR_INVALID_RESPONSE

### ISSUE THREAD

**Issue by Jotapee93** [OneSignal/OneSignal-Website-SDK#419]
hola buenas tardes, he realizado la actualización de una aplicación con las actualizaciones mas resientes del angular pero todo se desajusto y se movió, pensé que era un tema de bootstrap , popper o Jqery pero, no entiendo muy bien a pesar importar bien o hay algo que me falta en la nueva versión? .
  
*este es el mensaje que me sale.
A bad HTTP response code (404) was received when fetching the script.
Failed to load resource: net::ERR_INVALID_RESPONSE

___________________________________________________
y este es mi json.
"@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@auth0/angular-jwt": "^2.0.0",
    "angular2-notifications": "^1.0.4",
    "bootstrap": "^4.1.3",
    "core-js": "^2.5.4",
    "file-saver": "^2.0.0-rc.3",
    "font-awesome": "^4.7.0",
    "jquery": "^3.3.1",
    "jsencrypt": "^3.0.0-rc.1",
    "jstz": "^2.0.0",
    "moment-timezone": "^0.5.21",
    "ng": "0.0.0",
    "ng-push": "^0.2.2",
    "ngx-bootstrap": "^3.0.1",
    "popper.js": "^1.14.4",
    "primeicons": "^1.0.0-beta.10",
    "primeng": "^6.1.4",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.3.3",
    "ts-helpers": "^1.1.1",
    "zone.js": "~0.8.26"
__________________________________
   "styles": [
              "src/styles.css",
              "./node_modules/bootstrap/dist/css/bootstrap.css",
              "./node_modules/bootstrap/dist/css/bootstrap.min.css"
            ],
            "scripts": [
              "node_modules/jquery/dist/jquery.min.js",
              "node_modules/popper.js/dist/umd/popper.js",
              "node_modules/bootstrap/dist/js/bootstrap.min.js"
            ]

**Comment by Jotapee93** [comment]
![asdasdasdasdasdasdasd](https://user-images.githubusercontent.com/39116557/46749242-ea132600-cc7a-11e8-9d09-fc06fe98b88c.PNG)
dejo imagen del mensaje.

**Comment by jkasten2** [comment]
@Jotapee93 Can you provide the URL that is getting the 404 error? It is most likely the service working missing from your web server if you see this message after accepting push permissions. See this guide on fixing the issue.
https://documentation.onesignal.com/docs/troubleshooting-web-push#section-service-worker-404-and-403-errors

If you run into other issues I recommend contacting OneSignal support. Please leave you message in English as this is the only language we provide support in. Thanks.
