### ISSUE TITLE
I can't get playerID after subscription - ONE_SIGNAL_SDK_DB is empty

### ISSUE THREAD

**Issue by caciobanita** [OneSignal/OneSignal-Website-SDK#420]
**Description:**

I'm using this library in a React project. When i'm calling the init i get the player id. But on calling getUserId i get null.

This is onesignal trece on init:

> Called isPushNotificationsSupported() .
> WorkerMessenger.js:148 (http://localhost:3000) [Worker Messenger] The page is now controlled by the service worker.
> WorkerMessenger.js:151 (http://localhost:3000) [Worker Messenger] Page is now listening for messages.
> InitHelper.js:321 OneSignal: Set pageTitle to be 'Asociatie Transparent Residence'.
> InitHelper.js:280 Called internalInit()
> ServiceWorkerManager.js:184 [Service Worker Update] Checking service worker version...
> WorkerMessenger.js:108 [Worker Messenger] [Page -> SW] Unicasting 'GetWorkerVersion' to service worker.
> WorkerMessenger.js:200 [Worker Messenger] Page received message: {command: "GetWorkerVersion", payload: 150500}
> ServiceWorkerManager.js:203 [Service Worker Update] Service worker version is current at v150500 (no update required).
> SessionManager.js:66 Incremented page view count to 3.
> InitHelper.js:327 Called sessionInit({"__sdkCall":true})
> OneSignalUtils.js:85 Called isOptedOut() .
> OneSignalUtils.js:85 Called isPushNotificationsEnabled() .
> SubscriptionManager.js:308 Waiting for the service worker to activate...
> SubscriptionManager.js:310 Service worker is ready to continue subscribing.
> SubscriptionManager.js:414 [Subscription Manager] An existing push subscription exists and options is not null. Using existing options to resubscribe.
> SubscriptionManager.js:463 [Subscription Manager] Subscribing to web push with these options: PushSubscriptionOptions {userVisibleOnly: true, applicationServerKey: ArrayBuffer(65)}
> SubscriptionManager.js:122 Subscribed to web push and registered with OneSignal: t {language: "en", timezone: 10800, browserName: "Chrome", browserVersion: 69, operatingSystem: "Microsoft Windows", …}
> appId: "81d63f0f-3121-46d0-9611-c7aa645616ac"
> browserName: "Chrome"
> browserVersion: 69
> deliveryPlatform: 5
> deviceModel: "Win32"
> devicePlatform: "desktop"
> language: "en"
> operatingSystem: "Microsoft Windows"
> operatingSystemVersion: "10"
> sdkVersion: "150500"
> subscription: e {w3cEndpoint: URL, w3cP256dh: "BBYToSb91iHYRpINow5OsIFd7lhT3UYBWA6qxplsEL1fiZKgMCtPHXe2EpDLeOZJaW4FJSPUND0fgwXi3LVAENU=", w3cAuth: "cs3xoNOsMwcEbVDRXEhJsw==", existingW3cPushSubscription: e, safariDeviceToken: undefined, …}
> subscriptionState: 1
> timezone: 1080
> 

(your description here)

**Steps to Reproduce Issue:**

1. My init code:
```
OneSignal.push(["init", {
      appId: "81d63f0f-3121-46d0-9611-c7aa645616ac",
      autoRegister: false,
      notifyButton: {
        enable: false,
      },
      subdomainName: "transparent2",
      httpPermissionRequest: {
        enable: true,
      },
      promptOptions: {
        /* These prompt options values configure both the HTTP prompt and the HTTP popup. */
        /* actionMessage limited to 90 characters */
        actionMessage: "Permiteti primirea de notificari la emiterea unei facturi sau mesaj nou in chat?",
        /* acceptButtonText limited to 15 characters */
        acceptButtonText: "PERMITE",
        /* cancelButtonText limited to 15 characters */
        cancelButtonText: "NU MULTUMESC"
      },
      welcomeNotification: {
        "title": "Transparent residence",
        "message": "Va multumim pentru abonare!",
        // "url": "" /* Leave commented for the notification to not open a window on Chrome and Firefox (on Safari, it opens to your webpage) */
      },
      requiresUserPrivacyConsent: true,
      allowLocalhostAsSecureOrigin: true,
    }])
```

I'm calling provideUserConsent on button press:
 ```
userTappedProvideConsentButton = () => {
    // Will initialize the SDK and register for push notifications
    OneSignal.push(() => {
      OneSignal.provideUserConsent(true)
    });
  }
```

In OneSignal account the user subscription is created, but i can't get the user player id. If i send a notification to that player id, the notification is received.

Is Completely Subscribed: false
What is our OneSignal user ID? null
What is the notification permission status? granted
Are you manually opted out? false
isSupported? true

On calling OneSignal.setSuscription() - i get the error:
`Uncaught (in promise) Error: Missing required app ID.`

**Comment by caciobanita** [comment]
> The getUserId method will not work until after `OneSignal.provideUserConsent(true)` is called.
> 
> Try wrapping this method within the subscription change event and call this after `OneSignal.provideUserConsent(true)`
> 
> ```
> OneSignal.push(function() {
>   // Occurs when the user's subscription changes to a new value.
>   OneSignal.on('subscriptionChange', function (isSubscribed) {
>     console.log("The user's subscription state is now:", isSubscribed);
>     OneSignal.getUserId(function(userId) {
>       console.log("OneSignal User ID:", userId);
>       // (Output) OneSignal User ID: 270a35cd-4dda-4b3f-b04e-41d7463a2316    
>      });
>   });
> });
> ```
> ​
> Users only get a OneSignal playerID when they subscribe, so you can also use `isPushNotificationsEnabled` to wrap the getUserId method.

Tanks for response, but the problem is not in the implementation code, my code works great in Microsoft Edge, but ins not working in Chrome v69. After i call OneSignal.provideUserConsent(true), i get the response prom OneSignal API with playerID, but on calling another method i get this error: 

> Uncaught (in promise) Error: Missing required app ID.

After some debugging the ONE_SIGNAL_SDK_DB (in indexedDB) is empty, no appID is stored.
Is there a way to use a specific version of OneSignal WEB SDK, with version 150504 was working.

**Comment by caciobanita** [comment]
This is related https://github.com/OneSignal/OneSignal-Website-SDK/issues/335

**Comment by rgomezp** [comment]
Hey @caciobanita ,
Were you able to resolve? I don't think this is a bug. If you contact us through the support channel at OneSignal.com, we'd be happy to work with you directly and look at your specific site.

I'm closing the issue since I think this is more of a question/help than a bug.

**Comment by Ajayappnweb** [comment]
Hey, @rgomezp This is a bug with high priority, I am getting this issue on android. After deleting the user from one signal console and subscribing again from android not working, User not subscribing again at one signal.

**Comment by rgomezp** [comment]
@Ajayappnweb , I believe this is a similar but different issue. Can you please reach out through our support channel at OneSignal.com and mention you have a player update issue?
