### ISSUE TITLE
Can't receive notification after blocking and unblocking notification

### ISSUE THREAD

**Issue by dgeibi** [OneSignal/OneSignal-Website-SDK#422]
**Steps to Reproduce Issue:**

0. Open Chrome 69 (Windows 10)
1. Visit https://onesig-e3088.firebaseapp.com/xx.html
2. Click the bell to subscribe
2. Wait for prompt to appear
3. Click Allow
4. Block notification
5. Reload the page
6. Unblock notification
7. Reload the page
8. Click the bell to subscribe again
9. Send a message
10. Can't receive notification

**Comment by dgeibi** [comment]
![image](https://user-images.githubusercontent.com/2224764/46991029-a5820180-d136-11e8-8a1a-dae510dcd6d3.png)

**Comment by itrush** [comment]
Hi @dgeibi, fix for this issue is in the works and will be available with the next release.

**Comment by wmapes7** [comment]
What is the ETA on this fix?

**Comment by itrush** [comment]
The fix is live as of 10/19/2018 afternoon, please see the full release notes [here](https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/150501).

**Comment by dgeibi** [comment]
Thank you for the fix! @itrush

**Comment by kostiantyn-solianyk** [comment]
same issue even on newest sdk version, any updates?
