### ISSUE TITLE
Wordpress Plugin Error

### ISSUE THREAD

**Issue by serdarozbilen** [OneSignal/OneSignal-Website-SDK#423]
I deleted onesignal plugin on my wordpress site. But stil getting onesignal and superpwa errors. Why ?

A bad HTTP response code (404) was received when fetching the script.
Failed to load resource: net::ERR_INVALID_RESPONSE

**Comment by jkasten2** [comment]
@serdarozbilen They are most likely for the OneSignalSDKWorker and OneSignalSDKUpdaterWorker files. The browser will directly hit these service worker URLs to check if their are updates. I recommend checking your logs to confirm the exact URL of the 404.

If you have added another push provider or have another service work for other reasons on your site they will normally replace already registered service workers.

If you don't have anything using a service worker on your site now you can unregister the service worker or wait until browser drop them

**Comment by rgomezp** [comment]
closing due to no response
