### ISSUE TITLE
OneSignal Notification Image is not visible for firefox

### ISSUE THREAD

**Issue by riteshravlani** [OneSignal/OneSignal-Website-SDK#430]
**Description:**

We are using OneSignal to send push notifications. Everything is working fine for Chrome but we are facing some issue with Firefox. We are sending an object as below content, heading, icon, id, image and url for push notification. However, the image is not visible for firefox notification.

**Steps to Reproduce Issue:**

1. Visit https://adidasv5.thenewsmarket.info/ in chrome and firefox (63.0 (64-bit))
2. Allow notifications
3. Visit https://onesignal.com/ and login
4. Go to messages section and click New Push 
5. Enter Title and Message
6. Add Image for options
7 Click confirm button and then click on send the message

**Anything else:**

The expected result is - it should send a notification message with an image.
**issue:** notification image appears in chrome but it is not appearing for firefox

I have enabled trace using "OneSignal.log.setLevel('trace');" in both chrome and firefox

**Chrome log shows as below:**
content: "Message"
heading: "Title"
icon: "https://img.onesignal.com/t/776ebb32-528d-4d53-8217-41a332361f36.png"
id: "###############"
image: "https://img.onesignal.com/n/d1cba013-cde1-4f96-a125-6cfeb1005b1b.jpg"
url: ""

**Firefox log shows as below**
content: "This is an example notification."
heading: "one signal Test Message"
icon: "https://img.onesignal.com/t/776ebb32-528d-4d53-8217-41a332361f36.png"
id: "################"
url: "https://adidasv5.thenewsmarket.info?_osp=do_not_open"

Image attribute is not coming for firefox.

Can you please help me to resolve this issue.
Please let me know if you need anymore details..

**Comment by fatsjohonimahnn** [comment]
Firefox and Safari do not support images in push notifications like Chrome. More info on this here: https://documentation.onesignal.com/v5.0/docs/web-push-notification-icons#section-image

**Comment by riteshravlani** [comment]
Ok. Thank you for your quick reply
