### ISSUE TITLE
I'm DDoS'ed by your JS script (referrer)

### ISSUE THREAD

**Issue by Tigzy** [OneSignal/OneSignal-Website-SDK#434]
Hey, 
I have no idea what your SDK does, but I need your help because our website is being DDoS'ed by your script. Please look: https://twitter.com/TigzyRK/status/1060170902858543105

Can you tell me how our image url is stored in your script, and if you have any idea why it's called that many times and consuming our server bandwidth?

Regards,
Adlice Team.

**Comment by Tigzy** [comment]
The url: https://ez3c.tw/OneSignalSDKWorker.js?appId=e878aa8d-8303-4092-bfeb-d183ddf9e786
goes to: https://cdn.onesignal.com/sdks/OneSignalSDK.js

**Comment by rgomezp** [comment]
Please see this [response](https://github.com/OneSignal/OneSignal-WordPress-Plugin/issues/121#issuecomment-395621413) by jkasten (ignore solution #3)
