### ISSUE TITLE
addListenerForNotificationOpened not working the second time

### ISSUE THREAD

**Issue by varunpottigari** [OneSignal/OneSignal-Website-SDK#436]
**Description:**

I have added the "addListenerForNotificationOpened" callback as mentioned in the documentation [here](https://documentation.onesignal.com/docs/web-push-sdk#section--addlistenerfornotificationopened-).
`OneSignal.push(['addListenerForNotificationOpened', function (data) {
      console.log(data);
    }]
    );`

The function is fired when I receive a notification and the website is not opened, and the action is performed (which is to redirect him to another url based on the additional data fields of the notificaiton).
But when I receive the notificaiton again, the function is not called. 

The same issue is observed even when some other URL is already opened. The function is triggered the first time and doesn't work when a second notification is clicked. 

According to the documentation 
"This event occurs once only. If you would this to occur continuously every time a notification is clicked, please call this method again after your callback fires."

But I am not sure how to call the method again after the callback fires. 

Any example on how to do the same would be helpful.
(your description here)

**Steps to Reproduce Issue:**

1. I am using Angular 6 and the above code is written in the ngOnInit() hook in app.component.ts file. 

**Anything else:**

(any other information here)

**Comment by varunpottigari** [comment]
Hi @jasonpang ,

I've seen that you have addressed similar issues, can you please help me with the same.

Thank you.

**Comment by itrush** [comment]
Hi @varunpottigari,

Checking the implementation of the `addListenerForNotificationOpened`, it seems that "it's not a bug but a feature". It was designed to fire provided callback only once. As a workaround for now you can simply re-subscribe to the event from your handler. For example:

```
OneSignal.push(function() {
    const onNotificationClicked = function (data) { console.log(data); }

    const handler = function (data) {
      // call your primary handler
      onNotificationClicked(data);

      // add another handler right away
      OneSignal.addListenerForNotificationOpened(handler);
    };

    // attach your handler for the first time
    OneSignal.addListenerForNotificationOpened(handler);
  });
```

And we will look into adding another method that does not require adding a handler each time. Please let us know if it helped! 

Thanks.

**Comment by rgomezp** [comment]
Closing due to no response.

**Comment by toanhuynh345** [comment]
use HTTPS in your domain, don't use HTTP. that's work.
