### ISSUE TITLE
ServiceWorker error in WordPress project with Polymer

### ISSUE THREAD

**Issue by MatheusR98** [OneSignal/OneSignal-Website-SDK#443]
**Description:**

I am new with OneSignal...
I have a site with some web components of Polymer, in WordPress platform and now i want to use OneSignal custom code web push notifications...
I tried in local server (using MAMP Pro without SSL) and worked perfectly, but when i put in production (with SSL)  i have this issues

> A bad HTTP response code (404) was received when fetching the script 
> Failed to load resource: net::ERR_INVALID_RESPONSE
> [Service Worker Installation] Installing service worker failed
> TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
> ServiceWorkerManager.js:378 GET https://mais.cpb.com.br/OneSignalSDKWorker.js?appId=my-app-id-here (Not Found)

I read some tips from OneSignal documentation [here](https://documentation.onesignal.com/docs/web-push-setup-faq#section-can-onesignal-integrate-with-another-service-worker-on-my-site-or-a-progressive-web-app-) and i read other issues here in Github, but the solutions don't give my problem solved, and i don't have a serviceworker in my actual project, or if i have i don't know where is, so i don't know what is wrong. I put OneSignal archives in root and like i said, for local server this work nice, but in production something is wrong. 

**Steps to Reproduce Issue:**

1. Visit https://mais.cpb.com.br
2. Click on the green bell on left bottom
3. See the console from navigator (except Safari)

**Anything else:**

I tried to use typical site, because i think could me my mistake in custom code, but this doesn't work too.
Anyone have an idea?
Sorry for english mistakes, i'm not an expert.

**Comment by rgomezp** [comment]
Closing due to no response.
