### ISSUE TITLE
One Signal cache control

### ISSUE THREAD

**Issue by Guits32** [OneSignal/OneSignal-Website-SDK#445]
**Description:**

When I fetch - https://onesignal.com/api/v1/notifications?app_id=YOUR_APP_ID - (https://documentation.onesignal.com/reference#view-notifications), the API doesn't return last pushes, I have to clear my cache to get them. So I tried to set "Cache-control" header, but I get the following error:

> Access to fetch at 'https://onesignal.com/api/v1/notifications?app_id=MY_APP_ID from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field Cache-control is not allowed by Access-Control-Allow-Headers in preflight response.

BR

**Comment by jkasten2** [comment]
@Guits32 Make sure you are turning off client caching for the requests you are doing. This will vary depending the library you are using to make the REST API request.

OneSignal won't accept a "Cache-control" header, so you can't force clear any server side cache. The notifications endpoint isn't designed to be polled often, so the response will be cached for 30 seconds, for the same app_id and offset that is.

Lastly make sure to NEVER use the OneSignal REST API KEY from a client request from the browser. As someone can easily get this key.

**Comment by Guits32** [comment]
Ok, thank you for your answer @jkasten2.

**Comment by predel143** [comment]
its worthit..
