### ISSUE TITLE
RN OneSignal.didSetNotification Opened Handler is not a function

### ISSUE THREAD

**Issue by kiirat** [OneSignal/OneSignal-Website-SDK#447]
**Description:**

when I add this code below the notifcation alert appears but I receive the following error " ExceptionsManager.js:84 Unhandled JS Exception: TypeError: RN OneSignal.didSetNotification Opened Handler is not a function"
apparently this line "OneSignal.addEventListener('opened', this.onOpened)" that makes the problem when I remove it  the problem disappeared

Code Line 
 constructor(props) {
    super(props)
    OneSignal.init("my ID");
    OneSignal.addEventListener('received', this.onReceived);
    OneSignal.addEventListener('opened', this.onOpened);
    OneSignal.addEventListener('ids', this.onIds);
  }
  componentWillUnmount() {
    OneSignal.removeEventListener('received', this.onReceived);
    OneSignal.removeEventListener('opened', this.onOpened);
    OneSignal.removeEventListener('ids', this.onIds);
  }
  onReceived(notification) {
    console.log("Notification received: ", notification);
  }
  onOpened(openResult) {
    console.log('Message: ', openResult.notification.payload.body);
    console.log('Data: ', openResult.notification.payload.additionalData);
    console.log('isActive: ', openResult.notification.isAppInFocus);
    console.log('openResult: ', openResult);
  }
  onIds(device) {
    console.log('Device info: ', device);
  }

![simulator screen shot - iphone 7 - 2018-12-11 at 16 43 32](https://user-images.githubusercontent.com/30218125/49811677-a52f6c80-fd5b-11e8-896a-a94c1ea2920d.png)

**Comment by rgomezp** [comment]
Hello,
Were you able to resolve the issue? Please check the troubleshooting guide as well. Try using console.log statements to debug and gain further insight into what may be happening.

**Comment by kiirat** [comment]
yes I solved it by updating the package . Thank you rgomezp
