### ISSUE TITLE
Add a callback for when the OneSignalSDK has loaded

### ISSUE THREAD

**Issue by BorjaRafols** [OneSignal/OneSignal-Website-SDK#449]
**Description:**

Currently we are being asked to load the OneSignalSDK syncronously so that the subsequent code like this works:

`OneSignal.push(function() {
  OneSignal.sendTags({
    userId: 'example_userId_123'
  }).then(function(tagsSent) {
    // Callback called when tags have finished sending
    console.log(tagsSent);   
  });
});`

**Steps to Reproduce Issue:**

**Anything else:**
I'd just like to have a way to add a callback that notifies my code that this library has loaded. Google does this with their maps API.

`<script async defer src="https://maps.googleapis.com/maps/api/js?callback=initMap" type="text/javascript"></script>`

This should be pretty trivial to implement.

**Comment by jkasten2** [comment]
@BorjaRafols The `sendTag` and `sendTag` functions support passing in a callback function and they also return a `Promise` so you can use `.then` and `.catch` as well.
https://documentation.onesignal.com/docs/web-push-sdk#section--sendtags-

OneSignal support loading `OneSignalSDK.js` `async` or `defer`, using `async` is recommended in the documentation. `defer` is also fine but note that it will load OneSignal last so any permission prompting will be delayed longer. Using `window.OneSignal = window.OneSignal || [];` then making all calls with `OneSignal.push()` will ensure everything works when using `async`. Any `OneSignal.push()` calls will fire as soon as the `OneSignalSDK.js` is fully loaded by the browser.

**Comment by BRafols** [comment]
Totally true, sorry guys.
