### ISSUE TITLE
Listener for notification unreliable when notification is moved to action center

### ISSUE THREAD

**Issue by anl176** [OneSignal/OneSignal-Website-SDK#450]
**Description:**

When multiple notifications are in the action center, only 1 will trigger my listener for notification opened.

**Steps to Reproduce Issue:**

1. Have multiple notifications in the action center
2. Click on them one by one
3. See only 1 triggers listener added through OneSignal.push(["addListenerForNotificationOpened", myListener])

**Anything else:**

The notification that triggers the listener is not necessarily the last one received. Tested on Chrome 71.0.3578.98. I was not able to find any documentation regarding this so any help is appreciated.

**Comment by rgomezp** [comment]
Hello,
The reason is that this event only occurs once. You need to add the listener again in the callback once it fires. Please read the [documentation](https://documentation.onesignal.com/docs/web-push-sdk#section--addlistenerfornotificationopened-) for more info.
