### ISSUE TITLE
Issue Dashboard [EXTERNAL USER ID]

### ISSUE THREAD

**Issue by Droppix** [OneSignal/OneSignal-Website-SDK#451]
Hi,

I use the last OneSignal WEB SDK (from cdn), I have assigned an "external user id" to my "playerID" (https://onesignal.com/api/v1/players/{playerID}?appId=...), but your Dashboard (Users View),doesn't want to display the column (EXTERNAL USER ID).

Is it a bug or is there something I didn't understand?

Thanks

**Comment by caipivara** [comment]
@Droppix why did you close it? Im having the same issue

**Comment by gching** [comment]
@caipivara you can view it by ticking to display the column in the users dashboard (bottom left)
![screen shot 2019-02-10 at 3 27 42 am](https://user-images.githubusercontent.com/3330119/52533110-e56f8480-2ce3-11e9-99ed-c9b897ce59bf.png)

**Comment by gilzon** [comment]
Thanks
