### ISSUE TITLE
Custom link acts different on desktop and on android with typical site configuration

### ISSUE THREAD

**Issue by Misiu** [OneSignal/OneSignal-Website-SDK#466]
**Description:**

After configuring my first site with notifications I noticed that my test website acts different on the desktop and on mobile. On the desktop I get the correct button that says `subscribe to push notifications\unsubscribe from push notifications`, but on mobile, I always get `subscribe to push notifications`, nothing changes on site, but notifications seems to work.

**Steps to Reproduce Issue:**

  1. Configure notifications to use the custom link as permission prompt.
  2. Add this code in Your page header:
```
var OneSignal = window.OneSignal || [];
OneSignal.push(function() {
    OneSignal.on('subscriptionChange', function(isSubscribed) {
        alert("The user's subscription state is now: " + isSubscribed);

        if (isSubscribed === true) {
            OneSignal.sendTags({
                sub_url: window.location.href,
                clientId: '12455'
            }).then(function(tagsSent) {
                alert("tagsSent: " + JSON.stringify(tagsSent));
            });

            OneSignal.getUserId(function(userId) {
                alert("OneSignal User ID: " + userId);
            });
        } else {
            alert("User is not subscribed");
        }
    });
});

OneSignal.push(function() {
    OneSignal.init({
        appId: "5b0ccadf-2051-4122-b2f0-cb55c6396668",
    });
});
```

  3. Open the page on Chrome on Windows and click `Subscribe to push notifications`. You should get one alert: `The user's subscription state is now: true`, second with `OneSignal User ID: userId` and third with `tagsSent: {"sub_url":"https://labs.jagusz.pl/","clientId":"12455"}`. Then button should change the label to `Unsubscribe from push notifications`.
  4. Open the same page on Chrome on Android. After clicking button You will get alert `The user's subscription state is now: false` and nothing else.

**Anything else:**

I have Windows 10 and Chrome 71.0.3578.98 and Chrome Mobile 66.0.3359.158 on Android 6.0.1.

I've noticed that on mobile when I lock and unlock my phone the `subscriptionChange` event fires. Is that normal?

I've uploaded my sample app to https://labs.jagusz.pl/.
My idea is to show the subscribe button only when push notifications are available (user didn't block anything, onesignal was not blocked by any blockers and user isn't subscribed) and unsubscribe when user is subscribed.

**Comment by rgomezp** [comment]
Hi Misiu,
Thanks for the detailed explanation and sample app! I was not able to reproduce the issue. When I visited your app on both platforms I got all three alerts and the button did in fact change. Maybe you changed something?

**Comment by Misiu** [comment]
@rgomezp I didn't change anything in my test site.
I've uninstalled Chrome on my phone and installed the latest version (71.0.3578.99). After visiting the page everything seems to work fine.
I have one idea what could cause the error. When I first created my app I've accessed it via jagusz.pl/labs then I've changed URL in the config to use the subdomain.
I've subscribed using the subdirectory and then continued to work using the subdomain.
Do You think this might cause this weird behavior?

I'll try to recreate the issue with the latest Chrome version. I'll get back with results.

**Comment by rgomezp** [comment]
@Misiu this was likely the issue. I'm glad everything is working fine now! OneSignal will only work on the exact origin that is configured in the dashboard. Please see this [guide](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) for more info on same-origin policy.
