### ISSUE TITLE
onesignal custom link does not work correctly

### ISSUE THREAD

**Issue by omergulen** [OneSignal/OneSignal-Website-SDK#467]
I try to add custom link to my website, but when I turn off "allow unsubscribe" which is intended to prevent users to unsubscribe with that button and it will be shown when someone who is not subscribed is entered to the website and when someone enters to the website who is subscribed he/she won't see the button.

But in my case when I make it false, it doesn't show up at all.
But it works fine when I turn this "allow unsubscribe " on.

Steps to Reproduce Issue:

1. Visit https://onesignal.com.
2. Go to settings on your app.
3. Go to Permission Prompt Setup section.
4. Click on Add prompt button.
5. Choose a custom link option
6. Set ALLOW UNSUBSCRIBE option to false.
7. verify on your site.

**Comment by rgomezp** [comment]
Hello,
If you make "Allow unsubscribe" to be false, this means the user won't be able to unsubscribe using the button (as the name implies). In other words, the allow unsubscribe works as intended (I just tested it). However, I think the confusion may come from the fact that next to the switch it says "Hide button if user is subscribed," which is potentially confusing given it is the exact opposite. I will make a note to fix this in the dashboard. Thanks for bringing this to our attention!
