### ISSUE TITLE
Simulate Onesignal notification click

### ISSUE THREAD

**Issue by dominhtri1995** [OneSignal/OneSignal-Website-SDK#468]
How do I simulate the behavior of clicking the Onesignal Web notification ? When user click on a link to my website, I want to direct user to an existing tab of the same page. This would make it possible to support notifications outside of Onesignal web-push too.

Thank you.

**Comment by rgomezp** [comment]
Hello,
I don't quite understand what you mean. Are you trying to set a launch url for your notifications?

**Comment by rgomezp** [comment]
Closing due to no response.
