### ISSUE TITLE
How to change OneSignal Subscription Bell z-index css?

### ISSUE THREAD

**Issue by slowaways** [OneSignal/OneSignal-Website-SDK#469]
I want change the css z-index of Subscription Bell because it is on top of an important content of my site:
<img width="320" alt="captura de tela 2019-01-12 as 02 28 26" src="https://user-images.githubusercontent.com/9668277/51069639-e2647400-1611-11e9-86f8-b747482a306c.png">

**Comment by rgomezp** [comment]
Hello, 
Have you tried setting the z-index of your component rather than trying to change ours?

**Comment by slowaways** [comment]
@rgomezp Yes! No effect!

**Comment by rgomezp** [comment]
Strange. You should be able to change this somewhat easily. Have you tried using `!important`?

**Comment by rgomezp** [comment]
Closing due to no response.

**Comment by slowaways** [comment]
@rgomezp Yes. I added `!important`

**Comment by rgomezp** [comment]
Hello, you can alternatively use the sliding prompt if the notify button is causing you too much of a headache
