### ISSUE TITLE
how to listen to receive notification event or click notification event

### ISSUE THREAD

**Issue by novaknole** [OneSignal/OneSignal-Website-SDK#470]
**Description:**

I'm trying to use onesignal web push notifications. from laravel api, i send the notification successfully. in front-side, i get the notification and it gets displayed. All is good, but what I need now is when I get the notification on the front-side, i have to do something. which leads me to the situation where I need to know when notification gets received on front-side.

**Steps to Reproduce Issue:**

1. I have tried the following code but doesn't work.

```
OneSignal.once('notificationDisplay', (event) => {
    console.log(event);
  });
```
This causes something so wrong. If I first agree to receiving notifications by clicking 'Allow', everytime I get notifications , this event is called successfully. The bad thing happens, when I first block receiving notifications. I first block it, then I allow it again, but after allowing, it doesn't continue firing the above event at all. So this event only works if I first clicked 'Allow' and I never block notifications. What do you think? 

**Anything else:**

(any other information here)

**Comment by rgomezp** [comment]
Hello @novaknole 
You are using the function `once` instead of `on`. I suspect that this is in fact what is causing your issue. If you use the function `on`, the event will be fired every time instead of just the first time.

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by hoangduy1508** [comment]
Any update i have same error. I add this code to my website

`
OneSignal.on('notificationDisplay', function (event) {
                    console.log('OneSignal notification displayed:', event);
});
`

but don't have anything log is show when i received the notification

**Comment by rgomezp** [comment]
Howdy @hoangduy1508 ,
To confirm, the reproduction steps are the same as @novaknole 's ? i.e. 
>The bad thing happens, when I first block receiving notifications. I first block it, then I allow it again, but after allowing, it doesn't continue firing the above event at all

?

**Comment by hoangduy1508** [comment]
> Howdy @hoangduy1508 ,
> To confirm, the reproduction steps are the same as @novaknole 's ? i.e.
> 
> > The bad thing happens, when I first block receiving notifications. I first block it, then I allow it again, but after allowing, it doesn't continue firing the above event at all
> 
> ?

I resolved it. 'notificationDisplay' event only working for https website. But in the document i don't see the note for that.
I suggest add a note to document to let user know about that.

**Comment by rgomezp** [comment]
Thanks for the input. We will update the docs to make this more clear.

**Comment by iAmWillShepherd** [comment]
@rgomezp the docs have been updated to reflect that this event is only fired when running a site on HTTPS.
