### ISSUE TITLE
actionMessage on Mobile doesn't seems to work properly

### ISSUE THREAD

**Issue by synga** [OneSignal/OneSignal-Website-SDK#472]
**Description:**

When using the OneSignal init method on mobile it doen't seems to load the correct message for the `actionMessage` when using the `.showHttpPrompt()` method.
I need my internationalization file to use in `promptOptions` property and then i initialize it, the accept and decline buttons are translated, but the message doesn't shows as expected.
I've checked multiple times and it's not my internationalization file or concurrency problems.

**Steps to Reproduce Issue:**

My code:

    OneSignal.push(() => {
        OneSignal.init({
          appId: 'id',
          allowLocalhostAsSecureOrigin: true,
          promptOptions: {
            actionMessage: this.langs.onesignalActionMessage,
            exampleNotificationTitleDesktop: this.langs.onesignalExampleNotificationTitleDesktop,
            exampleNotificationMessageDesktop: this.langs.onesignalExampleNotificationMessageDesktop,
            exampleNotificationTitleMobile: this.langs.onesignalExampleNotificationTitleMobile,
            exampleNotificationMessageMobile: this.langs.onesignalExampleNotificationMessageMobile,
            exampleNotificationCaption: this.langs.onesignalExampleNotificationCaption,
            acceptButtonText: this.langs.onesignalAcceptButtonText,
            cancelButtonText: this.langs.onesignalCancelButtonText
          },
          welcomeNotification: {
            disabled: false,
            message: this.langs.onesignalWelcomeNotificationMessage
          }
        });
      });

And here's the result:
![onesignal](https://user-images.githubusercontent.com/9086829/51207306-95beb880-18f1-11e9-975a-a65bddce42d0.PNG)

As seen in image the buttons are translated, but the message is not. Is there something i'm missing? I'm following the docs for this

**Anything else:**

(any other information here)

**Comment by rgomezp** [comment]
It looks like you have the correct `actionMessage` key. However, since you're using a variable for the value, I cannot directly see or test its value. Please double check that this variable is dynamically changing with the language and that you configured it correctly.

**Comment by rgomezp** [comment]
Closing due to no response
