### ISSUE TITLE
One Signal works if I want to host all *.js files locally?

### ISSUE THREAD

**Issue by slowaways** [OneSignal/OneSignal-Website-SDK#474]
I recently ran performance testing on my site and the `OneSignalSDK.js` file, loaded by URL `https://cdn.onesignal.com/sdks/OneSignalSDK.js` takes a LOT time to fully load and even more than 70% of all code is not used initially after loading...

<img width="1352" alt="captura de tela 2019-01-23 as 20 42 23" src="https://user-images.githubusercontent.com/9668277/51644605-70fcbd80-1f4f-11e9-8866-c9fdcbd5bd8a.png">

_320ms of waiting... (slow)_

---

The file cache time is also low, which in many tests such as GTMetrix, Google SpeedPage and etc, shows an alert on the cache time and this makes it lose score (page grade).

<img width="966" alt="captura de tela 2019-01-23 as 20 37 36" src="https://user-images.githubusercontent.com/9668277/51644399-c71d3100-1f4e-11e9-82c0-8b7cf2886579.png">

_OneSignal with 5 min of cache TTL in Google PageSpeed_

<img width="1009" alt="captura de tela 2019-01-23 as 20 40 29" src="https://user-images.githubusercontent.com/9668277/51644511-254a1400-1f4f-11e9-95e2-d4a5df2eb777.png">

_GTMetrix specify a cache validator_

---

How can I load OneSignal .js files locally in my website?

**Comment by rgomezp** [comment]
The purpose of using a cdn is actually to increase the availability and the performance, though I suppose you could host the files yourself as long as they are in your top-level root of your site directory.

**Comment by rgomezp** [comment]
Closing due to no response.

**Comment by slowaways** [comment]
Why not add an option in the plugin to store these files locally? Many blogs use advanced features for performance improvement and CDN.

**Comment by rgomezp** [comment]
Hello, are you speaking of the Wordpress plugin?

**Comment by beatsk** [comment]
The idea with files stored locally sounds great. Pagespeed Insights has a big problem with OneSignal javascript. Still says that it is actually inactive and sugessting to remove it.
