### ISSUE TITLE
Web notifications not working on Android devices (Chrome and Firefox)

### ISSUE THREAD

**Issue by 3omdawy** [OneSignal/OneSignal-Website-SDK#478]
**Description:**

I use web push notification (HTTPS). My website is: https://madraset-elshamamsa.com/.
I have the following behavior:
1 - On iOS devices: the bell does not show at all ==> expected, no problem
2 - On Windows: everything works perfectly on Microsoft Edge.
For Chrome, I need to be opening the browser to receive the notification (Even if I set it to High priority)
==> Problem with Medium criticality
2 - On Android (HTC - Chrome and Firefox): I am able to subscribe but no notifications are shown at all!! even if the browser is opened ==> Critical issue for me.

Some notes: I use awardspace as a host, and Cloudflare as a CDN (to be https compliant).
I skipped cloudflare and tried the HTTP notification, still no difference.

I tried all the debugging steps on OneSignal website but nothing works for me ...
When I used USB debugging for the HTC mobile, the notification arrives to the browser but it is not shown.
I cleared the cache and reset permissions, subscribed again, still no difference.

**Steps to Reproduce Issue:**

1. Visit https://madraset-elshamamsa.com/ from any Android device (Chrome / Firefox browser)
2. Click the red bell in the bottom left, allow notifications
3. You should normally receive a welcome notification ... but it is not shown

**Anything else:**

(any other information here)

**Comment by fatsjohonimahnn** [comment]
Unfortunately was not able to reproduce this on your site https://madraset-elshamamsa.com/ using Android Galaxy and Chrome

My player id in your account is 82d35223-1694-421b-94bf-1b0a77e0cf8d

Attached are images of the bell and welcome notification.

![screenshot_2019-01-29-17-36-02](https://user-images.githubusercontent.com/19843180/51951516-ce7a8980-23e9-11e9-934e-6c4a4f427ff5.png)
![screenshot_2019-01-29-17-29-49](https://user-images.githubusercontent.com/19843180/51951525-d33f3d80-23e9-11e9-97bf-6103ad9a10c9.png)

When you subscribe to websites, you will only see the welcome notification the first time you subscribe. If you clear browser data and try to resubscribe, you will not get the welcome notification again.

You must clear your browser data and reset your notification permissions to test as a first time user.

Please see this guide for more info on how to do this with Android: https://documentation.onesignal.com/docs/troubleshooting-web-push#section-chrome-android-

**Comment by 3omdawy** [comment]
Thanks Jonathan for your reply .. I reset permissions but no change.
At least it seems to be working on some mobile devices but for me it is unsatisfactory if it does not work on (at least) most mobile devices and Chrome (when the browser is not opened).

Thanks again

**Comment by 3omdawy** [comment]
Guys, it is working 👍 😄 
Chrome and Firefox notifications were blocked on the device, so whatever the browser received, it could not show :D ... thanks for your support

**Comment by jasonLiu001** [comment]
> 
> 
> Guys, it is working 👍 😄
> Chrome and Firefox notifications were blocked on the device, so whatever the browser received, it could not show :D ... thanks for your support

Hi, how did you solved this problem? Could you share something for me. Because I also encounter this. Wish your help. Thanks.

**Comment by 3omdawy** [comment]
Hello,

In my case, the browser notifications were disabled in mobile settings ... so the problem was in the global device settings, not related to my website.
