### ISSUE TITLE
onesignal set url when notification received

### ISSUE THREAD

**Issue by novaknole** [OneSignal/OneSignal-Website-SDK#483]
**Description:**

'm using webpush notification. (not mobile).

I have been struggling about this for a very long time and I'd be so happy if you'd just try to help me a little bit. Thank you guys really so much.

I send notification from php back-end api to front-end. Onesignal says that you must pass url parameter from back-end api. Turned out I can't do that, because if I do that, then back-end api has to know my front-end urls, which I didn't want.

Here is how I want: I'd pass some parameters id=2&name="giorgi" from my back-end and when I'd recieve notification on front-end , I'd set the url there . When user'd click on the notification, he would go to that url.

**Steps to Reproduce Issue:**

1. I tried this. 

```
OneSignal.on('notificationDisplay', function(event) {
            event.url ="anotherurl/change";
            console.warn('OneSignal notification displayed:', event);
        });
```
but it didn't work.

What do I do?
**Anything else:**

(any other information here)

**Comment by rgomezp** [comment]
If I understood your question, you want to dynamically set the launch URL based on the user's activity on the client?

**Comment by rgomezp** [comment]
Closing due to no response
