### ISSUE TITLE
I can't get userId after subscibing success

### ISSUE THREAD

**Issue by zhangchengzheng91** [OneSignal/OneSignal-Website-SDK#485]
**Description:**

my site url is 'https://explame.com'.It is fully https.So in my setting I don't chose 'My site is not fully HTTPS'.
Users subscibe to my site sucessfully. 
I can get these values:
Notification.permission === 'granted'
OneSignal.isPushNotificationsSupported() === true
but, the follows is out of my mind:
OneSignal.isPushNotificationsEnabled() === false
OneSignal.getUserId() === null
So, I can't find userId in chrome console and Application IndexedDB and segments.
my users can't get my messages.
this is amzing.
what can I do for this? 
What can I do then I get userId?
Please help me.
thanks 

chrome version: 72
If you need another message, I can provide.

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(any other information here)

**Comment by rgomezp** [comment]
We provide the function `getUserId` so that you can fetch the ID easily. Is this not working for you? Please provide more information so I can better understand your problem.

**Comment by zhangchengzheng91** [comment]
> We provide the function `getUserId` so that you can fetch the ID easily. Is this not working for you? Please provide more information so I can better understand your problem.

Now, this problem dosen't exist.
I don't known why.
Thanks for your reply.

**Comment by rgomezp** [comment]
Hello, happy to hear that you were able to solve your problem. Please let us know if you encounter any other problems.
