### ISSUE TITLE
OneSignalShimLoader.ts - Self Hosting the JavaScript Web SDK

### ISSUE THREAD

**Issue by philipp-schaerer-lambdait** [OneSignal/OneSignal-Website-SDK#493]
**Description:**

We are using One Signal Web SDK and are hosting the SDK files on our servers by following this [Documentation](https://github.com/OneSignal/OneSignal-Website-SDK/wiki/Self-Hosting-the-JavaScript-Web-SDK).

The latest release has the new dynamic loading mechanism via the OneSignalShimLoader.ts file. Now the question is, does this dynamic loading always load from the One Signal CDN or is it possible to bypass or configure this?
Or is it planned in a feature release to add the self hosted option again? Or shouldn't it be used anymore?

**Steps to Reproduce Issue:**

There are no steps to reproduce.

**Comment by rgomezp** [comment]
Hello,
We've always told people to use the CDN to make sure everyone is running the latest version and to facilitate backwards compatibility. We aren't sure yet whether or not we want to support this in the future but are looking at all the considerations thoroughly. 

Thanks for bringing this up

**Comment by philipp-schaerer-lambdait** [comment]
Thank you for the information, but there is some semi-major issue with the hosting via CDN. The Ad-Blockers may block the request. One example is the uBlock Origin. There‘s also pottential CORS conflict, not that there is one currently.
An interesting additional feature to the CDN approach would be to be able to proxy the CDN call. But for this the _OneSignalShimLoader.ts_ needs to be configurable.
