### ISSUE TITLE
automatic notification prompt not work on google chrome mobile

### ISSUE THREAD

**Issue by elkoutari** [OneSignal/OneSignal-Website-SDK#502]
**Description:**

automatic native prompt not work on google chrome mobile when i set autoRegister: true, but when i make it false it work on chrome mobile version, tested here https://6.maqalat24.com/

```javascript
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
<script>
  var OneSignal = window.OneSignal || [];
      OneSignal.push(function() {
            OneSignal.init({
              appId: "e329316b-482d-4c41-962b-fc098e15c273",
                  autoRegister: true,
                      notifyButton: {
                        enable: false,
                      },
            });
          OneSignal.showNativePrompt();
       });
</script>
```

**Comment by rgomezp** [comment]
Hello @elkoutari ,
Are you saying the flag is acting the exact opposite of what it's supposed to? I encourage you to reach out to us directly through the support channel at OneSignal.com where we'd be happy to help you directly.

**Comment by rgomezp** [comment]
Closing due to no response
