### ISSUE TITLE
How to close or hide Onesignal Notification for Website

### ISSUE THREAD

**Issue by rauzan92** [OneSignal/OneSignal-Website-SDK#510]
I'm implementing the Onesignal notification for my website, but I try to find a way to hide the notification popup when my website received the notification.

Any solution guys to hide or automatically close the notification popup?

**Comment by rgomezp** [comment]
Hello,
I didn't quite understand your question. You want to implement notifications but you want to hide them? Or are you talking about the permission popup?

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by frajta160** [comment]
Interested in this also...
Is there any way to programatically hide/dismiss the notification after it is received?
Consider a case where we want to let the website handle how the user is notified when he is already on the website.
