### ISSUE TITLE
WebPush Multiple PlayerIds for same device and browser

### ISSUE THREAD

**Issue by connetcom** [OneSignal/OneSignal-Website-SDK#514]
**Description:**

After clearing DBs and caches and then subscribing a user to OneSignal multiple playerIDs for the same user persist in the OneSignal active users.

**Steps to Reproduce Issue:**

Created a very basic site with only one line of HTTP and then no other JS except for code directly off the OneSignal site.

Starting from a cleared storage (cache, DB, etc..), when a user subscribes this results in the user showing up in the dashboard Active Users display with a playerID. 

Delete the client side DB and cache, etc... and redo the process, it results in another playerID for the same user, same browser and same device .  

The question is how to these zombies get deleted from the db? Will they persist until manually deleted on the dashboard?

**Anything else:**
Read somewhere on the OneSignal site that it is not possible to delete zombies from the server side.
(any other information here)

**Comment by rgomezp** [comment]
Hello,
Thanks for your question. You will see that it takes two notifications for OneSignal to account for the lost subscriber. For example, you have 3 subscribers. You clear your cookies and reset permission for the site. You are now a new subscriber. When you send a notification, you will see it was sent to 4 people. If you send another one, OneSignal will realize that the device is no longer subscribed and account for the difference, returning 3 as the recipients once again.
