### ISSUE TITLE
Microsoft Edge: notificationPermissionChange handler not working on deny case

### ISSUE THREAD

**Issue by dornbirndevelops** [OneSignal/OneSignal-Website-SDK#515]
**Description:**

A registered `notificationPermissionChange` handler is not invoked when permission changes from `default` to `denied`. Instead, the following error is shown in console (log level: trace)
`Exiting subscription and not registering worker because the permission was blocked.`
--> `SubscriptionManager.js (280,21)`

```
{description: "Notification permissions are blocked.", message: "Notification permissions are blocked.", name: "q", reason: 0, stack: "q: Notification permissions are blocked. at Anonymous function (https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=150703:1:154038) at Generator.prototype.next (native code) at r (https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js?v=150703:1:150034)"}
```

This only happens on Microsoft Edge.

**Steps to Reproduce Issue:**

1. Visit an active OneSignal page served over https
1. register `notificationPermissionChange` handler
    `OneSignal.on("notificationPermissionChange", (permissionChange) => { console.log('notificationPermissionChange', permissionChange.to); });`
1. Ask for Permission and deny the upcoming permission request.
    `OneSignal.registerForPushNotifications();`

**Temporary Workaround:**

`OneSignal.registerForPushNotifications();` seems to be a promise, which resolves empty as soon as the user confirms/declines permission prompt. adding a polling interval solves the issue for all browsers. FYI: the poll is needed due to race conditions (update notification.permission vs do then) especially noticed in Safari.

```
const poll = () => { const handle = setInterval(() => { if (Notification.permission !== 'default') { clearInterval(handle); console.log(Notification.permission); } }, 1000); }

OneSignal.registerForPushNotifications().then(poll);
```

**Comment by rgomezp** [comment]
Hello,
Thanks for your patience. I will have to reproduce this issue so I'm happy you were able to find a workaround in the meantime.

**Comment by rgomezp** [comment]
Successfully reproduced this bug. Thank you so much for reporting it! @dornbirndevelops

**Comment by 0shi** [comment]
I don't see the `notificationPermissionChange` handler fire at all when moving from `default` to `denied` in Chrome using localhost testing on http with Treat HTTP localhost as HTTPS for testing enabled

**Comment by natterstefan** [comment]
Hi @rgomezp, any news regarding this issue?

**Comment by jkasten2** [comment]
This is no longer an issue with the latest Chromium based Edge.
Since the original Edge (EdgeHTML) has been deprecated by Microsoft and it's [end-of-life on March 9, 2021](https://docs.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge#what-is-the-lifecycle-policy-for-microsoft-edge) we will no longer be support the old Edge either.
