### ISSUE TITLE
Running OneSignal as a background webservice or in PWA

### ISSUE THREAD

**Issue by connetcom** [OneSignal/OneSignal-Website-SDK#516]
**Description:**

Hi,

First, thanks on prior responses to other issues.

Question here is whether the OneSignal service worker can continue to run in the background when Chrome is closed. Similarly, if embedded in a PWA, would the PWA wake up based on the receipt of a push notification from OneSignal? Chrome and other browsers have a mechanism to run in the background (e.g., which is on by default and can be blocked from settings, advanced) I realize that this includes some aspects outside of OneSignal per se but stackoverflow, github and general documentation seem relatively contradictory or unclear on these points so any input from you would be highly appreciated.

**Steps to Reproduce Issue:**

Running chrome canary on windows 10 environment.

Launch app in Chrome and subscribe to push notifications, generate a push message from the OneSignal dashboard, push is received and displayed on the screen and click takes to the appropriate browser page.

Close the Chrome browser, generate a push message and it is not displayed until the browser is opened again. 

So, how does one get the OneSignal service worker to remain as an active chrome background process that keeps Chrome running in the background without any pages open.

Thanks,

very much

**Anything else:**
Would this be automatic in the case that the app is bundled in a PWA

**Comment by fatsjohonimahnn** [comment]
Hello

There are a few factors that determine if a notification can be received when the browser is not running or user is offline.

Please see our docs for more detail on this: https://documentation.onesignal.com/docs/notification-delivery#section-do-users-receive-web-push-notifications-when-the-browser-isn-t-running-

Thanks

**Comment by connetcom** [comment]
Thanks but do you have any further info than that or could you point to some sample code or application that does run and receive notifications when chrome is not running - for example, does that pertain to webpush on Android (this seems to work fine) and also on Windows 10? Does some process need to register and run within Chrome to keep Chrome alive in the background (e.g., do we need to create a service worker for this or should it be automatic)?

Thanks

**Comment by rgomezp** [comment]
Hello @connetcom ,
Sorry for the delay. You are correct in your assessment and I will make sure that the documentation gets updated to include this information. Thank you for pointing this out.
- Chrome must be open to receive notifications

Thanks for your patience.
