### ISSUE TITLE
Hosting OneSignal Push myself

### ISSUE THREAD

**Issue by veso266** [OneSignal/OneSignal-Website-SDK#518]
**Description:**

Hi there I was wondering if it is possible to host OneSignal myself in a corporate intranet network (I know I have to use FCM and APN but one service less the better)

I know you make your SDK open-sourced on github which is great, was just wondering if you could maybe make server-side code open source or a minimal example one just to get your OneSignal-Android-SDK up and running with my own BASE_URL something like api.bad-company.com

**Steps to Reproduce Issue:**

A question

**Anything else:**

Thanks for Anwsering and Best Regards

Also how am I supposed to build OneSignal-Android-SDK to get the jar file out, as it build fine but after looking under OneSignal-Android-SDK\app\build\outputs\apk\debu I see app-debug.apk not something.jar file (which I suppose I could then somehow include in OneSignal-Cordova plugin)

**Comment by rgomezp** [comment]
Hello,
Unfortunately, we cannot make our server-side code open-sourced. 

I'm not entirely sure what you mean. If you have Android related questions please create an issue in the appropriate repository with further details and follow the issue template.

Thanks!
