### ISSUE TITLE
"This site has been updated in the background" (Super PWA Conflict Issue with Service Worker)

### ISSUE THREAD

**Issue by alaid** [OneSignal/OneSignal-Website-SDK#519]
**Description:**

Hi

I am using OneSignal with WordPress Plugin OneSignal Push Notifications, I followed the steps in the documentation and the first time the user allows to receive notifications in Chrome and Opera (Desktop and Mobile Version) works perfect, but after the user left the page of the site or closed the browser and opened it again, when sending a message it arrives but showing "This site has been updated in the background".

This occurs in the Chrome browser (Version 74.0.3729.131 (Official Build) (64 bits)) and Opera (Version: 58.0.3135.132) in its desktop and mobile versions.

I tried sending a direct message from the OneSignal dashboard and the same thing happens. I have reviewed the similar issues and I have done different tests and the same thing happens.

![Issue-OneSignal-1](https://user-images.githubusercontent.com/13101624/57582117-d63cd600-748e-11e9-897f-f39f313af779.jpg)
![Issue-OneSignal-2](https://user-images.githubusercontent.com/13101624/57582118-d63cd600-748e-11e9-80d1-e31eed8f9ed1.jpg)

**Steps to Reproduce Issue:**

  1. Visit https://granferiapzo.com
  2. Wait for prompt to appear.
  3. Click Allow.
  4. What information do I have to send so you can do the tests?

**Anything else:**

There are several plugins for push notifications, I chose OneSignal because I consider it excellent and I like it, I would like to be able to work with it.

Thanks

**Comment by rgomezp** [comment]
Please see this [issue](https://github.com/OneSignal/OneSignal-Website-SDK/issues/60) for more information on this issue and provide us with your public URL so we can take a closer look. Most likely, you are running another service worker which is getting overridden by ours.

**Comment by alaid** [comment]
I have reviewed the issue, I have tried in other different servers, in other sites with a basic WordPress and the same thing happens.

My public URL and information are in the previous message with the included images and description of the issue

**Comment by rgomezp** [comment]
@alaid Please take a look at this [integration guide](https://superpwa.com/doc/setup-onesignal-with-superpwa/) for OneSignal + Super PWA

**Comment by rgomezp** [comment]
Closing due to no response
