### ISSUE TITLE
Has SetExternalId a security flaw ?

### ISSUE THREAD

**Issue by valentin-ballester** [OneSignal/OneSignal-Website-SDK#520]
**Description:**

My app works with client and users (clients are packets of users with shared functionallities), the notification send data of events and actions that could be dangerous if anyone outside the client users gain access to (medical records, etc) what i saw when i started reading one signal guides was that you can set the external id from the client side and recieve all the notifications of that id, so a hacker only needs to get the id of one user of one client and can see a lot of the activity of that client. What i decided for the moment is not to use tags or external id's for handling the scope of my notifications and just keep track of the player id in my database. The tags i already read that are dangerous to use with authentification systems but i didnt find no one complaining about the external id. Im i wrong ? thanks. 

pd: the question i have specifically is if i can pretend be another user changing my external id through the browser console with : **OneSignal.setExternalUserId('user_id');** and if i can limit to only set the external user id through the api, thanks. 

**Steps to Reproduce Issue:**

  1. go to a one signal web app that uses external_id
  2. in the console using OneSignal.setExternalUserId('user_id'); pretend to be someone else.

**Comment by rgomezp** [comment]
Hello,
First of all, you shouldn't be sending any sensitive information through push notifications. For example, if you want to notify someone of an update to their medical records, you should send them a notification telling them that there is a new update on their account (not actually updating them through the notification itself). 

Second of all, this shouldn't be a problem unless the external_id is public somehow or is guessable (in a range perhaps). In summary, make sure your external_id is unique, difficult to guess, and your notifications don't include sensitive information.

Thank you for your question
