### ISSUE TITLE
Subscription bell on front page of website has no unsubscribe feature

### ISSUE THREAD

**Issue by steven66** [OneSignal/OneSignal-Website-SDK#522]
Onesignal subscription bell icon all ways shows "subscribe to notifications" even though I have already subscribed. Link as below
https://www.e-car.co.za/
Can you maybe please help me to sort this out. It is a wordpress site. Maybe there is a plugin interfering with onesignal.
Regards
steve

**Comment by rgomezp** [comment]
Hi Steve,
It looks like you're using a PWA plugin that is replacing the OneSignal service worker with its own. Take a look at our [troubleshooting docs](https://superpwa.com/doc/setup-onesignal-with-superpwa/) for information on how to merge service workers and make OneSignal compatible with PWA plugins.

**Comment by rgomezp** [comment]
Closing due to no response
