### ISSUE TITLE
how to deletect blocked users

### ISSUE THREAD

**Issue by bimubuceru** [OneSignal/OneSignal-Website-SDK#525]
**Description:**
i want to show a special message to users who have blocked the web push notification.
i was only able to get state isPushEnabled and isOptedOut

i tried to use if both condition dont satisfy it means user blocked the notification 
but its not working correctly 

i tried this code
                if (state.isPushEnabled) {
// do noting
                } else if(state.isOptedOut) {
// prompt 
} else{
// show user a message that they have blocked the notifications
}

currently i am using 

                if (state.isPushEnabled) {
// do noting
} else{
// show user a message that they have blocked the notifications
}

but it also run else condition for new users who are visit page for the first time 

how to know if user have blocked the notifications ? 

PS 
i use custom link 
i know that bell icon can detect when user block the notification permission 
i want to do that in custom link

**Comment by rgomezp** [comment]
Hello, are you doing this inside `getSubscriptionState()` ?

Example:
```javascript
  function getSubscriptionState() {
        return Promise.all([
          OneSignal.isPushNotificationsEnabled(),
          OneSignal.isOptedOut()
        ]).then(function(result) {
            var isPushEnabled = result[0];
            var isOptedOut = result[1];

            return {
                isPushEnabled: isPushEnabled,
                isOptedOut: isOptedOut
            };
        });
    }
```

**Comment by rgomezp** [comment]
Here's a different example:
```javascript
getSubscriptionState().then(function(state) {
            var buttonText = !state.isPushEnabled || state.isOptedOut ? subscribeText : unsubscribeText;

            var element = document.querySelector(buttonSelector);
            if (element === null) {
                return;
            }

            element.removeEventListener('click', onManageWebPushSubscriptionButtonClicked);
            element.addEventListener('click', onManageWebPushSubscriptionButtonClicked);
            element.textContent = buttonText;

            if (state.hideWhenSubscribed && state.isPushEnabled) {
                element.style.display = "none";
            } else {
                element.style.display = "";
            }
        });
```

**Comment by bimubuceru** [comment]
yup i think i was doing that 
they seems like the code from documentation 

well i solved my problem using "notification.permission" ref: https://developer.mozilla.org/en-US/docs/Web/API/Notification/permission
by using this i can check if user blocked the notification for my domain or not :) 
thanks anyway :)

**Comment by rgomezp** [comment]
No problem!
