### ISSUE TITLE
OneSignal does not with the Brave browser

### ISSUE THREAD

**Issue by jsappme** [OneSignal/OneSignal-Website-SDK#526]
I am integrating OneSignal in my Vue app. it works good with Chrome but I am mainly use Brave and it seems it does not work. Any idea or suggestions?

**Comment by rgomezp** [comment]
Hello,
Thank you for bringing this up. After testing on my mobile Brave app, it appears push has not been set up for the time being. I suggest you bring this up in their [community](https://github.com/brave) to confirm while referencing back to this issue.

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by kiily** [comment]
Hi, is there any chance of having an update on this. It seems Brave is preventing OneSIgnal's worker `js` scripts from loading i.e. `OneSignalSDKWorker.js` and `OneSignalSDKUpdaterWorker.js`. Any idea why this could be?

**Comment by jkasten2** [comment]
@kiily It seems Brave blocks installing the OneSignal service worker file `OneSignalSDKWorker.js`, or at least the `importScripts('https://cdn.onesignal.com/sdks/OneSignalSDKWorker.js');` from it.

I see the following error from the console which I determined the above from. 
```
ServiceWorkerManager.js:341 [Service Worker Installation] Installing service worker failed TypeError: Failed to register a ServiceWorker for scope ('https://onesignal.com/') with script ('https://onesignal.com/OneSignalSDKWorker.js?appId=ab76e2a0-6e87-4143-9b6f-452adb3e0742?sdkVersion=151510'): ServiceWorker script evaluation failed
```

Even when "disabling the shields" by clicking on Brave icon to the left of the Address bar. I recommend reporting this to Brave in hopes they can resolve this problem, at least for when the shields are down.

**Comment by kiily** [comment]
Yeah seems to be what I have observed as well. I'll get in touch with them. Thank you.

**Comment by pandit69** [comment]
Having same issue

```
Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'https://cdn.onesignal.com/sdks/OneSignalSDKWorker.js' failed to load.
    at http://localhost:3000/OneSignalSDKWorker.js?appId=xxxxxx?sdkVersion=151512:1:1
    
[Service Worker Installation] Installing service worker failed TypeError: Failed to register a ServiceWorker for scope ('http://localhost:3000/') with script ('http://localhost:3000/OneSignalSDKWorker.js?appId=xxxxx?sdkVersion=151512'): ServiceWorker script evaluation failed
```

**Comment by rgomezp** [comment]
Separating the issue of it not working even without shields, the core issue is that Brave uses Easy List to block 3rd party scripts. 

From my own conversations with the Brave team, it looks like they will not consider whitelisting certain URLs such as onesignal.com. To fix this, it would need to be removed from Easy List. However, Easy List has a strict policy and will block ANY 3rd party script that does any tracking whatsoever (such as session tracking -- regardless if no PID is collected). So unfortunately this doesn't look like it will be easily resolved.

As an idea, we may be able to develop a "lite" version of the OneSignal SDK in the far future as privacy browsers increase in popularity that provides basic push functionality and not much else.

**Comment by abhagsain** [comment]
@rgomezp It'd be great if we could proxy the request just like an analytics tool called Splitbee does at least for Next.js 
Here's how they do it [Documentation](https://splitbee.io/docs/nextjs-proxy).

**Comment by bnd170** [comment]
Any update about that?

**Comment by rgomezp** [comment]
@abhagsain @bnd170 ,
That might work. I don't think there's anything that is needed to do from OneSignal's side though. Was there anything extra you need to set up this sort of proxy method?

**Comment by cxnky** [comment]
is there any update on this?

**Comment by rgomezp** [comment]
From what I can tell, OneSignal is no longer blocked completely as I see the message received via the console. However, the message is not displaying. 

Testing on [tests.peter.sh](https://tests.peter.sh/push-message-generator/) doesn't appear to work either. So I'm not completely familiar with what Brave is doing behind the scenes, but it appears to me they don't fully support push notifications in general.

**Comment by djmtype** [comment]
After disabling Brave Shields the console error goes away, but there are 40 warnings all pertaining to `SameSite`.

```
Because a cookie’s SameSite attribute was not set or is invalid, it defaults to SameSite=Lax, which prevents the cookie from being sent in a cross-site request. This behavior protects user data from accidentally leaking to third parties and cross-site request forgery.

Resolve this issue by updating the attributes of the cookie:
Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests.
```
I have no idea if this is what prevents OneSignal's alert from working; asking for the user's permission to subscribe.

**Comment by jkasten2** [comment]
> From what I can tell, OneSignal is no longer blocked completely as I see the message received via the console. However, the message is not displaying.
> 
> Testing on [tests.peter.sh](https://tests.peter.sh/push-message-generator/) doesn't appear to work either. So I'm not completely familiar with what Brave is doing behind the scenes, but it appears to me they don't fully support push notifications in general.

On Brave on desktop seems to disable push notifications by default (I don't think this is an issue on Android): 
<img width="635" alt="image" src="https://github.com/OneSignal/OneSignal-Website-SDK/assets/645861/67a8d0b9-0b2f-4942-96bf-efffcc8bff98">

However once you enable this Brave setting on desktop and restart the browser that example push does work on [tests.peter.sh](https://tests.peter.sh/push-message-generator/) does work.

**Comment by rgomezp** [comment]
> > From what I can tell, OneSignal is no longer blocked completely as I see the message received via the console. However, the message is not displaying.
> > Testing on [tests.peter.sh](https://tests.peter.sh/push-message-generator/) doesn't appear to work either. So I'm not completely familiar with what Brave is doing behind the scenes, but it appears to me they don't fully support push notifications in general.
> 
> Brave on desktop seems to disable push notifications by default (I don't think this is an issue on Android): <img alt="image" width="635" src="https://user-images.githubusercontent.com/645861/261822134-67a8d0b9-0b2f-4942-96bf-efffcc8bff98.png">
> 
> However once you enable this Brave setting on desktop and restart the browser that example push does work on [tests.peter.sh](https://tests.peter.sh/push-message-generator/).

Very interesting. It would be nice for this to be default on.

**Comment by jkasten2** [comment]
I created an issue with Brave with the shields down not working:
https://github.com/brave/brave-browser/issues/35461
