### ISSUE TITLE
migrate to buildhub2

### ISSUE THREAD

**Issue by willkg** [OneSignal/OneSignal-Website-SDK#529]
OneSignal-Website-SDK uses Buildhub:

https://github.com/OneSignal/OneSignal-Website-SDK/blob/cece550806d989fafb401329376c5c2188ea8609/build/scripts/FIREFOX_ESR_SCRIPT.sh#L26

Buildhub is deprecated and will be decommissioned in July. See mozilla-services/buildhub#532 for details.

There are API docs here:

https://buildhub2.readthedocs.io/en/latest/user.html

This issue covers migrating to Buildhub2.

**Comment by rgomezp** [comment]
Thanks @willkg ,
We have made a note to do this. Please let us know as soon as you know the exact schedule.
