### ISSUE TITLE
OneSignal.sendSelfNotification() doesn't work when user manually switch notification permission from "Block" to "Allow"

### ISSUE THREAD

**Issue by ltrem** [OneSignal/OneSignal-Website-SDK#533]
**Description:**

Seems like OneSignal might have trouble detecting the browser permission when the user change the notification permission manually from "Block" to "Allow". When trying the "OneSignal.sendSelftNotification()" method, the only way to make it work is to:

1. Set the browser notification permission to "Ask".
2. Trigger the "OneSignal.showNativePrompt()" -> Allow.
3. Only then the "OneSignal.sendSelfNotification()" will work.

When we switch the notification permission manually from "Block" to "Allow", it does not work, and I feel like it should?

**Steps to Reproduce Issue:**

1. Have the browser notification permission to "Block".
2. Manually switch the permission to "Allow".
3. Try the OneSignal.sendSelftNotification().

**Anything else:**

Here's a gif explaining the problem while simultaneously using "new Notification('Hey')" to show "expected" behavior from OneSignal.

![OneSignal_sendSelfNotification_problem](https://user-images.githubusercontent.com/18757060/60280420-e7bc2f00-98d0-11e9-8e35-69a9931d3fa6.gif)

I've tried to find related issue or documentation with no success.

Thank you very much!

**Comment by rgomezp** [comment]
Thank you for your patience while we investigate

**Comment by fatsjohonimahnn** [comment]
Hello, please select "Treat HTTP localhost as HTTPS for testing" in the OneSignal dashboard and add 

`allowLocalhostAsSecureOrigin: true,` to the init call.

More details here: https://documentation.onesignal.com/docs/web-push-options#section-local-testing

**Comment by ltrem** [comment]
@fatsjohonimahnn Both of these configurations are already in place.

**Comment by ltrem** [comment]
@fatsjohonimahnn FYI: We also tested and noticed the same behavior on a production (https) environnement.

**Comment by rgomezp** [comment]
Howdy, could you please provide the url to your production site? You can also contact us directly through our OneSignal.com support channel.

**Comment by rgomezp** [comment]
Update: adding `autoResubscribe:true` to your initialization call should fix the issue.

**Comment by djaffer** [comment]
I am having the same issue. This doesn't work every time I have to change to ask then it works after refresh. It is a nightmare to get this to debug. I wish there was react library.
```
    <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
<script>
  window.OneSignal = window.OneSignal || [];
  OneSignal.push(function(){
    OneSignal.init({
        appId: '',
        allowLocalhostAsSecureOrigin: true,
        autoResubscribe: true,
        autoRegister: true,
        notifyButton: {
          enable: true,
        },
      allowLocalhostAsSecureOrigin: true,
    });
  });
</script>
```
