### ISSUE TITLE
Notifications are not displayed in macOS Opera browser

### ISSUE THREAD

**Issue by kravchenkodev** [OneSignal/OneSignal-Website-SDK#537]
**Description:**

Notifications are not displayed in macOS Opera browser

**Steps to Reproduce Issue:**

1. Visit https://onesignal-macos-opera-test.herokuapp.com/index.html using macOS and Opera browser
2. Wait for OneSignal badge to appear
3. Click OneSignal badge to subscribe to notifications
4. Click Allow button in the native notification prompt 
5. Observe Welcome notification

**Actual Result:**
A welcome push message is received (according to browser logs) but native notification is never displayed.
![Screen Shot 2019-08-20 at 15 20 59](https://user-images.githubusercontent.com/2387193/63346691-38df2100-c35e-11e9-96d6-18b68991ecb1.png)

**Expected Result:**
A welcome push message is received and native notification is displayed in the top-right corner of the screen.

**Anything else:**
A simple demo page has been created to reproduce this issue. https://onesignal-macos-opera-test.herokuapp.com/index.html

This issue has been reproduced on several machines:
1. macOS Mojave 10.14.5, Opera 62.0.3331.119
2. macOS Mojave 10.14.5, Opera 63.0.3368.35
3. macOS Mojave 10.14.6, Opera 63.0.3368.35

**Comment by rgomezp** [comment]
Howdy,
This is not an issue with our SDK. We have already opened a [bug report with Opera directly](https://forums.opera.com/topic/31334/push-notifications-with-requireinteraction-true-do-not-display-on-macos). Please upvote the issue in that forum. We hope they move on this issue soon.

Cheers

**Comment by kravchenkodev** [comment]
@rgomezp Thanks for the quick response!
