### ISSUE TITLE
promptOptions  doesn't work for translation

### ISSUE THREAD

**Issue by AliYmn** [OneSignal/OneSignal-Website-SDK#539]
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
    {% if debug %}
    <script>
    var OneSignal = window.OneSignal || [];
    OneSignal.push(function() {
      OneSignal.init({
        appId: "{{app}}",
        subdomainName: "{{subdomain}}",
        // Your other init options here
        promptOptions: {
            /* Change bold title, limited to 30 characters */
            siteName: 'Orthero',
            /* Subtitle, limited to 90 characters */
            actionMessage: "Orthero",
            /* Example notification title */
            exampleNotificationTitle: 'Orthero',
            /* Example notification message */
            exampleNotificationMessage: 'Orthero',
            /* Text below example notification, limited to 50 characters */
            exampleNotificationCaption: 'Orthero',
            /* Accept button text, limited to 15 characters */
            acceptButtonText: "Orthero",
            /* Cancel button text, limited to 15 characters */
            cancelButtonText: "Orthero",
            autoAcceptTitle: 'Orthero'
        },

      });
      OneSignal.sendTags({
      email: '{{request.user.email}}',
      first_name:'{{request.user.first_name}}',
      last_name:'{{request.user.last_name}}',
      role:'{{request.user.role}}',
      lang:'{{request.user.language}}',
      }).then(function(tagsSent) {
        //console.log(tagsSent);   
      });
      OneSignal.showHttpPrompt();
    });
    </script>

![2019-08-28 13 25 42 den ekran görüntüsü](https://user-images.githubusercontent.com/18416653/63847864-5b44f000-c997-11e9-92c6-c1291874bce7.png)

When i change  promptOptions but it doesn't work.

**Comment by AliYmn** [comment]
When i change custom code in Configure Web Push , my problem fixed :)

**Comment by natterstefan** [comment]
Hi @AliYmn,

> When i change custom code in Configure Web Push 

Does that mean you changed the Integration to Custom Code?

![image](https://user-images.githubusercontent.com/1043668/66922872-2fa1c600-f028-11e9-9c26-8d9489ac7c40.png)

**Comment by AliYmn** [comment]
@natterstefan yes, if you don't change custom code , some properties is in your selected dashboard. 
For example; if you want to translate prompt texts , you must use custom code. Than , write custom properties like this ( in my code ) ;

``` javascript
 promptOptions: {
          /* Change bold title, limited to 30 characters */
          siteName: "{% trans "Orthero Portal" %}",
          /* Subtitle, limited to 90 characters */
          actionMessage: "{% trans "Analizleriniz hazır olduğunda sizi bilgilendirelim mi?" %}",
          /* Example notification title */
          exampleNotificationTitle: "{% trans "Örnek Bildirim" %}",
          /* Example notification message */
          exampleNotificationMessage: "{% trans "Bu bir örnek bildirimdir." %}",
          /* Text below example notification, limited to 50 characters */
          exampleNotificationCaption: "{% trans "İstediğiniz zaman aboneliği iptal edebilirsiniz" %}",
          /* Accept button text, limited to 15 characters */
          acceptButtonText:" {% trans "İzin Ver" %}",
          /* Cancel button text, limited to 15 characters */
          cancelButtonText: "{% trans "İstemiyorum" %}",
          autoAcceptTitle: "{% trans "İzin Ver" %}",
      },
      welcomeNotification: {
        "title": "{% trans "Orthero Portal" %}",
        "message": "{% trans "Abone olduğunuz için teşekkür ederiz." %}",
        // "url": "" /* Leave commented for the notification to not open a window on Chrome and Firefox (on Safari, it opens to your webpage) */
      }
    });

```

Also you can see all properties  in  Prompting categories ;  https://documentation.onesignal.com/docs/permission-requests

**Comment by natterstefan** [comment]
Thank you very much @AliYmn, worked now.
