### ISSUE TITLE
Firefox 72 - The Notification permission may only be requested from inside a short running user-generated event handler.

### ISSUE THREAD

**Issue by ndarilek** [OneSignal/OneSignal-Website-SDK#540]
**Description:**

Getting the previous error in Firefox when calling `OneSignal.showNativePrompt()`. Your docs claim that this function can be called from anywhere, however [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1524619) seems to indicate that as of Firefox 68, this now requires a user gesture. I'm running this method from a button's click handler, so I am indeed calling it from a short-lived event. If I request permissions via `Notification.requestPermission()` from the same context (I.e. literally swapping out one call for the other) I don't get this error.

**Steps to Reproduce Issue:**

1. On Firefox 68 or greater, try calling `OneSignal.showNativePrompt()` from a button's click handler.
2. Assuming you get the error I do, replace the call with `Notification.requestPermission()`.

**Anything else:**

Might be useful to update your docs. I hit this fairly close to Firefox 68's release, but it's been out for a while, and your SDK documentation seems to indicate that this method can be called from anywhere. Unless I'm missing something, this isn't accurate anymore.

Thanks.

**Comment by rgomezp** [comment]
Could you please go into `about:config` and see if your `requireuserinteraction` has a value of `true`?

**Comment by ndarilek** [comment]
It is set to true and marked as default.

**Comment by jkasten2** [comment]
@ndarilek Thanks for the heads up on this, it seems the feature was added in Firefox 68 however it says it is off by default.
https://developer.mozilla.org/en-US/docs/Web/API/Push_API/Best_Practices#Browser_mitigations

We will look into supporting the `requireuserinteraction` flag by showing the OneSignal slidedown/popover prompt in the future.

I tried out Firefox 69, 70, and Firefox 68 ESR and `requireuserinteraction` is `false` and show as default. What specific version and build of Firefox are you testing with?

**Comment by ndarilek** [comment]
Huh, so I've been using the unofficial Firefox Nightly flatpak on 
Fedora, then recently discovered it was no longer updating and that 
Fedora now has a more official flatpak of stable. And, there, it shows 
as false and default with the same batch of extensions.


So I'm genuinely not sure what happened there, and apologies for the 
false alarm. But it definitely didn't detect my Vue button's click 
handler as user interaction, whereas requesting notification permission 
via the native APIs worked just fine. So there's still a potential issue 
in that the context where the call runs isn't registered as user 
interaction for some reason. I'm not sure what the browser's criteria 
for determining that a given callback is user interaction is.


I probably won't be able to debug this issue much further though, since 
we're focusing on email delivery and not in-browser push notifications. 
Apologies for that.

**Comment by jkasten2** [comment]
@ndarilek Thanks for digging in and updating us, good to hear that it doesn't sound like it is enabled by default any official builds.

We will update this thread once we fix the compatibility with the `requireuserinteraction` flag, we don't have an estimate on supporting it at this time.

**Comment by rktyt** [comment]
FYI

OS: MacOS 10.15
firefox developer edition: version 71.0b5 (64bit)

`requireuserinteraction` flag is true by default.

**Comment by jkasten2** [comment]
@rktyt Thanks for the details. It seems Mozilla is going to enable this by default starting with Firefox 72.
https://blog.mozilla.org/futurereleases/2019/11/04/restricting-notification-permission-prompts-in-firefox/

**Comment by NeoTechni** [comment]
Please reconsider. We were using this internally for a notification system at work. Where if agent's left a call waiting too long, it'd notify them as everyone was required to have the website open. Having them edit the about:config settings would be too much for them...
