### ISSUE TITLE
"undefined has no properties" when calling `getTags`

### ISSUE THREAD

**Issue by ndarilek** [OneSignal/OneSignal-Website-SDK#542]
**Description:**

Calling `OneSignal.getTags()` throws the following:

```
TypeError: undefined has no properties OneSignal.js:327:44
```

**Steps to Reproduce Issue:**

1. From an initialized OneSignal app, try running any of the following from a browser console:
```
OneSignal.getTags()
OneSignal.getTags().then(console.log)
OneSignal.getTags(console.log)
```

**Anything else:**

I'm not sure if calls using this method are supported, but `getEmail`, `sendTag` and other functions seem to work. I'm trying to run this from a pushed function as well and getting the same results, so I tried streamlining things a bit and using the console directly. It looks as if the API supports logging, but I'm unclear how to enable it or if it will even help in this case.

Thanks.

**Comment by rgomezp** [comment]
Howdy,
Logging is activated by calling `OneSignal.log.setLevel('trace')`. 

You need to actually pass a function to the getTags() function that does something as so: https://documentation.onesignal.com/docs/web-push-sdk#section--gettags-

**Comment by ndarilek** [comment]
Hmm, the docs also claim it returns a promise, so I thought I could just:


`await OneSignal.getTags()`


Even so, `OneSignal.getTags(console.log)` should work, correct? But 
that's one thing I tried and it throws the error in the subject.


Thanks.

**Comment by ndarilek** [comment]
Here's my log output:

```

Current Page URL: http://localhost:8080/documents/7b0b212e-c0fc-427d-bd65-6758b51c9177 build.umd.js:337
Browser Environment: Firefox 70.0 build.umd.js:337
Called init() . build.umd.js:337
OneSignal: Final web app config: {
    "appId": "747708c5-01f7-4fdc-a1de-e851ebe9de6a",
    "origin": "http://localhost:8080",
    "httpUseOneSignalCom": true,
    "cookieSyncEnabled": false,
    "restrictedOriginEnabled": true,
    "metrics": {
        "enable": true,
        "mixpanelReportingToken": "7c2582e45a6ecf1501aa3ca7887f3673"
    },
    "vapidPublicKey": "BMPM88vNihQ68BGZTgtKgC3hinhePL3n8GEFC6DKbUZBeb4ePkdJayNNc9zD-8C--RYUYEzamsTST6Rhje2T3Fg",
    "onesignalVapidPublicKey": "BMzCIzYqtgz2Bx7S6aPVK6lDWets7kGm-pgo2H4RixFikUaNIoPqjPBBOEWMAfeFjuT9mAvbe-lckGi6vvNEiW0",
    "userConfig": {
        "appId": "747708c5-01f7-4fdc-a1de-e851ebe9de6a",
        "notifyButton": {
            "enable": true
        },
        "allowLocalhostAsSecureOrigin": true,
        "promptOptions": {
            "customlink": {
                "enabled": false,
                "style": "button",
                "size": "medium",
                "unsubscribeEnabled": true,
                "text": {
                    "subscribe": "Subscribe to push notifications",
                    "unsubscribe": "Unsubscribe from push notifications",
                    "explanation": ""
                },
                "color": {
                    "button": "#e54b4d",
                    "text": "#ffffff"
                }
            },
            "slidedown": {
                "enabled": false,
                "autoPrompt": false,
                "actionMessage": "We'd like to show you notifications for the latest news and updates.",
                "acceptButtonText": "Allow",
                "cancelButtonText": "No Thanks"
            },
            "native": {
                "enabled": false,
                "autoPrompt": false
            },
            "autoPrompt": false
        },
        "serviceWorkerParam": {
            "scope": "/"
        },
        "serviceWorkerPath": "OneSignalSDKWorker.js",
        "serviceWorkerUpdaterPath": "OneSignalSDKUpdaterWorker.js",
        "path": "/",
        "autoResubscribe": true
    },
    "enableOnSession": false
} build.umd.js:337
(http://localhost:8080) [Worker Messenger] The page is now controlled by the service worker. build.umd.js:337
(http://localhost:8080) [Worker Messenger] Page is now listening for messages. build.umd.js:337
Called internalInit() build.umd.js:337
[Worker Messenger] [Page -> SW] Unicasting 'GetWorkerVersion' to service worker. build.umd.js:337
[Worker Messenger] Page received message: 
Object { command: "GetWorkerVersion", payload: 150706 }
build.umd.js:337
Incremented page view count to 4. build.umd.js:337
Called sessionInit() build.umd.js:337
Called isPushNotificationsEnabled() . 2 build.umd.js:337
Called isOptedOut() . build.umd.js:337
(Host) » notifyButtonStateChange: 
Object { from: "uninitialized", to: "subscribed" }
build.umd.js:337
Called isOptedOut() . build.umd.js:337
Called isPushNotificationsEnabled() . build.umd.js:337
Not registering for push because the user is subscribed and this is not the first page view. build.umd.js:337
Called isPushNotificationsEnabled() . build.umd.js:337
(Host) » initializeInternal build.umd.js:337
Checking subscription expiration... build.umd.js:337
Subscription is not considered expired. build.umd.js:337
(Host) » initialize build.umd.js:337
Called isPushNotificationsEnabled() . build.umd.js:337
Called getSubscription() . build.umd.js:337
Called getSubscription() . build.umd.js:337
Called getTags("[Function]") . build.umd.js:337
TypeError: undefined has no properties
OneSignal.js:327:44
```

I've switched my calling style to:

```
    window.OneSignal.push(async function()  {
      OneSignal.log.setLevel('trace')
      const tags = await OneSignal.getTags((tags: any) => console.log("Tags", tags))
      console.log("Tags", tags)
    })
```

Any other thoughts on what might be going on here? On a whim I tried delaying `getTags` to see if something wasn't correctly set up, but it doesn't seem to amek a difference.

Thanks.

**Comment by ndarilek** [comment]
Argh, so I'm trying to debug this by creating my own custom builds of 
your library with my own debug logging, but the Docker build process 
gives me the following when I run `yarn build:dev`:


```

Version: webpack 4.4.1
Time: 55ms
Built at: 9/24/2019 5:40:07 PM
ERROR in Entry module not found: Error: Can't resolve 
'/sdk/build/ts-to-es6/src/entries/pageSDKInit.js' in '/sdk'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about 
this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about 
this command.
root@9668d0fbbec9:/sdk#
```


Getting the same errors without the Docker-based build process.


What am I getting wrong now? I thought OneSignal would be easier than 
rolling my own push notifications but am beginning to rethink that. :(

**Comment by rgomezp** [comment]
Sorry, you're right. I'll take a deeper look

**Comment by ndarilek** [comment]
Given that I already have the SDK initialized in my page, how hard would it be to get/send tags via `fetch`? Presumably I have all the tokens/app IDs I'd need via the client instance. All I need to do on the client at this point is tag the user with the specific notifications they're interested in, at which point the backend should do its thing. But I'm blocked if I can't get this working or build the SDK myself to figure out why.

I really need to move forward on this somehow. I sold my clients on OneSignal but we need tags functionality for this particular feature, and I'm surprised that the website SDK neither works nor builds in the official Docker environment.

Thanks a bunch.

**Comment by jkasten2** [comment]
@ndarilek Thanks for reporting the `pageSDKInit.js` issue, it was related to the wrong casing being used so it wasn't an issue for all build environments.
Can you try to run yarn build from the `fix_casing_build_issue` branch on this repo? I created PR #546 to get this into master.

I am not able to reproduce the `getTag` issue you have noted on https://onesignal.com by running the code from the console. I tested Firefox 70.0b9 (64-bit) as noted in your log as well as Chrome 77. Do you have a public domain where you can reproduce the issue?

**Comment by ndarilek** [comment]
Thanks, no public URL unfortunately since we don't yet have a staging 
environment. For the moment I'm trying to use [this API 
call](https://documentation.onesignal.com/reference#view-device) to get 
my device info, which appears to have my tags. I can't figure out my 
player ID, though. How do I get the player ID from the window.OneSignal 
instance? Is it different from my user ID, which I've gotten via 
OneSignal.getUserId() but which doesn't appear to work?



I'll test out the build fixes tomorrow and see if they work. It's 
probably easier for me to debug the API and figure out what's not 
working, but for now I need to ship this, so `fetch` it is.

**Comment by ndarilek** [comment]
Just tested the build system fixes and they worked for me. Thanks! I'll 
see if I can step through the SDK and figure out why this is failing for 
me early next week.

**Comment by ndarilek** [comment]
I was using Firefox Nightly because it seemed to have some added accessibility improvements, but last weekend I downgraded to Stable with a new profile. After that, this plus my other recent issue seem to have gone away. Not sure if I had a bad nightly build, a bad profile or what, but I'm calling this resolved for now. Thanks, and apologies for the noise.
