### ISSUE TITLE
Problems with EMAILS via REST API or Dashboard

### ISSUE THREAD

**Issue by Droppix** [OneSignal/OneSignal-Website-SDK#550]
Hi,

1/ I try to send a mail (template) via dashboard, my subscribe user have a tag "first_name", and my template use this tag on text "Hi {{first_name | default:""}}, but I received mail without tag. 
The tag is visible in my dashboard
Why?

2/ My user can receive mail or a push message, since we have associated an email (with AuthEmailToken), however I need to send only one notification and not an email, I get an error

**My JSON sent by rest api is** 
```{
"headings":{
"en":"Bla Bla",
"fr":"Bla Bla"
},
"contents":{
    "en":"Bla Bla",
    "fr":"Bla Bla"
},
"ios_badgeType":
"Increase",
"ios_badgeCount":1,
"subtitle":{"en":"Bla","fr":"Bla "},
"include_player_ids":["XXXXX-XXXXX"]
}
```
Response of api : (send)
***["Message Emails must have a subject", "Message Email body can not be blank"]***

I would like, choose send mode -> (Push or Mail, or Push and Mail). 
Is Possible ?

Thanks for your response.

**Comment by jfishman1** [comment]
Hello @Droppix 

1 - To better assist you, please contact support@onesignal.com with your OneSignal App Id, Template name and player id you tested with.

2 - The code you provided is correct for sending a push, check that the player_id you added to the "include_player_ids" parameter is a push record and not an email record.

If you are still having issues, please share the player id you tested and link to this github issue in the email.

-------

For others viewing this ticket:

1 - Tag Substitution will work on emails as long as the tags are set correctly on the email record in OneSignal dashboard.

2 - When using "include_player_ids" make sure you set a push record player id when sending a push and an email record player id when sending an email. Email API parameters can be viewed here: https://documentation.onesignal.com/reference#section-email-content

If you target multiple player ids, any records that are not correct will be ignored.

You cannot send an email and a push in the same API call.
