### ISSUE TITLE
Allow customization of HTTP popup text "This website"

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#56]
All the other text in the popup can be customized except for that.

**Comment by jasonpang** [comment]
The text "This website" on the HTTP popup is shown only when the user's Chrome platform settings' *Site URL* field is set to `*`. Normally, instead of "This website", we display the URL entered in the *Site URL* textbox. For a *Site URL* of `*`, we don't know what URL to display and we don't want to display `*` so we display "This website" instead.

The text still should be translatable, but for a large number of users, the actual solution is not to use a *Site URL* of `*`. Instead, the user should enter into their Chrome platform settings their actual site origin.

This issue really only affects HTTP subscription users across multiple origins who need to use `*` for their *Site URL*.

**Comment by alonbilu** [comment]
I'm one of those users... :-(
How about giving us an option (through the init parameters) to hide this line entirely?

**Comment by jasonpang** [comment]
Hey @alonbilu,

Makes sense :) Sorry for the delay in getting back to you.

Fixed by: https://github.com/OneSignal/OneSignal-Website-SDK/commit/dbd63d3082a884be01abe69db07629e4ed121f42
