### ISSUE TITLE
Chrome Desktop with Dev iOS View - TypeError: Cannot read property 'pushNotification' of undefined

### ISSUE THREAD

**Issue by watzak** [OneSignal/OneSignal-Website-SDK#560]
**Description:**

There is an js error when u are visiting following url = https://www.watson.ch/wirtschaft/schweiz/930659620-moebel-pfister-von-xxxlutz-gekauft-schweizer-tradition-geht-nach-oesterreich
in mobile view

TypeError: Cannot read property 'pushNotification' of undefined
    at Function.getSafariNotificationPermission (PermissionManager.js:83)
    at Je.<anonymous> (PermissionManager.js:69)
    at Generator.next (<anonymous>)
    at SubscriptionError.js:3
    at new Promise (<anonymous>)
    at Ye (SubscriptionError.js:3)
    at Je.getReportedNotificationPermission (PermissionManager.js:67)
    at Je.<anonymous> (PermissionManager.js:39)
    at Generator.next (<anonymous>)
    at SubscriptionError.js:3

**Steps to Reproduce Issue:**

1. https://www.watson.ch/wirtschaft/schweiz/930659620-moebel-pfister-von-xxxlutz-gekauft-schweizer-tradition-geht-nach-oesterreich
1. on mobile or with user-agent mobile on chrome developers mode
1. check console output and u will find a js error
![](https://user-images.githubusercontent.com/8505970/67390129-4d2cdd80-f59c-11e9-9fae-433e60d5ae98.png)

**Anything else:**

Thanx for your help in advance ;)

**Comment by jkasten2** [comment]
@watzak Thanks for reporting. Selecting an iOS device (iPhone or iPad) in the Chrome tools ends up mocking the `navigator.userAgent` string to an iOS device, however it does not mock `window.safari` so this error occurs in that testing environment. On a real iOS device in either the Chrome or Safari browser this error does not occur.

This is an error we will be fixing, in the meantime you can use "responsive" or an Android device in the drop down to simulate a non-iOS device to keep it from causing any issues in your mobile testing from a desktop browser.

**Comment by svem1** [comment]
This error occurs in Google Chrome on Windows 10 too (site - https://mygoal.one, need autorize)

InitHelper.js:289 TypeError: Cannot read property 'pushNotification' of undefined
    at Function.getSafariNotificationPermission (PermissionManager.js:83)
    at Re.<anonymous> (PermissionManager.js:69)
    at Generator.next (<anonymous>)
    at tslib.es6.js:65
    at new Promise (<anonymous>)
    at Object.n (tslib.es6.js:61)
    at Re.getReportedNotificationPermission (PermissionManager.js:67)
    at Re.<anonymous> (PermissionManager.js:39)
    at Generator.next (<anonymous>)
    at tslib.es6.js:65
(anonymous) @ InitHelper.js:289
a @ tslib.es6.js:63
Promise.then (async)
c @ tslib.es6.js:64
(anonymous) @ tslib.es6.js:65
n @ tslib.es6.js:61
doInitialize @ InitHelper.js:271
(anonymous) @ InitHelper.js:53
(anonymous) @ tslib.es6.js:65
n @ tslib.es6.js:61
sessionInit @ InitHelper.js:45
(anonymous) @ InitHelper.js:43
r @ tslib.es6.js:62
Promise.then (async)
c @ tslib.es6.js:64
(anonymous) @ tslib.es6.js:65
n @ tslib.es6.js:61
internalInit @ InitHelper.js:29
(anonymous) @ OneSignal.js:224
r @ tslib.es6.js:62
Promise.then (async)
c @ tslib.es6.js:64
r @ tslib.es6.js:62
Promise.then (async)
c @ tslib.es6.js:64
(anonymous) @ tslib.es6.js:65
n @ tslib.es6.js:61
e @ OneSignal.js:188
(anonymous) @ OneSignal.js:227
(anonymous) @ tslib.es6.js:65
n @ tslib.es6.js:61
delayedInit @ OneSignal.js:184
(anonymous) @ OneSignal.js:182
r @ tslib.es6.js:62
Promise.then (async)
c @ tslib.es6.js:64
r @ tslib.es6.js:62
Promise.then (async)
c @ tslib.es6.js:64
(anonymous) @ tslib.es6.js:65
n @ tslib.es6.js:61
init @ OneSignal.js:158
processItem @ ProcessOneSignalPushCalls.js:15
push @ OneSignal.js:625
processAsES6Stub @ ReplayCallsOnOneSignal.js:45
doReplay @ ReplayCallsOnOneSignal.js:10
(anonymous) @ pageSdkInit.js:21
(anonymous) @ pageSdkInit.js:25
i @ bootstrap:19
(anonymous) @ bootstrap:68
(anonymous) @ bootstrap:68

**Comment by BasileusGR** [comment]
Is the issue solved? I have the same problem.

**Comment by weroh** [comment]
Hi, I'm getting the same issue for Chrome Canary / Win10. Are there at least any workarounds for this issue?

**Comment by jkasten2** [comment]
@weroh I updated my https://github.com/OneSignal/OneSignal-Website-SDK/issues/560#issuecomment-547127523 above. Let me know if that covers your question.

**Comment by cyb3rdroid** [comment]
Its bug still actual.

**Comment by bfischer1121** [comment]
@jkasten2 do you think this is ever gonna be fixed?

**Comment by jkasten2** [comment]
This is now fixed in the [151600](https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/151600) release that went out today.
