### ISSUE TITLE
OneSignal is not working after page refresh

### ISSUE THREAD

**Issue by malihassan20** [OneSignal/OneSignal-Website-SDK#564]
**Description:**

We have a website https://doctor.staging.instantconsult.com.au/. The onesignal was working fine yesterday and suddenly it stops working from today. If we clear the cookies and restart the chrome browser it gives us the promt and works for the first time then after refreshing the page it does not even shows the bell icon on the right bottom end. Can nybody help me with this? I have read the troubleshoot guide to resolve the issue but no luck. https://documentation.onesignal.com/docs/troubleshooting-web-push#section-debugging-using-browser-developer-tools

**Steps to Reproduce Issue:**

1. Visit https://doctor.staging.instantconsult.com.au.
  2. Wait for prompt to appear.
  3. Click Allow.
  4. Now refresh the page and you will see that nothing appears.

**Anything else:**

It is not even working on my local setup which was also working fine yesterday. Does it is happening due to chrome latest update? or do I have to update for this in order to make it work properly again?

**Comment by rgomezp** [comment]
Could you please contact us through our official support channel (red bubble in bottom right) on OneSignal.com so we can address your situation directly?

**Comment by malihassan20** [comment]
I have contacted there but it looks the person who replied me didn't even understand the issue completely I'm facing :(

**Comment by malihassan20** [comment]
Can you send me your skype or any other id through which we can have a quick call and I can show you the issue?

**Comment by serkankaya** [comment]
I have same problem... @malihassan20 your link looking work ... how did you fix it ?

**Comment by malihassan20** [comment]
@serkankaya here's what I have done to make it working again.

1) Created new app and get new appId
2) If you are using subdomain in the onesignal init then remove it and set it for HTTPS.
