### ISSUE TITLE
Safari: showSlidedownPrompt() does not ask for Notification permissions upon agree

### ISSUE THREAD

**Issue by dornbirndevelops** [OneSignal/OneSignal-Website-SDK#574]
**Description:**

When using the showSlidedownPrompt method to ask the user for permission, the native Notification permission dialog never appears upon clicking the agree action of the slidedown prompt.

**Steps to Reproduce Issue:**

1. visit a website with OneSignal activated.
2. invoke the `OneSignal.showSlidedownPrompt()` function via browser console, button, on load, etc.
3. click the agree action
4. on Safari, the native Notification permission dialog is not opened at all.

**Sidenote**

The native function supported by most recent browsers works as expected.

```js
// recent browsers I could find except Safari
const permissionPromise = Notification.requestPermission()
permissionPromise.then(console.log)

// Safari (I know it's deprecated)
Notification.requestPermission(console.log)
```

**Question**

I've written a workaround method for `registerForPushNotifications` which overcomes the permission issues while you guys are working on it.
I've seen that `OneSignal.showSlidedownPrompt()` (quickly) returns a promise with undefined as the resolved value. The promise resolves, even before the User has taken any action on the prompt. Is there any way to recognize when and what action has been taken in the slidedown prompt (promise, event, or callback) so I can hook other logic in?

**Comment by rgomezp** [comment]
Hello

For Safari not working, please see our troubleshooting guide for more details: https://documentation.onesignal.com/docs/troubleshooting-web-push#section-safari-troubleshooting
​
If you are still having issues, please reach out to our support channel for further assistance.

**Comment by rgomezp** [comment]
Closing due to no response
