### ISSUE TITLE
OneSignal.isPushNotificationsEnabled() does not work in Safari iframe

### ISSUE THREAD

**Issue by jones-rr** [OneSignal/OneSignal-Website-SDK#578]
**Description:**

code connected to isPushNotificationsEnabled() tries to call IDBFactory.open() which throws a security exception when called inside an iframe in Safari.

**Steps to Reproduce Issue:**

1. a.html:

`<html><body><iframe src=b.html></iframe></body></html>`

1. b.html:

```
<html><body>
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
<script>
var OneSignal = window.OneSignal || [];
OneSignal.push(function() {
	OneSignal.init({
		appId: "...",
	});
	OneSignal.isPushNotificationsEnabled(function(b) {
		console.log ('push enabled: '+b);
	});
});
</script>
</body></html>
```

1. Open a.html in Safari. Open developer tools. In debug panel, put a break point for "All Exceptions".  Reload.
1. Security Exception thrown trying to IDBFactory.open().

**Comment by rgomezp** [comment]
Thank you for reporting

**Comment by jones-rr** [comment]
Note this prevents the solution recommended on your page:

> When user is subscribed to my.example.com, open an iframe to www.example.com. Call OneSignal.isPushNotificationsEnabled() in the iframe, which will return true for this user. Call OneSignal.setSubscription(false) in the iframe to unsubscribe the user from www.example.com, since they are already subscribed to my.example.com.

https://documentation.onesignal.com/docs/web-push-complex-integrations#section-override-subscription-status

Currently we are not sure how to implement OneSignal with a site that uses www1.example.com, www2.example.com, etc. since your recommended solution does not work.

**Comment by ejlocop** [comment]
This is what happens when running my app in the Brave browser. 

![image](https://user-images.githubusercontent.com/12082880/76407455-56410e80-63c6-11ea-92cc-a2975c062803.png)

**Comment by rgomezp** [comment]
@jones-rr , sorry for the delay. Are you still seeing the issue?

**Comment by rgomezp** [comment]
@ejlocop , unfortunately Brave is not currently a supported browser. We hope to add support soon

**Comment by jones-rr** [comment]
@rgomezp last time I checked - yes.  Our site has www1.example.com, www2.example.com, etc. and we are not sure how to implement web push for this case, since the OneSignal recommendation is iframe but that is not supported for Safari.

**Comment by rgomezp** [comment]
@jones-rr ,
Can you confirm your site is HTTP and not HTTPS?

**Comment by jones-rr** [comment]
it's all https

**Comment by rgomezp** [comment]
My mistake. Understood. Can you include a full stack trace that includes more than just the database security exception:?

**Comment by jones-rr** [comment]
@rgomezp see attached
![Screen Shot 2020-04-08 at 4 27 30 PM](https://user-images.githubusercontent.com/32111890/78835530-f5e9c080-79b5-11ea-9467-2a9fb80c1bcc.png)

**Comment by rgomezp** [comment]
Howdy,
Thanks for the screenshot. Would you be willing to share your site URL so we can take a look ourselves?

**Comment by rgomezp** [comment]
Closing due to no response

**Comment by jones-rr** [comment]
You can close it if you want, but whether or not I can publish a live link on our site that you can use to investigate does not mean it's not a bug.  

Reproduce it yourself using the instructions I gave up above.

**Comment by jkasten2** [comment]
Using an iframe to share data between multiple domains an end-user visits isn't going to work any more due to Chrome's [CHIPS](https://developer.chrome.com/en/docs/privacy-sandbox/chips/) / [Storage Partitioning](https://developer.chrome.com/en/docs/privacy-sandbox/storage-partitioning/).
Also, [Safari already does this as well](https://webkit.org/tracking-prevention/).

@jones-rr Is this your use case?
