### ISSUE TITLE
InvalidStateError in Chrome

### ISSUE THREAD

**Issue by menshinobi** [OneSignal/OneSignal-Website-SDK#579]
**Description:**
My console constantly shows error about InvalidStateError from OneSignal Website Push Wordpress plugin. 

I followed the direction and configured everything correctly and this error doesn't go away. Might have something to do with OneSignal itself.

Please see screenshot
https://www.screencast.com/t/8PEvNAsZA

**Steps to Reproduce Issue:**

1. Go to https://sciotocountydailynews.com
2. Open the Chrome console and check

**Comment by minhdq1982** [comment]
We have the same problem.
![image](https://user-images.githubusercontent.com/13147619/71388984-2e46d800-262d-11ea-88b2-63c21e6045e6.png)

**Comment by rgomezp** [comment]
Howdy @menshinobi @minhdq1982 ,
I wasn't able to reproduce the error. I subscribed and was even able to send a selfNotification

**Comment by nashgao** [comment]
I had the same problem as well... when I'm using my dashboard(running on chrome) to push notifications to webapp (running on chrome as well) it triggers this issue but works fine on firefox

**Comment by cwuensche** [comment]
I get this exact same error @rgomezp

**Comment by rgomezp** [comment]
Hello all,
Please include a link to an site actively reproducing the error since I am not able to reproduce it on my side with the above link.

Also, is this affecting functionality? What happens if you reload the page?

**Comment by netizen-ais** [comment]
I get the very same error only when I do a hard reload (Ctrl-shift-r), with or without opening devtools. Normal reload (F5) works.

**Comment by rgomezp** [comment]
This isn't really an issue except for when you hard reload the page. As soon as you do a normal reload, everything works as expected. Therefore, we don't plan to fix this at any time soon since it is such a rare occurrence (low priority).

**Comment by netizen-ais** [comment]
I can understand the low priority label, as this shouldn't affect end users, just developers trying to use the product. I'd suggest adding this as a note on the README at least

**Comment by rgomezp** [comment]
Thanks @netizen-ais for the suggestion. We will consider adding better logging for this

**Comment by manoranjanpanda** [comment]
@rgomezp , I have same problem is showing in console while page hard reload.
![Screenshot by Lightshot](https://user-images.githubusercontent.com/36078483/75143105-70b68f00-571a-11ea-8edc-adc87cbc01c0.png)

**Comment by Asinox** [comment]
Well, here as well +1
