### ISSUE TITLE
OneSignal alongside with Push API 

### ISSUE THREAD

**Issue by praneethfdo** [OneSignal/OneSignal-Website-SDK#583]
**Description:**
I'm trying to use OneSignal push notification alongside with Push API. So added OneSignalSDKWorker.js in angular. Everything works fine except when I send a notification through Push API, the notification appear twice. After some research, I found out that this is because when we add OneSignal service worker, it becomes two service workers with angular service worker. And both of the handle the same notification when received.

(your description here)

**Steps to Reproduce Issue:**

1. Add service worker to angular project and enable push notifications
2. Add WebPush API to the backend project ( Spring boot in my case )
3. Send push notification from backend and observe. ( Notification is shown correctly )
4. Add OneSignal service worker to the angular project 
5. Send push notification from backend and observe. ( Notification is shown twice ) 

**Anything else:**

(any other information here)

**Comment by rgomezp** [comment]
Howdy, please see our documentation regarding merging service workers:
https://documentation.onesignal.com/docs/web-push-setup-faq#section-can-one-signal-integrate-with-another-service-worker-on-my-site-or-a-progressive-web-app

**Comment by praneethfdo** [comment]
@rgomezp Hi, Thanks for the suggestion. I have already integrated OneSignal service worker with the angular service worker in my pwa, And everything is working fine. Except when I send a notification through Push API,  the notification is shown twice and if we remove OneSignal service worker it does not happen.

**Comment by jkasten2** [comment]
@praneethfdo Thanks for the details! When you see two notification do both notifications look the same when you send a notification from outside of OneSignal? Or does it end up showing the last notification you sent from OneSignal then the new contents of the notification you just sent outside of OneSignal? We have fallback code in our SDK that could be re-displaying the cached successful notification from OneSignal that you might be running in to.

Let use if the above is what you are see. We will investigate from our end as well and let you know the findings.

**Comment by rgomezp** [comment]
Closing due to no response
