### ISSUE TITLE
Error 400 after delete user from Onesignal dashboard

### ISSUE THREAD

**Issue by danielerota** [OneSignal/OneSignal-Website-SDK#587]
When you delete a user from OneSignal dashboard, that user cannot resubscribe anymore. PUT request always return 400 error "No user with this id found"

**Steps to Reproduce Issue:**

1. Register user from browser
2. delete user from onesignal dashboard (doesn't matter if user is unsubscribed or subscribed)
3. user cannot resubscribe, 400 given

**Comment by jkasten2** [comment]
@danielerota Thanks for reporting, we are investigating this issue.

**Comment by jkasten2** [comment]
@danielerota This is now fixed in the just released [150713](https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/150713) SDK update. Users updates now successfully update after they visit your site with a new tab or window.
