### ISSUE TITLE
Unable to receive chomre push notification in Samsung duos running Android Kitkat

### ISSUE THREAD

**Issue by kanodia** [OneSignal/OneSignal-Website-SDK#59]
Hello

I have configured my website with one signal push SDK.

When I send notifications, I am able to receive them in all my devices except for Samsung galaxy duos running Android Kitkat.

Is a an android version bug. Are chrome push notification supported in Kitkat?

**Comment by jasonpang** [comment]
Hi there,

Are you using the Samsung-provided browser or specifically Chrome on Android from Google?

**Comment by kanodia** [comment]
Hi

I am using chrome on Android

*Abhishek Kanodia*
Under Graduate Student
BITS Pilani

**Comment by jasonpang** [comment]
Hey Kanodia,

Web push notifications are supported on Chrome on Android v42+.

Could you provide more details? How many times have you consistently experienced this issue? Did you make sure to subscribe first (subscription state isn't shared between Chrome browsers on different devices)?

Could you please check these tips: https://documentation.onesignal.com/docs/website-push-common-problems#my-site-isnt-working-on-my-mobile-phone

**Comment by jasonpang** [comment]
Hey @kanodia,

Let us know if you're still having issues receiving push notifications on a Samsung Galaxy Chrome browser. It should be supported!
