### ISSUE TITLE
Custom Link Button Does Not Display (Create React App)

### ISSUE THREAD

**Issue by kimfucious** [OneSignal/OneSignal-Website-SDK#602]
**Description:**

The custom link button does not display.

**Steps to Reproduce Issue:**

1. Setup site in OneSignal dashboard, using custom code option
2. Use http://localhost:3000 for site url
3. Turn local testing "ON"
4. Add code to `<head>` of `index.html` in the public directory of a React App (see below).  Note that I have set: `unsubscribeEnabled: {true}`
5. Add custom link container to an existing React component (that properly displays other content), using `className` instead of class, like this:
```html
  <div className="onesignal-customlink-container" />
```
6. Open website locally with Chrome or Firefox.

The button is not visible.  

**Anything else:**

- If I view the div element using dev tools, the computed width and height are both set to 0.  No amount of fiddling with styles has any effect.
- The div element itself is empty.  I'm not sure if that's correct or not.
- There is no registered user in the dashboard.
- Chrome notifications for the app are set to (default) ask
- Clearing site data, including cookies, and closing/reopening browsers has no effect
- I *can* get the bell to show by setting `notifyButton : {enable: true}`, but that's not what I want.  Plus the doesn't work all that well, requiring a refresh after subscribing in order to display as subscribed.
- I've not tried to get this working on the production site (with HTTPS) yet.

This seems like it should be really simple, but I seem to be flailing about here.

I've got a feeling that perhaps there is an issue related to how React is (not) rendering the button, but I'm frankly unsure.

Any thoughts on how to further troubleshoot and/or get this working would be much appreciated.

Alternatively, I'd like to create my own button component but I can't seem to find the right documentation with the information I need to do that.  If you could point me there, that would be nice.

**index.html scripts in `<head>`**
```html
 <script
      src="https://cdn.onesignal.com/sdks/OneSignalSDK.js"
      async=""
    ></script>
    <script>
      var OneSignal = window.OneSignal || [];
      OneSignal.push(function() {
        OneSignal.init({
          appId: "id-omitted-intentionally-here",
          notifyButton: {
            enable: false
          },
          allowLocalhostAsSecureOrigin: true,
          promptOptions: {
            customlink: {
              enabled: true /* Required to use the Custom Link */,
              style: "button" /* Has value of 'button' or 'link' */,
              size: "medium" /* One of 'small', 'medium', or 'large' */,
              color: {
                button:
                  "#E12D30" /* Color of the button background if style = "button" */,
                text: "#FFFFFF" /* Color of the prompt's text */
              },
              text: {
                subscribe:
                  "Subscribe to push notifications" /* Prompt's text when not subscribed */,
                unsubscribe:
                  "Unsubscribe from push notifications" /* Prompt's text when subscribed */,
                explanation:
                  "Get updates from all sorts of things that matter to you" /* Optional text appearing before the prompt button */
              },
              unsubscribeEnabled: true /* Controls whether the prompt is visible after subscription */
            }
          }
        });
      });
    </script>
```

**Comment by kimfucious** [comment]
Okay, I believe this has to do with initialization.  At some point while fiddling about, after a screen refresh after subscribing (with the bell) and Allowing notifications in Firebox, the *unsubscribe* button appeared.

![Onesignal](https://user-images.githubusercontent.com/26792769/73134909-baa24b80-406e-11ea-9a22-1f3fee7f4db9.jpg)

I *think* I can work with `window.OneSignal` methods to perhaps make some progress here.  Is this documented anywhere?

**Comment by kimfucious** [comment]
Okay, I've made some progress here:

1.  Removed all OneSignal code from `index.html`, as I only need the code on the page where I have the subscribe/unsubscribe button
2.  Added NPM package, [react-load-script](https://www.npmjs.com/package/react-load-script) 
3.  On page where button is, load OneSignalSDK.js using above script with:
```html
      <Script
        url="https://cdn.onesignal.com/sdks/OneSignalSDK.js"
        onCreate={() => handleScriptCreate()}
        onError={() => handleScriptError()}
        onLoad={() => handleScriptLoad()}
      />
```
4.  The following function runs when the script gets loaded successfully:
```js
  const handleScriptLoad = () => {
    window.OneSignal.init({
      appId: "ONESIGNAL_APP_ID" <= real app_id goes here
    });
    setScriptLoaded(true);
  };
```
5.  The above script sets a state variable: `{scriptLoaded: true}`
6.  The following React `useEffect` hook fires on changes to `scriptLoaded`:
```js
  useEffect(() => {
    if (scriptLoaded === true) {
      const isPushSupported = window.OneSignal.isPushNotificationsSupported();
      setIsPushSupported(isPushSupported);
    }
  }, [scriptLoaded]);
```
So, after all that, I *can* see the button in dev mode (http), with no existing users (in the OneSignal dashboard), notifications set to ask (default) in the browser, and application data cleared.

On initial page load, where the button is, no service workers are shown (in dev tools).

When the subscribe button is clicked,the `OneSignalSDKWorker.js` shows in dev tools as activated and running.

So far so good, but...

There is an error logged in the console:
```console
index.js:1 installWorker - SW's 'controllerchange' fired but no state change!
```
**Current Situation**
1.  The button does not change state to reflect a subscribed stats, and the OneSignal dashboard does not show any user.

2. A hard refresh of the page, results in a user being created in the OneSignal dashboard and the correct button representation of the subscribed status.

Now looking for the step that I'm missing, so as to achieve the desired behavior without a page refresh.

**Comment by kimfucious** [comment]
Still battling with this... and here's some more info.

1. The "bell" suffers the same problem as the custom link button, in that upon subscribing a user for the first time and allowing notifications in the browser prompt, nothing happens in the UI.  The service worker behavior is identical, in that `OneSignalSDKWorker.js` becomes activated.

2. After a hard refresh of the app, both the custom link button works as expected while remaining on the same page.  The button toggles appropriately between subscribe and unsubscribe when clicked upon.  However, navigating away from the page, and returning causes the button to vanish.

I've changed the logic mentioned above to be:

```js
  const handleScriptLoad = () => {
    setScriptLoaded(true);
  };

  useEffect(() => {
    if (scriptLoaded === true) {
      if (!window.OneSignal.initialized) {
        window.OneSignal.init({
          appId: "real_id_goes_here"
        });
        setIsInitialized(true);
      } else {
        setIsInitialized(true);
        console.log("OneSignal Already initialized");
      }
    }
  }, [scriptLoaded]);

  useEffect(() => {
    const setNotificationStatus = async () => {
      try {
        const isEnabled = await window.OneSignal.isPushNotificationsEnabled();
        setIsPushNotificationsEnabled(isEnabled);
      } catch (error) {
        console.log(error);
      }
    };
    const getOneSignalUserId = async () => {
      try {
        const userId = await window.OneSignal.getUserId();
        setOneSignalUserId(userId);
      } catch (error) {
        console.log(error);
      }
    };
    if (isInitialized === true) {
      const isPushSupported = window.OneSignal.isPushNotificationsSupported();
      setIsPushSupported(isPushSupported);

      setNotificationStatus();

      getOneSignalUserId();

      window.OneSignal.on("subscriptionChange", isSubscribed => {
        console.log("isSubscribed: " + isSubscribed);
        setIsSubscribed(isSubscribed);
        setNotificationStatus();
      });
    }
  }, [isInitialized]);
```
One key thing this does is *to not* re-initialize OneSignal if it's already initialized.

**Comment by kimfucious** [comment]
FYI:  I found this [onesignal-web-sdk NPM module](https://www.npmjs.com/package/onesignal-web-sdk), but it doesn't seem operational, and the link to docs is broken.

**Comment by kimfucious** [comment]
I've noticed the following:

With no users in the OneSignal dashboard and a "fresh" browser setup, when the subscribe (custom link) button is clicked, GET requests are made:

`GET: http://localhost:3000/OneSignalSDKWorker.js?appId=APP_ID`

followed by:

`GET: https://cdn.onesignal.com/sdks/OneSignalSDKWorker.js`

These, from what I can tell, import the OneSignalWorker.js script and get the service worker up and running.

Subsequent clicks on the button do nothing (it stays in the unsubscribed state).  As mentioned prior, there's an error in the console:

```console
installWorker - SW's 'controllerchange' fired but no state change!
```

And no user has been created in the OneSignal Dashboard yet.

After a hard-refresh, the custom-link button is visible *in the already subscribed state*, in other words, the buttons says, "Unsubscribe from notifications".

Clicking on the button will issue a PUT to the API that toggles the button between subscribed and unsubscribed.

**Unsubscribe**
```js
{"app_id":"PLAYER_ID","notification_types":-2}
```
**Subscribe**
```js
{"app_id":"PLAYER_ID","notification_types":1}
```

That said, I'm still stuck at the point where a hard page refresh is the only way to get things working.

**Comment by man0s** [comment]
I had the same issue. The workaround is to work with window.OneSignal methods, Hooks and a Button handler.

**Comment by kimfucious** [comment]
Thanks @man0s 

When you say "add a button handler", I assume you mean that you're not using the `one-signal-customlink-container`, which will provide a button.  Instead, you're using your own custom button.  Is that right?

If not, kindly clarify.

If so, then it seems like you'll have needed to write a lot of the functionality that the provided button should (e.g. getting the service worker running).

My hope was to not have to do this, but if it's the only workaround maybe I'll give that a go.

**Comment by kimfucious** [comment]
I had a bit of a breakthrough here, I _think_.

In brief, as I'm using create-react-app, which has a pre-built `serviceWorker.js` file, I started to play around there.

First, I changed out the default `service-worker.js` reference with the `OneSignalSDKWorker.js` (which has been placed in the public directory) in `serviceWorker.js`, like this:

```js
  window.addEventListener("load", () => {
    const swUrl = `${process.env.PUBLIC_URL}/OneSignalSDKWorker.js`;
    ...
```

Then, in `index.js` (the app entry point), I changed the serviceWorker call from `unregister()` to `register()`

Initially, upon restarting the app and heading over to the page where the custom-link button is, there is no change to the behavior; however, *now* upon clicking the button everything *seems* to be working as expected.  

I'm gonna try a few things and report back.

**Comment by kimfucious** [comment]
Okay, this all works smashingly, except for one thing, and I'm probably doing something dumb here, but...

If I navigate away from the page where the button is, and then I come back to that page, the button is not visible...  hmm.

**Comment by kimfucious** [comment]
In the end, I've given up on using the `one-signal-customlink-container` to display the button.

Instead, I've put in my own button(s) and logic to support them via the SDK.

**Comment by taranek** [comment]
Hi, I managed to trigger the prompt by calling:

`window.OneSignal.eventHelper.onSubscriptionChanged_updateCustomLink()`

when parent of `one-signal-customlink-container` mounts, e.g:


```
export const OneSignalCustomLinkContainer = () => {
  React.useEffect(() => {
    window.OneSignal.eventHelper.onSubscriptionChanged_updateCustomLink()
  }, [])
  return <div className="onesignal-customlink-container" />
}

```
I am using `151512` version of OneSignal Web SDK.

**Comment by encryptblockr** [comment]
why did you close this @kimfucious ??? 
issue is not solved; your workaround is not a solution and you closing this stops trying to fix this
others are facing same issue but here you closed the issue

**Comment by jkasten2** [comment]
@encryptblockr Could you create a new issue with additional details on you setup?
