### ISSUE TITLE
OneSignal & Firebase Cloud Function - Returned undefined, expected Promise or value

### ISSUE THREAD

**Issue by keithwang5** [OneSignal/OneSignal-Website-SDK#603]
**Description:**
I'm trying to use Firebase cloud function to trigger a OneSignal push notification whenever a new chat message document is created in Firestore. I followed the instructions on the OneSignal Create Notifications REST API doc.

However, cloud function keeps complaining my function doesn't return a promise or value.

I tried to return the sendNotification function hoping to return the promise, but the same error popped up. 

**Steps to Reproduce Issue:**
  1. I followed the code from https://documentation.onesignal.com/reference#section-send-based-on-one-signal-player-ids-create-notification
  2. In VS code cloud functions, I embedded the code above into an exports Firestore trigger function (code below)
  3. I deployed the function
  4. I then sent a new chat message from my installed app on an actual iPhone 6; no push notification occurred
  5. I checked the Cloud Functions dashboard to see the logs with the "Returned undefined, expected Promise or value" error.

**Log Error Details**
See attached screenshot:
<img width="742" alt="Screen Shot 2020-01-26 at 2 08 27 PM" src="https://user-images.githubusercontent.com/23715950/73131418-89615580-4045-11ea-914e-9c33126ee6b8.png">

**Code**
```javascript
exports.newChatNotification = functions.firestore.
document('channels/{userId}/thread/{docId}').
onCreate((snap, context) => {

  // Get the values of the newly created document
  const newValue = snap.data();

  // Access the "content" field
  const content = newValue.content;
  console.log(content);

  // Access the "userID" field
  const userID = newValue.userID;
  console.log(userID);

  const docId = context.params.docId;
  console.log(docId);

  // OneSignal notification sending
  var sendNotification = function(data) {
    var headers = {
      "Content-Type": "application/json; charset=utf-8",
      "Authorization": "Basic NGEwMGZmMjItY2NkNy0xMWUzLTk5ZDUtMDAwYzI5NDBlNjJj"
    };

    var options = {
      host: "onesignal.com",
      port: 443,
      path: "/api/v1/notifications",
      method: "POST",
      headers: headers
    };

    var https = require('https');
    var req = https.request(options, function(res) {  
      res.on('data', function(data) {
        console.log("Response:");
        console.log(JSON.parse(data));
      });
    });

    req.on('error', function(e) {
      console.log("ERROR:");
      console.log(e);
    });

    req.write(JSON.stringify(data));
    req.end();
  };

  var message = { 
    app_id: "APP_ID",
    contents: {"en": content},
    include_player_ids: ["PLAYER_ID_1", "PLAYER_ID_2"]
  };

  return sendNotification(message);

});
```

**Comment by jkasten2** [comment]
@keithwang5 This issue isn't related to the WebSDK specifically, since it is a OneSignal REST API + Firebase Cloud Function integration question I recommend asking OneSignal support or stackoverflow.

However from a quick look I believe you must return some after `req.end();` based on the error you are getting.

**Comment by Luisquii** [comment]
Did you solve this? if so, can you share your solution? @keithwang5

**Comment by jfishman1** [comment]
Hello, have you tried our Firebase guide: https://documentation.onesignal.com/docs/firebase

Specifically this section on Cloud Functions: https://documentation.onesignal.com/docs/firebase#sending-push-notification-using-firebase-cloud-functions
