### ISSUE TITLE
Investigate supporting the Samsung browser

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#61]

**Comment by alonbilu** [comment]
I've got few reports from Galaxy 6 owners that they don't see the native confirmation dialog... In once case, it did load after a minute of waiting, but most of the time it just doesn't load at all.

**Comment by jasonpang** [comment]
Hey @alonbilu,

I haven't actually started on this issue yet, so I'm not sure how our SDK works in the Samsung browser. We only support the Google Chrome browser at this time, so maybe most of the reported users are using the Samsung browser (which, maybe, doesn't work with our SDK), whereas that one user that got it after a minute of waiting was because his site took a minute to load and he was using a supported browser (see below side note).

Side note: I believe our current SDK version waits until the document fully loads before displaying any prompt. Our next SDK version will not displaying it earlier without waiting as long.

**Comment by jasonpang** [comment]
Web push is supported: http://developer.samsung.com/technical-doc/view.do?v=T000000245&pi=2&ps=10&pb=Y&ct=&sc=, https://jakearchibald.github.io/isserviceworkerready/

**Comment by alonbilu** [comment]
Thanks for the update!

**Comment by jasonpang** [comment]
Also see: https://github.com/web-push-libs/web-push#browser-support

**Comment by jasonpang** [comment]
Fixed by: https://github.com/OneSignal/OneSignal-Website-SDK/commit/1a14c53c2ef6c6913905701a51e7988a52cf1fa8.
