### ISSUE TITLE
Doubt about adding a user

### ISSUE THREAD

**Issue by joaodematejr** [OneSignal/OneSignal-Website-SDK#611]
I'm trying to add a user but says there is no No Push Token, but the return is ok
![Captura de Tela 2020-02-10 às 18 11 21](https://user-images.githubusercontent.com/17418041/74190318-f3c2ea00-4c30-11ea-8fc0-74986a2a7a6f.png)
![Captura de Tela 2020-02-10 às 18 10 02](https://user-images.githubusercontent.com/17418041/74190335-f7ef0780-4c30-11ea-8043-9e9c18589390.png)
![Captura de Tela 2020-02-10 às 18 10 12](https://user-images.githubusercontent.com/17418041/74190337-f8879e00-4c30-11ea-939d-ec462d4fd43c.png)

**Comment by rgomezp** [comment]
Please reach out through our support channel at OneSignal.com for help
