### ISSUE TITLE
Chrome subscribe button still appearing despite subscribed

### ISSUE THREAD

**Issue by mattjudgey** [OneSignal/OneSignal-Website-SDK#612]
**Description:**

Within Chrome, when clicking the subscribe button to be added as a player, the subscribe button does not disappear once the subscription has been confirmed. This issue only appears within chrome, I have tested this in firefox and the subscribe button disappears as expected.

**Steps to Reproduce Issue:**

1. Configure Web Push setup selecting typical setup.
2. Include the following code within JavaScript: 
```
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
<script>
var OneSignal = OneSignal || [];
OneSignal.push(function() {
		OneSignal.init({
			appId: "APP_ID",
			notifyButton: {
				enable: true
			}
		});
	});
</script>
```
3. Include the following code in the html page:
`<div class='onesignal-customlink-container mb-2'></div>`

**Anything else:**

I am using Chrome version 79.0.3945.130.
This works in firefox as expected the issue is only with Chrome.

**Comment by weslei-dias-vakt** [comment]
Also in the same boat, Any updates here?

**Comment by rgomezp** [comment]
I haven't been able to reproduce this. Can you reach out to our support channel with a link to your specific site?
