### ISSUE TITLE
Unsubscribe not working

### ISSUE THREAD

**Issue by weslei-dias-vakt** [OneSignal/OneSignal-Website-SDK#614]
Hey,
i'm trying to setup OneSignal in my React app, to allow the users to receive notifications by web browser.
I want that those users be able to subscribe and unsubscribe. I'm using the same code available at the documentation (https://documentation.onesignal.com/docs/web-push-custom-code-examples#section-custom-link-prompt).
The subscribe is working as expected, but the unsubscribe didn't work.
Any ideas about this?

**Comment by rgomezp** [comment]
Please contact us through our support channel for help with this at onesignal.com
