### ISSUE TITLE
onesignal push notification for web on ios

### ISSUE THREAD

**Issue by novaknole** [OneSignal/OneSignal-Website-SDK#619]
There's no need to follow this template as my issue is something unrelated to it.

I have integrated onesignal into my web app. It's PWA app. Now, push notifications work for most browsers, but not for Safari on iOS device. Is it because Apple didn't anounce support for push notifications on IOS? 

is it even planned? do you happen to know when this feature will be supported?

**Comment by rgomezp** [comment]
That is correct. Currently mobile web push is only for Android devices. Apple has not announced anything yet.

Enjoy!

**Comment by jkasten2** [comment]
This is now supported. Requires installing your site as a Web App, see [Mobile Web Push for iOS/iPadOS](https://documentation.onesignal.com/docs/safari-web-push-for-ios)
