### ISSUE TITLE
Service worker not working properly with ReactJS Application

### ISSUE THREAD

**Issue by Rathpanha** [OneSignal/OneSignal-Website-SDK#629]
### Description

I set up OneSignal using http://localhost:3000 for testing in development and noticed that OneSignal service worker not working properly with ReactJS. Here is the code I put in the head tag of my ReactJS App:
```
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
<script>
  var OneSignal = window.OneSignal || [];
  OneSignal.push(function() {
  OneSignal.init({
    appId: "MY-APP-ID",
  });
});
</script>
```

### Steps to Reproduce Issue
1. When I clicked allow notification, I got this error in console:
![image](https://user-images.githubusercontent.com/24370142/79428605-995b5680-7ff0-11ea-80cd-a6fca9f52166.png)
And I couldn't find subscribed user at the OneSignal admin panel. Of course, because when I inspected the network, **I didn't see** OneSignalAPI sends "players" and "notifications" response back to the client like the image below:
![image](https://user-images.githubusercontent.com/24370142/79429025-31594000-7ff1-11ea-95c8-affa7474f95c.png)

2. I need to refresh the page a few times to get those responses back from the API, but I only got "players" response back from the API. After that, I could see the user in the panel and I could broadcast message to that user normally.

3. Here comes the problem, If I refresh the page few more times, I got this error in console something related to OneSignal can't retrieve the client's device ID and can't continue the session like the image below:
![image](https://user-images.githubusercontent.com/24370142/79430039-8c3f6700-7ff2-11ea-872b-dad54e0697fc.png)
And then, I couldn't broadcast the message to that user anymore and that user **got unsubscribe** automatically(I view in the panel).

### Anything else
Both of my `OneSignalSDKUpdaterWorker.js` and `OneSignalSDKWorker.js` files are in the public folder.
I found this issue [https://github.com/OneSignal/OneSignal-Website-SDK/issues/231](url) from 2017 and tried to execute this code `navigator.serviceWorker.register('/OneSignalSDKWorker.js');` manually after the first step and got "players" and "notifications" responses back from the API  normally in the network console. And then again I still got the issue like the third step.

**Comment by rgomezp** [comment]
Howdy,
Thanks for the information. A couple questions:
1. Are you using a second service worker? If so, you have to [merge them](https://documentation.onesignal.com/docs/onesignal-service-worker-faq#section--integrating-multiple-service-workers-).
2. Can you please turn on OneSignal logging and paste the entire output of the console here? You can enable debug mode with `OneSignal.log.setLevel('trace');`

**Comment by Rathpanha** [comment]
Hello, sorry for the late reply.

The problem is ReactJS service worker conflicts with OneSignal.  We can do something just like you [suggest](https://documentation.onesignal.com/docs/onesignal-service-worker-faq#section--integrating-multiple-service-workers-). Doing that is not easy, because of ReactJS service worker auto-generate from the build and it hards to merge the two of them.

To solve that problem, I just create another app with simple HTML with another subdomain and let user register to that domain instead.

**Comment by rgomezp** [comment]
Howdy @Rathpanha ,
Okay. Don't hesitate to reach out if you have any further questions at OneSignal.com through our support channel. Cheers
