### ISSUE TITLE
setSubscription(true) bug after unblocking in browser, UUID not working

### ISSUE THREAD

**Issue by kfe908** [OneSignal/OneSignal-Website-SDK#635]
We get grey hair using OneSignal Web SDK and play around with special user events like:

1. Browser Chrome (Version 81.0.4044.11)
2. Registering with OneSignal UUID
3. Notification works fine
4. Blocking Notification in Chrome
5. Status for UUID is Unsubscribed
6. Allow Notifications in Chrome, got same UUID from OnesignalSDK, setSubscription(true)
7. In OneSingal Backend User is Subscribed again
8. Sending Notification, OneSignal says "success", no message delivered
9. Sending second notification, OneSignal says "error", user unsubscribed

Gaining a new OneSignal UUID when user changed from "blocking" to "allowed" using

OneSignal.provideUserConsent(true);

does not work as well, still get same UUID (also after 10 seconds waiting time)

This might be a bug or does anybody has a solution of this, getting an a user subscribes when the browser status changed from blocked to allowed (a) using the same UUID or (b) gaining a new UUID

**Comment by rgomezp** [comment]
Howdy,
Are you using `autoResubscribe` set to `true` in your dashboard or [initialization](https://documentation.onesignal.com/docs/web-push-sdk#init)?

**Comment by kfe908** [comment]
Yes, we did both. The same outcome.

**Comment by kfe908** [comment]
Could you confirm this bug and fix it?

**Comment by rgomezp** [comment]
This is reproducible, but it's not a bug. You need to refresh the page as chrome indicates between permission changes. Hope that helps.

**Comment by kfe908** [comment]
Yes, of course the site has been refreshed  - the same issue.

**Comment by kostiantyn-solianyk** [comment]
so, any updates? same issue
