### ISSUE TITLE
"Cannot read property 'controller' of undefined" on HTTP 

### ISSUE THREAD

**Issue by TheMacros** [OneSignal/OneSignal-Website-SDK#638]
**Description:**

I have an error "Cannot read property 'controller' of undefined" in developer console. I'm using http connection. This error appear in Chrome only. Also user is not subscribed after click **subscribe** and **allow push notifications** in popup window
https://media.areama.net/uploads/2020-05-05_130505.png

**Steps to Reproduce Issue:**

1. Visit http://www.ecigarettesmaroc.com/2019/fr/
2. Wait for prompt to appear.
3. Click Allow.
4. Observe issue.

**Comment by rgomezp** [comment]
Please reach out to OneSignal support channel for these types of issues in the future. But it looks like your site is not on HTTP which could be the source of the problem.
