### ISSUE TITLE
Blocked Frame Origin + 403 forbidden

### ISSUE THREAD

**Issue by Gustavo-Stein** [OneSignal/OneSignal-Website-SDK#639]
**Description:**

Trying to setup in a php project, but always show errors in console:

A cookie associated with a cross-site resource at http://onesignal.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
VM1513:1 Uncaught DOMException: Blocked a frame with origin "https://onesignal.com" from accessing a cross-origin frame.
    at <anonymous>:1:16
(anonymous) @ VM1513:1
1.js:60 GET https://s3-us-west-2.amazonaws.com/mfesecure-public/host/v2.ajudabrasil.net/client.json?source=jsmain 403 (Forbidden)
get_json @ 1.js:60
load_config @ 1.js:45
init @ 1.js:2
(anonymous) @ 1.js:65
1.js:46 trustedsite-tm-main[config][403]
1.js:105 GET https://s3-us-west-2.amazonaws.com/mfesecure-public/host/v2.ajudabrasil.net/client.json?source=jsinline 403 (Forbidden)
get_json @ 1.js:105
load_config @ 1.js:91
init @ 1.js:67
(anonymous) @ 1.js:109
1.js:92 trustedsite-tm-inline[config][403]
inicio:34 [Violation] 'setInterval' handler took 72ms

(your description here)

**Steps to Reproduce Issue:**

1. (your steps here)
2.
3.

**Anything else:**

(any other information here)

**Comment by rgomezp** [comment]
Howdy,
For these type of site-specific issues, I'd encourage you to reach out through our support channel at OneSignal.com so we can look at your site more specifically.

I'll close the issue here since you don't have the URL listed but please don't hesitate to reach out. We're happy to help.
