### ISSUE TITLE
Setting one  signal on multiple subdomains

### ISSUE THREAD

**Issue by lmatab** [OneSignal/OneSignal-Website-SDK#642]
**Description:**

I am trying to set up my website like so: https://github.com/OneSignal/OneSignal-Website-SDK/wiki/Set-up-web-push-on-a-custom-HTTPS-subdomain

it just does not work, I wanted to know if those scripts still working or there has been a change in your core.

**Steps to Reproduce Issue:**

 I follow the instruction step by step and just do not work, on the subdomain.site.com it says that ```Uncaught (in promise) p: OneSignal: This web push config can only be used on site.com```

**Comment by rgomezp** [comment]
Howdy, 
Unfortunately, subdomains are considered part of the site "origin" so if you would like to do this, you will have to set up multiple OneSignal applications, each with their own app_id and unique origin. Hope this answers your question.
