### ISSUE TITLE
Change/Hide site URL or from push notification appearance

### ISSUE THREAD

**Issue by sebiskver** [OneSignal/OneSignal-Website-SDK#647]
On my project i want to hide or change Site URL in browsers default look, is it possible to do it?  Is it  unchangeable behavior?

Take a look in this link. I want to change or hide underlined URLs

[https://i.ibb.co/s2KJdKT/37d6fda-88dd83b-Example-Web-Push.png](https://i.ibb.co/s2KJdKT/37d6fda-88dd83b-Example-Web-Push.png)

**Comment by rgomezp** [comment]
Howdy,
This is not possible to modify. It is set by the browser for security reasons so users know which site is sending the push notification.

Cheers
