### ISSUE TITLE
OneSignalError.js:18 Uncaught (in promise) InvalidStateError: The current environment does not support this operation.

### ISSUE THREAD

**Issue by hosnyben** [OneSignal/OneSignal-Website-SDK#648]
Hello,
Onesignale for web browser doesn't work for mobile devices. So to try to investigate that's what i did.

1- Visit my website https://niswa.ma
2- Changed my user agent to "Chrome, iphone"
3- I got an error in my log which is the following 

`OneSignalError.js:18 Uncaught (in promise) InvalidStateError: The current environment does not support this operation.`

Thank you

**Comment by rgomezp** [comment]
Howdy, 
Unfortunately, Apple currently doesn't support Web Push.

You can read more about [this topic ](https://onesignal.com/blog/will-apple-ever-introduce-push-notifications-for-the-open-mobile-web/)on our blog. Cheers
