### ISSUE TITLE
OneSignal API callbacks not invoked when SDK is loaded lazily by angular(webpack) application

### ISSUE THREAD

**Issue by mbratoev** [OneSignal/OneSignal-Website-SDK#649]
Lazy loading of OneSignal SDK (by injecting the corresponding script tag into the document) inside Angular CLI application leads to malfunction of subsequent API invocations. 

Namely, callbacks supplied to API calls such as OneSignal.getUserId() are never invoked (and the returned promises are never resolved/rejected). Functions supplied to OneSignal.push() calls are not invoked once the SDK is loaded. There are no errors or exceptions in the browser console.

When the script tag for OneSignal SDK is directly inserted inside the html file loaded by the browser the problem is not observed.

On the other hand lazy loading works properly when implemented with a plain javascript code i.e. when Angular is not involved.

**Comment by rgomezp** [comment]
Howdy,
Please make sure to follow our issue template.

Thank you
