### ISSUE TITLE
WorkerMessenger.js:118 Uncaught (in promise) TypeError: Cannot read property 'controller' of undefined

### ISSUE THREAD

**Issue by farazkhanpush** [OneSignal/OneSignal-Website-SDK#651]
**Description:**

Good evening-Sorry for my poor english, I have tried to setup an app using "Typical Setup" guide lines for a website that is built using php on my local. The problem is, it just throwing a JS error that I have mentioned in the title. I have tried fire fox and chrome both but the issue is coming at the same line of code which is mentioned below
        navigator.serviceWorker.controller.postMessage({
            command: command,
            payload: payload
        });

**Steps to Reproduce Issue:**

1. Visit http://local-example.com
  2. Wait for prompt to appear.
  3. Click Allow.
  4. Observe issue in the console saying can't read property 'controller' of undefined.
  5. It just throwing same error couple of times

**Anything else:**

On fire fox the error message is different but looks like technically same, the error message can be read as "TypeError: navigator.serviceWorker is undefined"

**Comment by rgomezp** [comment]
Howdy, 
I was not able to reproduce this issue. Do you have further details or perhaps a test site that reproduces this?

**Comment by farazkhanpush** [comment]
Hi,

Ok so as I mentioned above, I am trying to configure one signal on my local php application. The problem is when I click on the allow the notification then I noticed a js error which comes multiple times as the service worker associated with the app is not found I guess. For more clarity I am attaching a screen shot of cookie related warning and the js error associated with the one signal configuration.
<img width="1440" alt="Screenshot 2020-06-29 at 7 32 35 PM" src="https://user-images.githubusercontent.com/35764122/86016031-f1c2c180-ba3f-11ea-9b9f-fff406410c1c.png">

**Comment by rgomezp** [comment]
Howdy, I see that your site says "Not Secure." Please set up HTTP or HTTPS.[ Learn more here.](https://documentation.onesignal.com/docs/web-push-http-vs-https#faq)

**Comment by farazkhanpush** [comment]
Ok but as far as I can see you provide alternative solution for non-https sites which is by sendin notifications from a subdomain of your site, .os.tc which is https site. I set "label" option while setting up the app but don't know what is still missing

**Comment by rgomezp** [comment]
Howdy,
You need to set up HTTP at a minimum on your site to be able to use our HTTP SDK with the workaround you mention above.

**Comment by rgomezp** [comment]
Closing due to no response
