### ISSUE TITLE
Problem widh Website SDK (OneSignalSDKStyles.css)

### ISSUE THREAD

**Issue by mastronicola** [OneSignal/OneSignal-Website-SDK#667]
**Description:**
There is a problem with sdk/css.

On chrome
https://onesignal.com/sdks/OneSignalSDKStyles.css?v=1 marked as 404

On firefox
https://onesignal.com/sdks/OneSignalSDKStyles.css?v=1
it seems that the css file is missing "X-Content-Type-Options"  - "text / plain" header

If i remove ?v=1 the css load correctly.

![today_onesignal](https://user-images.githubusercontent.com/3090641/87143691-c98c5b80-c2a6-11ea-8f1f-22d49dd303fd.png)

![onesignal_firefox](https://user-images.githubusercontent.com/3090641/87144627-571c7b00-c2a8-11ea-9513-810c14303091.png)

**Steps to Reproduce Issue:**
1. Disable all your extension 
2. Visit https://www.fuelsystem.it/
3. Open Chrome Inspector 
4. Open Console

**Comment by jorgeibanez-ibasoft** [comment]
I have the same problem.

![error](https://user-images.githubusercontent.com/58577690/87171850-e5890080-c298-11ea-862d-14d617216c15.jpg)

Website link: https://kid.ibasoft.com.co/presencia/kontrolid

**Comment by jkasten2** [comment]
Thanks for reporting, the css file at https://onesignal.com/sdks/OneSignalSDKStyles.css?v=1 is now loading correctly again.

**Comment by jorgeibanez-ibasoft** [comment]
Hello,

Does not apply styles correctly.

Google Chrome:

![image](https://user-images.githubusercontent.com/58577690/87190995-285ad080-c2b9-11ea-9a16-9fabe494239c.png)

Firefox:

![image](https://user-images.githubusercontent.com/58577690/87191022-33adfc00-c2b9-11ea-9e0d-64d1e40b4020.png)
