### ISSUE TITLE
Onesignal is completely blocked from AdBlockers

### ISSUE THREAD

**Issue by rohitcoder** [OneSignal/OneSignal-Website-SDK#677]
**Description:**
First i can see https://cdn.onesignal.com is blocked from AdBlockers, that why it can't load any JS files from that origin.
![Screenshot 2020-07-27 at 2 18 53 PM](https://user-images.githubusercontent.com/17665703/88522534-1cd70b80-d014-11ea-943c-1655137a0646.png)
I search related issues and i found this one https://github.com/OneSignal/OneSignal-Website-SDK/issues/371 and it wasn't useful for me.

I tried hosting these JS files on my origin (Copied all contents of ```https://cdn.onesignal.com/sdks/OneSignalSDK.js``` and hosted it in my own server then got same blocked issue with ```OneSignalPageSDKES6.js``` page then i also hosted this same file on my server and change its path from ```OneSignalSDK's``` JS code.

After that it again, blocked other XHR / Ajax requests which was made to Onesignal. Is there any method we can solve this these stuffs? After watching previous closed issue, i don't have any idea i would be able to get a good answer or not, we were using Core Firebase service and we shifted to Onesignal one month back and now this is happening, we can't ask our usrs to whitelist our website,or disable AdBlockers.

(your description here)

**Steps to Reproduce Issue:**

  Example:

  1. Install OneSignalSdk on a website and visit that page with AdBlocker extension https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom
  2. Look at browser console, Onesignal is blocked.

**Comment by jkasten2** [comment]
@rohitcoder This was due to onesignal.com being incorrectly added to the EasyList source that most ad blockers use as a blocklist. The issue has been resolved.
https://github.com/easylist/easylist/issues/5776

**Comment by verificatorrus** [comment]
Hello everyone! I faced this problem too and have a working solution. I created a proxy for CloudFlare workers.
https://github.com/verificatorrus/onesignal-proxy
