### ISSUE TITLE
Does not work in any browser with uBlock - no prompt in Safari 13.1 at all

### ISSUE THREAD

**Issue by iongion** [OneSignal/OneSignal-Website-SDK#689]
**Description:**
I have an wordpress website, configured everything properly, as documented.
Made setup on onesignal for all browser + safari and then brought the settings inside wordpress plugin configuration.

**Steps to Reproduce Issue:**

1. Visit http://golflln.com with Safari 13.1 or any of the browser above with uBlock
1. Wait for prompt to appear.
1. Nothing shows
1. If you whitelist onesignal.com in ublock, then the prompt window will show
1. In Safari nothing works

**Anything else:**

I've read about a miss-report of onesignal as tracking domain in EasyList and that it was removed and fixed.
I have purged all lists and updated uBlock, still, I had to manually whitelist it. Maybe onesignal is now in other lists too ?!

Another issue in Chrome (on MacOS Catalina) is that if one closes the prompt from the close window button, without selecting anything, then next retrying, after clicking on the bell icon, the prompt window will open, but will be completely empty / white. If Chrome gets closed completely with CMD+Q, then the window will show fine again(until clicking that close red button of macos native window prompt)

https://streamable.com/5jylw1

**Comment by verificatorrus** [comment]
Hello everyone! I faced this problem too and have a working solution. I created a proxy for CloudFlare workers.
https://github.com/verificatorrus/onesignal-proxy

**Comment by rgomezp** [comment]
Thanks @iongion @verificatorrus 

Unfortunately, we don't have any control over whether or not some of these block lists add OneSignal or not. We have tried to get them to remove us but they consider our services tracking services.

I was unable to see the streamable video. I also know this is a very late reply so please provide an update on whether this is still an issue. Cheers.

**Comment by rgomezp** [comment]
Closing for now. Please leave a comment if you are still seeing this issue and we can reopen
