### ISSUE TITLE
ServiceWorker is too intrusive

### ISSUE THREAD

**Issue by nseb** [OneSignal/OneSignal-Website-SDK#691]
**Description:**

Your ServiceWorker is too intrusive with existing service workers, I have a project using vuejs and quasar, with workbox, I just wish I could use your product, but your service worker integration is too intrusive. There is no solution to integrate into an existing service worker, quite simply?

**Steps to Reproduce Issue:**

1. (your steps here)
1. 
1. 

**Anything else:**

(any other information here)

**Comment by jkasten2** [comment]
We made an improvement in version 151300 where OneSignal no longer requires control of the page. 
https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/151300

This is much less intrusive but OneSignal still uses the root scope for it's ServiceWorker by default to not break any existing setups that may already depend on that. We will be providing more details on how to migrate OneSignal off the root scope seamlessly soon.

**Comment by jkasten2** [comment]
@nseb We have guide for those who have already setup OneSignal on a live site and need to migrate OneSignal off the root scope.
* [Service Worker migration guide](https://documentation.onesignal.com/docs/onesignal-service-worker-faq#service-worker-migration-guide
)

For those who are just setting up OneSignal or are still in the testing phase (100 or less uses as a ruff estimate) follow this section.
1. [OneSignal Typical Setup](https://documentation.onesignal.com/docs/web-push-typical-setup) - If you haven't done so already.
2. [How Do I Integrate OneSignal's Service Worker Files?](https://documentation.onesignal.com/docs/onesignal-service-worker-faq#how-do-i-integrate-onesignals-service-worker-files)
