### ISSUE TITLE
OneSingal CDN speed is worst

### ISSUE THREAD

**Issue by rohitcoder** [OneSignal/OneSignal-Website-SDK#692]
Hi, i've been noticing this speed since last 1 months, this is really annoying me.

![image](https://user-images.githubusercontent.com/17665703/91529317-af760d80-e926-11ea-8396-0afdb2b04726.png)

1.1 min to load a javascript file? and all others script load so fast.

**Comment by jkasten2** [comment]
@rohitcoder This https://cdn.onesignal.com/sdks/OneSignalPageSDKES6.js should be loading very quick as it is served via CloudFlare cache. The DNS should be picking a very close server based on this, however even was a server far away it would only be in the few 100ms realm so not a real factor here.

Can you hover over the Waterfall entry for `OneSignalPageSDKES6.js` to give a breakdown there? The color looks like a stall but would like to confirm.
Please also show any other requests that match a simplair stall pattern.

Also see the following Google doc on debugging stalls as you may find the the related issue from this guide.
https://developers.google.com/web/tools/chrome-devtools/network/understanding-resource-timing

**Comment by rohitcoder** [comment]
For now, this loads in 1.69 Seconds but sometimes it takes really a long time.

![Screenshot 2020-09-05 at 1 27 50 PM](https://user-images.githubusercontent.com/17665703/92300817-9a7b2900-ef7b-11ea-9f20-2b901d763bac.png)

**Comment by jmadler** [comment]
Can you please provide a [har file](https://developers.google.com/web/tools/chrome-devtools/network/reference#save-as-har)?

**Comment by rohitcoder** [comment]
@jmadler For now this request takes only 118 to 120 ms, i'll re-open this thread with har files attached or any other logs, if i face same problem again.

**Comment by jmadler** [comment]
Ok Rohit, thanks for the update.
