### ISSUE TITLE
React notification works only time when permission is set ask in Chrome

### ISSUE THREAD

**Issue by djaffer** [OneSignal/OneSignal-Website-SDK#705]
I am having the same issue. This doesn't work every time I have to change notification permission to ask then it works after refresh. It is a nightmare to get this to debug. 

```
     <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
<script>
  window.OneSignal = window.OneSignal || [];
  OneSignal.push(function(){
    OneSignal.init({
        appId: ',
        allowLocalhostAsSecureOrigin: true,
        autoResubscribe: true,
        autoRegister: true,
        notifyButton: {
          enable: true,
        },
    });
  });
</script>
```

Some issue similar to this I found https://github.com/OneSignal/OneSignal-Website-SDK/issues/533
![bug-onesignal](https://user-images.githubusercontent.com/5740725/93934484-da1a7280-fce8-11ea-8b12-7a60ef0e2dd7.gif)

**Comment by Andrewpfb** [comment]
Hello.
I faced a similar problem. If you call the "unregister()" method, try removing it.

**Comment by simonare** [comment]
Hi,

I am having same issue. We couldn't able to solve it. Any suggestions?

**Comment by djaffer** [comment]
The issue was ServiceWorker not being loaded. Make sure you import these. Hopefully it will resolve the issue.

https://documentation.onesignal.com/docs/onesignal-service-worker-faq
