### ISSUE TITLE
React installWorker - SW's 'controllerchange' fired but no state change!

### ISSUE THREAD

**Issue by zhengissov** [OneSignal/OneSignal-Website-SDK#710]
**Description:**

On react project there is an error displayed on console:
React installWorker - SW's 'controllerchange' fired but no state change!

**Comment by quarryman** [comment]
Having the same issue.

**Comment by haroldh17** [comment]
Same issue here too! Anyone?

**Comment by jkasten2** [comment]
Thanks for reporting, this is now fixed in version 151300 and has been deployed to cdn.onesignal.com.
https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/151300
