### ISSUE TITLE
setEmail() creates an email record in OneSignal but does not take external user id into account if its already set.

### ISSUE THREAD

**Issue by grevolution** [OneSignal/OneSignal-Website-SDK#712]
**Description:**

setEmail() creates a different player record on OS but does not set external user id if you have already set it via calling setExternalUserId(). Becuase of this, we cannot use external user id to send the email using the create notification API.

**Steps to Reproduce Issue:**

1. Initialize the SDK using the initialize method.
1. Subscribe to push notifications.
1. Call setExternalUserId() to set the external user id.
1. Call setEmail() to set the email for the user.

Look on the OneSignal portal under Audience. You'll see 2 records beign created, One for Web Push notification and another for email. But external user Id will not be set on the email record.

**Comment by grevolution** [comment]
solution proposed in #713

**Comment by rgomezp** [comment]
Howdy,
You are correct. Thank you for surfacing this and creating a PR for it.

**Comment by jkasten2** [comment]
This is now fixed in PR #797 and has been released in version [151403](https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/151403).
