### ISSUE TITLE
Wrong notification permission value (http)

### ISSUE THREAD

**Issue by rjcpereira** [OneSignal/OneSignal-Website-SDK#717]
**Description**

Wrong Notification permission value when called `OneSignal.getNotificationPermission()` method, after remove manually from Chrome's notifications settings on a HTTP config:

`OneSignal.getNotificationPermission(res => console.log(res));`, returns **"granted"**.

If I try to call `Notification.permission` on the **MY_SITE.os.tc** domain, it returns: **"default"**.

The value only gets updated if I call the `OneSignal.registerForPushNotifications();` method.

If the user still have the Cookies, Database and Storage data, but it have deleted the browser permission, there is any way to know that? I cant call the `OneSignal.registerForPushNotifications();` every time.

**Steps to Reproduce Issue:**

[Firefox](https://youtu.be/WLO-T313UD4)

[Chrome](https://youtu.be/AdTEndES2vU)

**Example**
[https://rjcpereira.com/one-signal/http.html](https://rjcpereira.com/one-signal/http.html)

**Comment by RicardoJCP** [comment]
[Firefox](https://youtu.be/WLO-T313UD4)

[Chrome](https://youtu.be/AdTEndES2vU)

**Comment by devpato** [comment]
This is a bug with Chromium (Google Chrome) we have reported the issue to them.

https://bugs.chromium.org/p/chromium/issues/detail?id=1194658

**Comment by rgomezp** [comment]
Since this is not a OneSignal, bug, we can close here and track via Google (above).
