### ISSUE TITLE
cdn.onesignal.com is on the "Peter Lowe’s Ad and tracking server list"

### ISSUE THREAD

**Issue by ssherar** [OneSignal/OneSignal-Website-SDK#720]
**Description:**

Following on from #677 the `cdn.onesignal.com` domain is getting blocked by other ad lists, specifically the `Peter Lowe’s Ad and tracking server list`

* which is one of the main lists shipped with typical ad blockers such as uBlock Origin, PiHole and others. 

Below is the report from uBlock Origin showing the match, and doing a quick search across [the list generator](https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1) you can see it's matched as well.

```
Filter
||cdn.onesignal.com^
Filter list
Peter Lowe’s Ad and tracking server list 
Type
script
URL
https://cdn.onesignal.com/sdks/OneSignalSDK.js
```

Has anyone followed up on this list to take it off and looked into the reason why it was on there in the first place? 

**Steps to reproduce:**

1. Download the latest ad block list from https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1
1. Grep across to find `cdn.onesignal.com`
1. If exists, then any ad blockers using it as a dependency will fail to load the SDK.

**Comment by jmadler** [comment]
Hi Sam!

I've reached out to Peter Lowe who believes this is an accurate classification according to his policy: https://pgl.yoyo.org/as/policy.php

Please follow-up with him if appropriate.

**Comment by verificatorrus** [comment]
Hello everyone! I faced this problem too and have a working solution. I created a proxy for CloudFlare workers.
https://github.com/verificatorrus/onesignal-proxy
