### ISSUE TITLE
Firefox set user as Not Subscribed when it's not

### ISSUE THREAD

**Issue by rjcpereira** [OneSignal/OneSignal-Website-SDK#721]
**Description:**
The browser permission is Allow, it returns permission "granted" and subscription enabled from OneSignal SDK, but its marked as "Not Subscribed" in the OneSignal Dashboard

(your description here)

**Steps to Reproduce Issue:**
[https://youtu.be/9V-Ggm7hYlg](https://youtu.be/9V-Ggm7hYlg)

**Example**
[https://rjcpereira.com/one-signal/http.html](https://rjcpereira.com/one-signal/http.html)

**Comment by jmadler** [comment]
Thanks for the bug report, we'll take a look.

**Comment by rgomezp** [comment]
Howdy @rjcpereira ,
Sorry for the delay. Were you able to resolve the issue? I recommend reaching out to our support channel at onesignal.com for issues like this.

Cheers
