### ISSUE TITLE
Detect Updated ServiceWorker for reload app

### ISSUE THREAD

**Issue by nseb** [OneSignal/OneSignal-Website-SDK#724]
Hello,

in my PWA , I have a registrationservice worker to display a message for notify user to reload app for the update 

 updatefound (registration) {
    console.log('New content is downloading.')
  },

  updated (registration) {
    console.log('New content is available; please refresh.')
    // let snackbar = document.getElementById('snackbar')
    // snackbar.className = 'show'
    /* document.getElementById('reload').addEventListener('click', function () {
      navigator.serviceWorker.addEventListener('controllerchange', () => {
        console.log('Doing refesh')
        window.location.reload(true)
      })
      // Test
      registration.waiting.postMessage({ type: 'SKIP_WAITING' })
    }) */
    console.log('Sending event')
    let UpdatedEvent = new CustomEvent('swUpdated', { detail: registration })
    document.dispatchEvent(UpdatedEvent)
  },

With the integration serviceworker OneSignal , How can I do ?

Best Regards

**Comment by nemoneph** [comment]
Hello,
I missed your issue.
Same problem here: #726 

(skipWaiting() called in the install event of OneSignalSDK is messing / auto-update the PWA and we can't control anymore "manually" the refresh).

**Comment by jkasten2** [comment]
Thanks for reporting, this is now fixed in version 151300 as `skipWaiting` and `clients.claim()` are no longer used by this SDK. It has been deployed to cdn.onesignal.com.
https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/151300

**Comment by nemoneph** [comment]
thx good job. Game changer.
