### ISSUE TITLE
Service worker: skipWaiting() in install is causing problem 

### ISSUE THREAD

**Issue by nemoneph** [OneSignal/OneSignal-Website-SDK#726]
**Description:**

Hello,

It's linked with issue #623

I have a PWA with my own ServiceWorker.
I have a "refresh" button to manually update my application. 
(it's a common workflow for handling update on a PWA).

After adding OneSignal SW with mine, my application and my SW is updated automaticaly...

It's because of the skipWaiting() called in the install setup here:
https://github.com/OneSignal/OneSignal-Website-SDK/blob/e530384b72bc69b1741112f05d55d55ec07fd704/src/service-worker/ServiceWorker.ts#L779-L791

I don't think that calling always / automatically skipWaiting() on the install is a good thing, it break update for some app and it can be dangerous.

See this excellent article about this: https://redfin.engineering/how-to-fix-the-refresh-button-when-using-service-workers-a8e27af6df68

Do you have a solution to prevent this ?

You can see complementary infos on PWA update here:

https://whatwebcando.today/articles/handling-service-worker-updates/
https://medium.com/@dougallrich/give-users-control-over-app-updates-in-vue-cli-3-pwas-20453aedc1f2

Thanks a lot.

**Comment by nseb** [comment]
@rgomezp , any updates ?

@nemoneph we have the same problem , it's painful, because for me it would be enough for him to work on their less intrusive service worker integration, and I sign immediately for my platform

**Comment by jkasten2** [comment]
Thanks for reporting, this is now fixed in version 151300 as `skipWaiting` and `clients.claim()` are no longer used by this SDK. It has been deployed to cdn.onesignal.com.
https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/151300
