### ISSUE TITLE
Automate documentation and type information from source

### ISSUE THREAD

**Issue by jskrzypek** [OneSignal/OneSignal-Website-SDK#73]
I'm building an angular2 app with OneScript to do push, and it would be nice to have a definition file to use with typescript that helps implement the API correctly. Are you likely to provide one in the future? If not and I end up writing one, would you guys be interested in bundling it with your SDK?

It would also be a good thing to write/provide for the cordova SDK, since then we could integrate it more easily into our ionic2 app.

**Comment by gdeglin** [comment]
Hi there. We likely won't have a chance to look into this ourselves for a while, but we would certainly be happy to accept a pull request for this.

**Comment by jasonpang** [comment]
Hey @jskrzypek,

This is an interesting idea! Unfortunately, as George said we probably won't get around to this for a long time. If you provide a definition file to use with TypeScript or another language, we will happily include it in our web SDK. You can comment on this thread anytime or email us at support@onesignal.com if you've got it, thanks!

**Comment by jskrzypek** [comment]
Great 😄 I'm going to circle back to the client side of our OneSignal integration next week

**Comment by ozwin** [comment]
@jskrzypek did you manage to make an integration for ng2 ? I would also be interested in this file if possible. Thanks !

**Comment by jskrzypek** [comment]
I haven't finished it because push notifications are an enhancement that i
keep having to sideline, but from the more recent experimentation that I've
done, the v3 docs are pretty straightforward and easy to follow. Looking at
the ionic2 docs will also prove useful.

**Comment by jasonpang** [comment]
Now that our SDK is written in TypeScript, we could use a tool that generates a typings module for our SDK based on our public API source file.

If someone is using Angular or TypeScript in general for their web project, they can reference our typings module and get auto completion for our public APIs and initialization function.

Working on this typings module would be a great opportunity to sync this information to our documentation.

**Comment by rgomezp** [comment]
Closing issue. Note: request still under consideration
