### ISSUE TITLE
window.OneSignal is undefined

### ISSUE THREAD

**Issue by zausailov** [OneSignal/OneSignal-Website-SDK#740]
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
`<script>
var nativePromptMessage = '';
var nativePromptAcceptButtonText = '';
var nativePromptCancelButtonText = '';

var OneSignal = window.OneSignal;

OneSignal.push(function () {
    OneSignal.init({
        appId: "ID",
        safari_web_id: "ID",
        notifyButton: {
            enable: true,
        },
        welcomeNotification: {
            disable: true,
        },
        promptOptions: {
            slidedown: {
                enabled: true,
                autoPrompt: true,
                timeDelay: 20,
                pageViews: 3,
                actionMessage: nativePromptMessage, 
                acceptButtonText: nativePromptAcceptButtonText,
                cancelButtonText: nativePromptCancelButtonText,
            }
        }
    });
    OneSignal.showSlidedownPrompt();

```
OneSignal.getNotificationPermission(function (permission) {
    if (permission === 'granted') {
        OneSignal.getUserId(function (userId) {
            localStorage.setItem('oneSignalUserId', userId);
        });
    } else if (localStorage.getItem('oneSignalUserId')) {
        localStorage.removeItem('oneSignalUserId');
    }
})
```

```
OneSignal.on('notificationPermissionChange', function (permissionChange) {
    if (permissionChange.to === 'granted') {
        OneSignal.getUserId(function (userId) {
            localStorage.setItem('oneSignalUserId', userId);
        });
    } else if (localStorage.getItem('oneSignalUserId')) {
        localStorage.removeItem('oneSignalUserId');
    }
});
```

});
</script>`

**Comment by jkasten2** [comment]
@zausailov It looks like you just forgot the `|| []` when definiting OneSignal.
Update `var OneSignal = window.OneSignal;` to `var OneSignal = window.OneSignal || [];` and things should be in working order.

Was this from any example code on onesignal.com? We can ensure we update it if so.

Let us know if you have any other issues with your OneSignal code and we can take a 2nd look.
