### ISSUE TITLE
If user deleted from OneSignal dashboard, wipe client-side data

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#75]
It's not intuitive that deleting a user from the OneSignal dashboard still leaves behind client-side data on the browser. IndexedDB should be wiped and the service worker should be unregistered (if possible, on HTTPS) if we get a no user with this ID found error indicating the user is deleted.

**Comment by jasonpang** [comment]
A table of actions that, when triggered, return the specified error if the user has been deleted from the dashboard:

Action | Error
--- | ---
Clicking setSubscription (clicking Subscribe/Unsubscribe on notify button) | `No user with this id found
Calling getTags | `Could not find app_id for given player id.`

**Comment by jasonpang** [comment]
#### New Behavior
If a user deletes their entry from the dashboard, and a user ...
- Refreshes the same page
  - Nothing will happen and the browser state will remain uncleared
- Opens a new tab or window to their auto-registering HTTPS site
  - The user will get a new user ID and a new user entry will be created. Browser data will be updated automatically
- Opens a new tab or window to their HTTP site
  - Nothing will happen and the browser state will remain uncleared; auto-resubscribing doesn't work for HTTP yet
- Triggers any API call listed in the previous comment
  - IndexedDB is cleared, and the user is unsubscribed from push notifications. The service worker is not removed, this seems to cause an issue where `navigator.serviceWorker.ready` hangs when testing so it seems unreliable for now. Unsubscribing seems to be enough to get a new user ID.

**Comment by jasonpang** [comment]
Implemented by: https://github.com/OneSignal/OneSignal-Website-SDK/commit/83f99c92ef32e52f5a2bba10cff7ece146572a01

**Comment by geenloop** [comment]
still the same problem, after deleting on OneSignal dashboard.... web app stop communicate at all

**Comment by floifyjames** [comment]
I'm also experiencing this issue.

**Comment by dmitry** [comment]
Deleted onesignal IndexedDB from applications in chrome.
