### ISSUE TITLE
Improvement: Use version number query param to cache break instead of filenames

### ISSUE THREAD

**Issue by jkasten2** [OneSignal/OneSignal-Website-SDK#757]
## Motivation
Today we instruct site owners to upload two files to their site, `OneSignalSDKWorker.js` and `OneSignalSDKUpdaterWorker.js`. This SDK will alternate between which one is registered when `OneSignalSDK.js` on the page detects an update. The SDK has to check which one is installed and then register the alternate worker filename.
In summary switching to a query string provides the following benefits:

* For site owner
  * Slightly simpler setup; upload one file vs two
  * Slightly less file clutter
  * ~1-2KiB smaller SDK size
* SDK team
  * Simplify ServiceWorker code and tests

## Confirming Solution
I confirmed this works by setting `'Cache-Control', 'public, max-age=86400'` on my server's HTTP response header and observing GET calls from the Edge browser each time `navigator.serviceWorker.register` is called with a different query param.
   - Confirmed this also works with the `{ updateViaCache: 'all' }` setting.
   - Recommend also confirming with Safari and Firefox before changing any code

## Changes
Today the SW is registered with the following with a URL that looks like this. `OneSignalSDKWorker.js?appId=YOUR_APP_ID` we will just need to add a `v=` query param to the end which would give us `OneSignalSDKWorker.js?appId=YOUR_APP_ID&v=ONESIGNAL_VERSION`.

### Code Changes
* [Any code that looks at `ServiceWorkerActiveState.WorkerA` vs `ServiceWorkerActiveState.WorkerB` ](https://github.com/OneSignal/OneSignal-Website-SDK/blob/151302/src/helpers/ServiceWorkerHelper.ts#L246-L259) could be cleaned up.
* Any code that calls `navigator.serviceWorker.register` needs to the new version number param.

**Comment by rgomezp** [comment]
This has been implemented
