### ISSUE TITLE
Add automatically appearing in-page modal dialog for users to subscribe for HTTP sites

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#78]
Requests since issue created: 2

Some of the users asking for this feature:

https://app.intercom.io/a/apps/344a89aeac3f033e4dec4370781543b948aece6d/inbox/web-push-team/conversations/5039983145

**Comment by sunilkr9871** [comment]
i am waiting too for this is option...

**Comment by gdeglin** [comment]
We just added this feature! https://documentation.onesignal.com/docs/web-push-http-prompt
