### ISSUE TITLE
Cross-Origin-Resource-Policy "cross-origin" not present in OneSignalSDK.js

### ISSUE THREAD

**Issue by arleyandrada** [OneSignal/OneSignal-Website-SDK#784]
Unable to make my website "cross-origin isolated" using COOP and COEP.
https://web.dev/coop-coep/

Resource:
https://cdn.onesignal.com/sdks/OneSignalSDK.js?

Error:
To use this resource from a different origin, the server needs to specify a cross-origin resource policy in the response headers.

Missing response header:
Cross-Origin-Resource-Policy: cross-origin

**Comment by rgomezp** [comment]
Howdy,
Thanks for your request. I will discuss internally to see if this is possible.

**Comment by rgomezp** [comment]
Just wanted to follow up. This seems like something that we could do, but we want to be careful and truly understand all of the implications of adding this header.

If you have any more information that could help us in making a final decision, please leave a comment.

**Comment by rgomezp** [comment]
Closing due to no response
