### ISSUE TITLE
Investigate allowing a CNAME'd subdomain to be used in place of ours for HTTP websites

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#80]

**Comment by centminmod** [comment]
much appreciated @jasonpang :+1:

**Comment by VIRTUALcast** [comment]
Very, very, very nice guys!

**Comment by jasonpang** [comment]
CC @VIRTUALcast @centminmod 

We looked into this issue and we've decided to not support this at the current time. It looks like we would have to modifying our server to dynamically accept different hosts, which isn't a feature we want to build at the moment. Sorry about the inconvenience, and if possible, please try switching to HTTPS!
