### ISSUE TITLE
Notification URLs without a scheme open relative to the subscribing origin

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#83]
For example, if we a send a notification using the URL `www.google.com`, our service worker says this is an invalid URL and it only works if we add `https://` or `http://`.

**Comment by jasonpang** [comment]
On second thought, the URL should just be entered. It wouldn't be good to guess whether we should use `http://` or `https://` if the protocol isn't specified.

**Comment by gdeglin** [comment]
Defaulting to http would be fine. This is what web browsers do (and then the webserver is expected to redirect to https for https-only sites)

**Comment by jasonpang** [comment]
This issue is occurring currently on sites (the latest SDK has been released yet) due to this line of code: https://github.com/OneSignal/OneSignal-Website-SDK/blob/2bf7b53b0b156c544ccd1f71d2535919576d87e3/src/serviceWorker.js#L328. There is no `try/catch` block around the `new URL(..)` statement, and a URL without a protocol is an invalid URL.

This issue has since been (accidentally) fixed while refactoring parts of the service worker. Now, notifications URLs without a protocol like `www.google.com` or `google.com` simply open relative to the subscribing origin.

So if a user subscribes to `site.com`, and sends a message to all his users with a notification URL of `abc.com`, the user would be redirected to `site.com/abc.com`.`
