### ISSUE TITLE
Is it possible to use web push on desktop app generated by the nativefier (from electron)?

### ISSUE THREAD

**Issue by YohaanYoon** [OneSignal/OneSignal-Website-SDK#840]
### Description

- Is it possible to use web push on desktop app generated by the nativefier (from electron)?

**Comment by rgomezp** [comment]
Howdy,
Thanks for the question. Unfortunately, while Electron supports service workers and uses the Notification API, they don't yet have Push API support.

You can read more about it [here](https://github.com/electron/electron/issues/6697)

**Comment by YohaanYoon** [comment]
@rgomezp 

I have one more question.
Is it possible to use web push on electron using https://github.com/MatthieuLemoine/electron-push-receiver?
I tested it and the electron received push notification with the fcm (firebase cloud messaging).

**Comment by jkasten2** [comment]
@YohaanYoon Thanks for pointing this out!

OneSignal doesn't have official support for this but others have gotten this to work with OneSignal in the past. See 
 https://github.com/OneSignal/OneSignal-Website-SDK/issues/98#issuecomment-444579207
