### ISSUE TITLE
Safari: Native prompt not working with user gesture

### ISSUE THREAD

**Issue by clementduncan** [OneSignal/OneSignal-Website-SDK#842]
**Description:**

Native Prompt doesn't appear in Safari on macOS / OSX.

`Error: Push notification prompting can only be done from a user gesture.   SubscriptionManager.js:212`

I've tested on Safari 14.1.1 on three Macs and once on the most recent Safari Tech Preview 14.2

**Steps to Reproduce Issue:**

Not a problem if bell clicked or if a slider is requested first.
Using Bell loads Native prompt straight away as I'd expect it to.
If slider `OneSignal.showSlidedownPrompt({force: true});` requested, slider appears, followed by the native prompt.

However if `promptOptions: { customLink: {` is setup within `OneSignal.init()` or custom code is used to trigger `showNativePrompt()`, the error appears and the native prompt doesn't load.

Both methods use a user gesture to init the native prompt, either onclick, eventListener or the built in OneSignal customlink button automatically created with `<div class='onesignal-customlink-container'></div>`.

Using the example code on OneSignal.com produces these issue [https://documentation.onesignal.com/docs/web-push-custom-code-examples](https://documentation.onesignal.com/docs/web-push-custom-code-examples)

**Anything else:**

This used to work (last successfully tested on 6 June 2021) but now I get an error. I don't know what has changed since.

**Comment by rgomezp** [comment]
Thank you for reporting this. It has been fixed in https://github.com/OneSignal/OneSignal-Website-SDK/pull/867
