### ISSUE TITLE
OneSignalApiBase.js:49 PUT https://onesignal.com/api/v1/players/*app id* 400

### ISSUE THREAD

**Issue by ilhmpy** [OneSignal/OneSignal-Website-SDK#846]
Hi all. I write app in React, TypeScript, in application must be a notifications, im use OneSignal and get error which i added in title of this issue. How to fix this? In google i don't find information which i need.

Here code which i use to connecting OneSignal to my app:
```
  (window as any) .OneSignal = (window as any) .OneSignal || [];
  const OneSignal = (window as any) .OneSignal;
  const appId = "de85aff6-eb35-4764-b6e3-1908687412fc";

  useEffect (() => {
    if (localStorage.getItem ("token")) {
      OneSignal.push (() => OneSignal.init ({appId}));
    };
  }, []);
```
(i check if user is authorization).

and here handler
```
subscribe  
  if (localStorage.getItem ("token")) {
      OneSignal.push (() => {
        OneSignal.on ("notificationPermissionChange", (data: any) => {
           console.log (data);
         });
      });
   };
```
I use ball-button. Sorry for my bad english, i need help.)

**Comment by rgomezp** [comment]
Howdy,
I think we can best address your problem if you reach out to our dedicated support team in the OneSignal.com intercom support chat.

Thanks
