### ISSUE TITLE
Notification not showing up coming in Chrome

### ISSUE THREAD

**Issue by dpramani** [OneSignal/OneSignal-Website-SDK#847]
I followed the following doc to initialize one signal in our react app.
https://documentation.onesignal.com/docs/web-push-typical-setup

And added the following code inside index.html

```
<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
<script>
      window.OneSignal = window.OneSignal || [];
      OneSignal.push(function() {
        OneSignal.init({
          appId: "",
          autoRegister: true,
          autoResubscribe:true,
          notifyButton: {
            enable: true,
          },
        });
      });
      OneSignal.push(function() {
        OneSignal.getUserId(function(userId) {
          console.log('Player id of the subscribed user is : ' + userId);
        });
      });
</script>

```

After doing that when I go to http://localhost:3000/, I do get the permissions prompt. Upon subscribing, a subscribed user is being added to the all users in the one signal dashboard.
But when I am trying to send a new push, the delivery is failing and also the user is transformed from subscribed to not subscribed. I am unsure of what exactly is happening.  Any ideas ?

Thanks
Debabrata Pramanik

**Comment by the-deadshot** [comment]
> I followed the following doc to initialize one signal in our react app.
> https://documentation.onesignal.com/docs/web-push-typical-setup
> 
> And added the following code inside index.html
> 
> ```
> <script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
> <script>
>       window.OneSignal = window.OneSignal || [];
>       OneSignal.push(function() {
>         OneSignal.init({
>           appId: "",
>           autoRegister: true,
>           autoResubscribe:true,
>           notifyButton: {
>             enable: true,
>           },
>         });
>       });
>       OneSignal.push(function() {
>         OneSignal.getUserId(function(userId) {
>           console.log('Player id of the subscribed user is : ' + userId);
>         });
>       });
> </script>
> ```
> 
> After doing that when I go to http://localhost:3000/, I do get the permissions prompt. Upon subscribing, a subscribed user is being added to the all users in the one signal dashboard.
> But when I am trying to send a new push, the delivery is failing and also the user is transformed from subscribed to not subscribed. I am unsure of what exactly is happening. Any ideas ?
> 
> Thanks
> Debabrata Pramanik

Have you found any solution for this?

**Comment by jkasten2** [comment]
If you have a PWA (which has it's own ServiceWorker) it might be replacing the OneSignal ServiceWorker, which will result in this unsubscribe issue.
I recommend customizing the ServiceWorker setup to a path so it does not interfere.
https://documentation.onesignal.com/docs/onesignal-service-worker-faq

**Comment by the-deadshot** [comment]
@jkasten2 Thank you it worked.

**Comment by rgomezp** [comment]
Fantastic!

**Comment by dpramani** [comment]
Thanks guys. I will be testing jkasten2's solution / docs. Thanks all for your help.
