### ISSUE TITLE
Does OneSignalServiceWorker natively not support PWA? Error in converting react app that is using OneSignal to PWA.

### ISSUE THREAD

**Issue by djaffer** [OneSignal/OneSignal-Website-SDK#849]
I am using react-app-rewired build and trying to convert the app to PWA. When 
I do build the service-worker.js is not there. Does OneSignalServiceWorker natively not support PWA?
config-override.js

```
module.exports = (config) => {
  config.module.rules[1].oneOf.unshift({
    test: /\.wasm$/,
    type: 'javascript/auto',
    loader: 'file-loader',
  });
  return config;
};
```

public/OneSignalSDKWorker.js

```
/* eslint-disable */
importScripts('https://cdn.onesignal.com/sdks/OneSignalSDKWorker.js');
// importScripts('./service-worker.js');
```

public/OneSignalSDKWorker.js
```

    /* eslint-disable */
    importScripts('https://cdn.onesignal.com/sdks/OneSignalSDKWorker.js');
    // importScripts('./service-worker.js');

```

package.json

```
"build": "react-app-rewired build",
```

src/index.js

```
import React from 'react';
import { render } from 'react-dom';
import { Provider } from 'react-redux';
import { ConnectedRouter } from 'connected-react-router';
import store, { history } from './store';
import App from './components/app';
import * as ServiceWorker from './serviceWorker';



const target = document.querySelector('#root');

render(
  <Provider store={store}>
    <ConnectedRouter history={history}>
      <App />
    </ConnectedRouter>
  </Provider>,
  target
);

 ServiceWorker.register();
```

**Comment by jkasten2** [comment]
@djaffer Your missing `service-worker.js` seems to be related an an issue with your PWA setup that is not related to OneSignal.

After you correct your issue with your `service-worker.js` file I recommend following the OneSignal setup guide below:
https://documentation.onesignal.com/docs/web-push-quickstart#step-6-upload-files

If you need to customize where your OneSignal specific ServiceWorker lives or it's scope please see this guide:
https://documentation.onesignal.com/docs/onesignal-service-worker-faq
