### ISSUE TITLE
The One Signal Slide down Dialog

### ISSUE THREAD

**Issue by wparslan** [OneSignal/OneSignal-Website-SDK#854]
The One signal Slide Down Dialog takes the whole page width which doesn't let click to link in it is in the way.
I have made a gif file for you as well from the OneSignal.com site as well.

![OneSignal](https://user-images.githubusercontent.com/66727492/130725607-78788458-db4c-4565-b7df-555b6cfa5904.gif)

**Comment by rgomezp** [comment]
Hello,
To click a link behind the dialog, simply click No Thanks to dismiss it.

Hope this helps
