### ISSUE TITLE
 OneSignal.init causes page to reload again and again

### ISSUE THREAD

**Issue by peshanghiwa** [OneSignal/OneSignal-Website-SDK#855]
Page keeps reloading

I am using nuxt framework with the official @nuxtjs/onesignal installed as dependency,
everything is configured the way that is mentioned in official one signal documentation.

when I run my project, every time OneSignal.init() runs, it causes the page to reload again creating infinite loop.

nuxt.config,js:
`
export default {
modules:[
 "@nuxtjs/onesignal",
 "@nuxtjs/pwa",
],

oneSignal: {
        init: {
            appId: "******************************",
            allowLocalhostAsSecureOrigin: true,
        },
    },
}
`

**Comment by DiegoPerea** [comment]
Same issue here. Did you work it out?

**Comment by peshanghiwa** [comment]
> Same issue here. Did you work it out?

No it turned out to unsolvable so i just decided to use firebase cloud messaging which worked well.

**Comment by rgomezp** [comment]
Howdy,
Please reach out to our OneSignal support team through our onesignal.com support chat for help debugging these types of issues.

Cheers!
