### ISSUE TITLE
Safari throws "The string did not match the expected pattern."

### ISSUE THREAD

**Issue by coppolafab** [OneSignal/OneSignal-Website-SDK#856]
**Description:**

Hi,
to start, thanks for all your work.

I'm facing this issue: after allowing native notification permission modal, an error is thrown on MacOs Safari.

**Steps to Reproduce Issue:**

1. Check that your Safari -> Preferences -> Privacy -> Prevent cross-site tracking, is unchecked.
2. Check you followed all steps here: https://documentation.onesignal.com/docs/troubleshooting-web-push#safari-troubleshooting
3. Visit your site, I'm in https://localhost, but occours also on different https domain (private staging)
4. Wait for prompt to appear or, indifferently, call showNativePrompt() from a click trigger
5. Click "Allow"
6. Read the following error in console:
UpdateManager.js:92
Failed to create user. Error "The string did not match the expected pattern,"

![index](https://user-images.githubusercontent.com/4855987/133587919-282496f1-fc8d-459d-b721-9928a4462835.jpeg)

**Anything else:**

Tested on Mac Os Safari 14.1.2 and 13.1.2.
The same setup used to work also on Safari (maybe a change in the SDK).
Currently it works on all other browsers.

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience. Can you please include the relevant OneSignal code snippet you are calling?

**Comment by rgomezp** [comment]
Closing for now. Please leave a comment if you are still seeing this issue and we can reopen
