### ISSUE TITLE
Red Notification Subscribe button no longer disappears 

### ISSUE THREAD

**Issue by seme1** [OneSignal/OneSignal-Website-SDK#865]
A user who is already subscribed should not see the red subscribe button. This was the case for almost the past two years till yesterday. No code changes were made to the website within the past 7 days.

When opening Developer tools, I see the "Installing worker..." message. Clicking the red Subscribe button causes the same "Installing Worker..."  message to appear again.

![image](https://user-images.githubusercontent.com/8105948/143446087-e9b16c99-b54e-4f04-aa23-b567da376036.png)

**Comment by seme1** [comment]
The problem disappeared today with no changes were made from our end. Did someone from onesignal fix it ?

**Comment by jkasten2** [comment]
@seme1 There was a new version released on 11/22 to optimize the ServiceWorker implementation to require only one file.
  - https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/151510

The change wasn't intended to fix any bugs , only to make the setup process easier and to provide a small optimization.
