### ISSUE TITLE
SDK initialization event is incompatible with CloudFlare's rocket loader

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#87]
```js
console.warn('Current Document ReadyState:', document.readyState);
document.onreadystatechange = () => console.warn('onreadystatechange ReadyState:', document.readyState);
window.addEventListener('DOMContentLoaded', () => console.warn('DOMContentLoaded ReadyState:', document.readyState));
window.addEventListener('load', () => console.warn('load ReadyState:', document.readyState));
```

Results:

```
Current Document ReadyState: loading
onreadystatechange ReadyState: loading
DOMContentLoaded ReadyState: loading
onreadystatechange ReadyState: loading
load ReadyState: loading
```

CloudFlare's rocket loader somehow modifies the loading events. However this event is still fired:

```
onreadystatechange: complete
```

So we should listen for that.

**Comment by jaydadarkar** [comment]
I am facing the same issue. Surprisingly, the bell is displayed on mobile permanently but not on desktop. It is displayed for the first time and then gone. Disabled the rocket loader. Lets see.

**Comment by kuaza61** [comment]
im enabled cloudflare rocket loader and change my wordpress plugins include js:
`<script data-cfasync="false" src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async></script>`

im added this tag:  data-cfasync="false"

is working but icon not working (for me don't problem).

**Comment by jasonpang** [comment]
Hi @kuaza61,

Could you let us know the URL of your site so that we can try to reproduce the issue?

**Comment by jasonpang** [comment]
Fixed by: https://github.com/OneSignal/OneSignal-Website-SDK/commit/57d3cf03a2883e384e3c6dfc2c230bbc75d966fc

**Comment by jasonpang** [comment]
Issue seems to be fixed.
