### ISSUE TITLE
Unable to run multiple one signal 'apps' due to db conflict

### ISSUE THREAD

**Issue by dotexe0** [OneSignal/OneSignal-Website-SDK#896]
I have tested this on Chrome (Version 96.0.4664.110) and Safari (Version 15.2 (15612.3.6.1.8, 15612)). This issue is only reproducible on Safari. Chrome seems to not have this issue.

If you have more than 1 project on One Signal, you are unable to run the SDK in subsequent websites you visit without the SDK crashing due to an error in `OneSignal/OneSignal-Website-SDK/build/ts-to-es6/src/services/IndexedDb.js`. 

In our case we have Dev, QA, Stage, Prod versions of the same website.

How to reproduce:
1. Use safari in Private mode.
2. Access any one of your apps with OneSignal SDK installed. 
3. Note no errors in logs.
4. Open a new tab, still in Private mode and access a _different_ app.
5. Note errors in console:
![image](https://user-images.githubusercontent.com/16355108/148834505-0481fcef-dd65-4bd9-9046-cefbfefbcd2e.png)
![image](https://user-images.githubusercontent.com/16355108/148834528-37b82063-387f-4780-a650-22fc90758fa8.png)

Creating a new Private window and accessing the app which failed previously will not result in errors being logged.

**Comment by rgomezp** [comment]
Hello, I have not been able to reproduce this.

So to confirm, you can only reproduce this in a private window on Safari, correct? I have tested on version 15.5.

Is this resulting in any side-effects affecting your app's execution? In other words, why is this a problem, given push is not even supported in a private window?

Just a little more context would be helpful. Cheers

**Comment by dotexe0** [comment]
It was only affecting devs, who accessed multiple environments (i.e. multiple, different instances of one-signal within a single org). The private window step was just to ensure you're on a clean browser instance -- issue was reproducible outside of private mode. We are no longer managing the app in question, so I will close as not reproducible.
