### ISSUE TITLE
[Question]: SDK's Version Lock

### ISSUE THREAD

**Issue by Airscripts** [OneSignal/OneSignal-Website-SDK#908]
### How can we help?

Hi! 😊  
First of all thank you so much for this SDK.  

I'm facing a security issue that I want to fix on my blog.  
Do you know how can I lock your SDK's version up?  

I need it in order to implement [SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) but I'm a little bit scared of hashing down the URL given on the documentation.  
Without proper version lock, the hash will change unexpectedly and this will break things up.  

If locking is not possible, copying the script locally to my repository would be problematic in terms of functionality?  
Thanks in advance for your time.

**Comment by rgomezp** [comment]
Howdy,
The SDK is just a group of scripts fetched from OneSignal's CDN. 

You can host a clone of the OneSignal SDK just note that you won't get new features released automatically. I think for your purposes this would be suitable enough.

You will need to host the OneSignalSDK.js, OneSignalPageSDKES6.js, and OneSignalSDKWorker.js

Check out https://github.com/OneSignal/OneSignal-Website-SDK/tree/main/express_webpack for info on how to build the SDK.

Enjoy!
