### ISSUE TITLE
Query/Enhancement: Need for expiry

### ISSUE THREAD

**Issue by rishab-yumist** [OneSignal/OneSignal-Website-SDK#96]
Hello @jasonpang ,

I'm wondering if there is an expiry feature for the push. For eg: I send a push now and the person doesn't open the push for a week, it should get expired within the given expiry time.

**Comment by jasonpang** [comment]
Hello @rishab-yumist,

Could you take a look at this answer and let us know if it doesn't answer your question completely? https://documentation.onesignal.com/docs/frequently-asked-questions#section-do-users-receive-web-push-notifications-when-the-browser-isn-t-running-
