### ISSUE TITLE
Installing service worker failed (due to passing of 2 params without using '&' by OneSignal)

### ISSUE THREAD

**Issue by tuberelevant2** [OneSignal/OneSignal-Website-SDK#973]
### How can we help?

I've added the OneSignal service worker on my site accessible from https://syllabuzz.in/_functions/OneSignalSDKWorkerjs
It has an HTTP header to register in the root directory. And OneSignal knows where to look for it. (image below)
<img width="503" alt="image" src="https://user-images.githubusercontent.com/104287304/209468345-8ea904c3-69dc-42c8-bf0e-994312c0483d.png">

Earlier this used to work fine but now OneSignal calls the SW script by passing 2 parameters without using '&'.
https://www.syllabuzz.in/_functions/OneSignalSDKWorkerjs?appId=1ed59dfe-493a-40a9-b5b9-a07ed0f532a2?sdkVersion=151514
This makes the page blank and it doesn't load. And I see an error in the console.
<img width="532" alt="image" src="https://user-images.githubusercontent.com/104287304/209468569-5015b669-401a-4d39-9885-4fb14d8b058b.png">

The script does have a valid MIME type. It's just the 2 params without '&' which cause the issue.
Earlier only one parameter (appID) was passed, which used to work.

Also, the SW script loads when the last param is passed with '&' instead of '?'.
https://www.syllabuzz.in/_functions/OneSignalSDKWorkerjs?appId=1ed59dfe-493a-40a9-b5b9-a07ed0f532a2&sdkVersion=151514

Any suggestions on how do I fix it? Or OneSignal needs to update how it calls the SW script?
Thanks.

**Comment by rgomezp** [comment]
Howdy,
A couple things:
1. Is there a reason you named the file OneSignalSDKWorkerjs and not `.js`?
2. I see that you're attempting to register the service worker yourself. This is not necessary as the SDK will register it for you.

```

if('serviceWorker' in navigator){
  navigator.serviceWorker.register('/_functions/OneSignalSDKWorkerjs?appId=1ed59dfe-493a-40a9-b5b9-a07ed0f532a2&sdkVersion=151514', { scope: "/" })
    .then(reg => console.log('service worker registered'))
    .catch(err => console.log('service worker not registered', err));
}
```

3. I believe you're on Typical Setup when your site might need "Custom Code" since you're trying to do something more complex.
4. Please see our [documentation](https://documentation.onesignal.com/docs/onesignal-service-worker-
faq#customizing-your-service-worker-integration) on customizing your service worker for more info

**Comment by tuberelevant2** [comment]
> Hi!
Yes, there's a reason for naming it 'js' instead of '.js'. It's just one of the limitations of Velo by Wix. But, I don't think that will cause a problem because the SW file is viewable.

When I posted the Issue here, I removed the custom registration of SW but added it again after a while. I have removed it now. You can check. I was trying custom registration with '&' instead of '?' before the second parameter, and it successfully registers the worker but OneSignal registers with '?' before the second param which causes it to fail.

Also, I can use custom setup but I can't find a way in the documentation where we can manually register sw and onesignal will accept it. OneSignal always tries to register the worker itself. 
The only difference in custom setup is that it asks the path of sw file in the code. That's what I have found. Maybe you can guide me in the right direction.

Thank You.

**Comment by tuberelevant2** [comment]
Thank You. May I know when will the changes be published?
