### ISSUE TITLE
[Question]: Upgrade to nodejs v18

### ISSUE THREAD

**Issue by Sthanasis** [OneSignal/OneSignal-Website-SDK#987]
### How can we help?

Hello! I 'm trying to upgrade the node version on my project to version 18 lts but I can not do it due to node-sass incompatibility. I've figured out that it is because onesignal-website-sdk uses node-sass version 4 and in order to upgrade to node 18, node-sass needs to be 8.0+ according to the guide here https://www.npmjs.com/package/node-sass. Is there a plan to upgrade this dependency on onesignal-website-sdk? Thank you in advance!!

**Comment by rgomezp** [comment]
Howdy! We are in the midst of a major release (currently in beta) which may be a good opportunity to do so. Thanks for the suggestion!
