### ISSUE TITLE
[Feature Request] Users wanting the HTTP prompt on HTTPS sites

### ISSUE THREAD

**Issue by jasonpang** [OneSignal/OneSignal-Website-SDK#99]
This feature is currently only available for HTTPS sites. The reason we made the feature only available for HTTPS sites is because we did not think most users wanted to click twice: once on the onboarding popup, and again on the "Allow" for notifications. Because the browser's permission prompt cannot be bypassed and must be shown, the HTTPS subscription flow is designed to only use that dialog to keep the number of users dialog must click through to a minimum.

Currently there's just no way to show that dialog on an  HTTPS site since it's currently hardcoded not to show for an HTTPS site.

Requests: ~3

**Comment by bwente** [comment]
I think of it as more of an onboarding step. Web notifications are new to most people, and this gives you a way to explain it in more detail. I like how it shows the user what to expect.

**Comment by jasonpang** [comment]
Hi @bwente,

It's now possible to manually display the HTTP prompt, but it won't be automatically shown (unless you do so from code via `OneSignal.push(["showHttpPrompt"])` (this can be done before the `init()` call and the SDK should wait for `init()` to finish first.
