### ISSUE TITLE
[Bug]: Safari doesn't get a notification with the content of more than one language

### ISSUE THREAD

**Issue by tachigami** [OneSignal/OneSignal-Website-SDK#993]
### What happened?

I tried to send a notification in English and German to Safari/Chrome/Firefox but only Chrome and Firefox received that notification. Then I left English as the one language and Safari finally received it.

### What browsers are you seeing the problem on?

Safari

### What operating system are you running?

macOS Ventura 13.2

### Steps to reproduce?

```Markdown
1. Go to Dashboard > Messages > Templates
2. Select any template
3. Add one more language and fill in Title and Message
4. Go to "Platform settings" and enable "Send to Safari"
5. Hit "Send Test Push"
6. Select Safari and confirm
```

### What did you expect to happen?

Safari displays the notification.

**Comment by nan-li** [comment]
Hi, we have had no further reports of this. Please upgrade the OneSignal SDK if you or anyone is still having this issue. If this is still an issue, please open a new report with updated information.
