### ISSUE TITLE
[Question]: Parameter message.action.subscribed don't working

### ISSUE THREAD

**Issue by rafaelmamorim** [OneSignal/OneSignal-Website-SDK#994]
### How can we help?

I used Onesignal's custom code on the opensource-socialnetwork.org system and after a user signs up, the message shown to the user is always "Thanks for subscribing".

I tried the welcomeNotification parameter and couldn't get it to work.

Is there any parameter to enable the value that I declared? My browser is in Portuguese and no matter the message, it never changes.

**Comment by rgomezp** [comment]
Howdy, yes.

With the following code, you can get the resulting notification:

```js
OneSignal.sendSelfNotification("hello", "example");
```
<img width="197" alt="Screen Shot 2023-02-22 at 2 03 34 PM" src="https://user-images.githubusercontent.com/11739227/220746412-2441b19b-30fc-4b4b-8764-f798f6333c41.png">

Enjoy!

**Comment by rafaelmamorim** [comment]
I need a way to overwrite the oneSignal default self notification or change the text of default notification.

**Comment by rgomezp** [comment]
Hey there Rafael. My apologies.

Take a look at our [documentation here](https://documentation.onesignal.com/docs/web-push-sdk#init-welcomenotification-parameters). 

The values you are looking for should be `title` and `message`.

If that is not the answer you're looking for, please provide the actual initialization code you are using.

**Comment by rafaelmamorim** [comment]
Working now. Thank you
